<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>VcfSdkDotnet</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="InternalViJson/src/Vcenter.ViJson.OpenApi/Vcenter.ViJson.OpenApi.csproj" />
    <ProjectReference Include="InternalOpenApi/src/Vcenter.Automation.OpenApi/Vcenter.Automation.OpenApi.csproj" />
  </ItemGroup>

</Project>