/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// This schema is deprecated as of __vSphere API 9.1.0.0__.  The Appliance.Health.Database.Message schema contains a database health message along with its severity.  This schema was added in __vSphere API 7.0.0.1__.
    /// </summary>
    [DataContract(Name = "Appliance.Health.Database.Message")]
    public partial class ApplianceHealthDatabaseMessage : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApplianceHealthDatabaseMessage" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ApplianceHealthDatabaseMessage() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ApplianceHealthDatabaseMessage" /> class.
        /// </summary>
        /// <param name="severity">This property is deprecated as of __vSphere API 9.1.0.0__.  Severity of the message.  Possible values:   - &#x60;ERROR&#x60;: Error message.   - &#x60;WARNING&#x60;: Warning message.   For more information see: *Appliance.Health.Database.Message.Severity*.  This property was added in __vSphere API 7.0.0.1__. (required).</param>
        /// <param name="message">This property is deprecated as of __vSphere API 9.1.0.0__.  Message describing the issue with the database.  This property was added in __vSphere API 7.0.0.1__. (required).</param>
        public ApplianceHealthDatabaseMessage(string severity = default, VapiStdLocalizableMessage message = default)
        {
            // to ensure "severity" is required (not null)
            if (severity == null)
            {
                throw new ArgumentNullException("severity is a required property for ApplianceHealthDatabaseMessage and cannot be null");
            }
            this.Severity = severity;
            // to ensure "message" is required (not null)
            if (message == null)
            {
                throw new ArgumentNullException("message is a required property for ApplianceHealthDatabaseMessage and cannot be null");
            }
            this.Message = message;
        }

        /// <summary>
        /// This property is deprecated as of __vSphere API 9.1.0.0__.  Severity of the message.  Possible values:   - &#x60;ERROR&#x60;: Error message.   - &#x60;WARNING&#x60;: Warning message.   For more information see: *Appliance.Health.Database.Message.Severity*.  This property was added in __vSphere API 7.0.0.1__.
        /// </summary>
        /// <value>This property is deprecated as of __vSphere API 9.1.0.0__.  Severity of the message.  Possible values:   - &#x60;ERROR&#x60;: Error message.   - &#x60;WARNING&#x60;: Warning message.   For more information see: *Appliance.Health.Database.Message.Severity*.  This property was added in __vSphere API 7.0.0.1__.</value>
        [DataMember(Name = "severity", IsRequired = true, EmitDefaultValue = true)]
        public string Severity { get; set; }

        /// <summary>
        /// This property is deprecated as of __vSphere API 9.1.0.0__.  Message describing the issue with the database.  This property was added in __vSphere API 7.0.0.1__.
        /// </summary>
        /// <value>This property is deprecated as of __vSphere API 9.1.0.0__.  Message describing the issue with the database.  This property was added in __vSphere API 7.0.0.1__.</value>
        [DataMember(Name = "message", IsRequired = true, EmitDefaultValue = true)]
        public VapiStdLocalizableMessage Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApplianceHealthDatabaseMessage {\n");
            sb.Append("  Severity: ").Append(Severity).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
