/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// The Appliance.Recovery.Info schema contains the information about the appliance recovery environment.  This schema was added in __vSphere API 6.7__.
    /// </summary>
    [DataContract(Name = "Appliance.Recovery.Info")]
    public partial class ApplianceRecoveryInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApplianceRecoveryInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ApplianceRecoveryInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ApplianceRecoveryInfo" /> class.
        /// </summary>
        /// <param name="supported">Is recovery supported in this appliance.  This property was added in __vSphere API 6.7__. (required).</param>
        public ApplianceRecoveryInfo(bool supported = default)
        {
            this.Supported = supported;
        }

        /// <summary>
        /// Is recovery supported in this appliance.  This property was added in __vSphere API 6.7__.
        /// </summary>
        /// <value>Is recovery supported in this appliance.  This property was added in __vSphere API 6.7__.</value>
        [DataMember(Name = "supported", IsRequired = true, EmitDefaultValue = true)]
        public bool Supported { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApplianceRecoveryInfo {\n");
            sb.Append("  Supported: ").Append(Supported).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
