/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// CisTaggingTagAssociationAttachRequest
    /// </summary>
    [DataContract(Name = "Cis_Tagging_TagAssociation_attach_request")]
    public partial class CisTaggingTagAssociationAttachRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CisTaggingTagAssociationAttachRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CisTaggingTagAssociationAttachRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CisTaggingTagAssociationAttachRequest" /> class.
        /// </summary>
        /// <param name="objectId">objectId (required).</param>
        public CisTaggingTagAssociationAttachRequest(VapiStdDynamicID objectId = default)
        {
            // to ensure "objectId" is required (not null)
            if (objectId == null)
            {
                throw new ArgumentNullException("objectId is a required property for CisTaggingTagAssociationAttachRequest and cannot be null");
            }
            this.ObjectId = objectId;
        }

        /// <summary>
        /// Gets or Sets ObjectId
        /// </summary>
        [DataMember(Name = "object_id", IsRequired = true, EmitDefaultValue = true)]
        public VapiStdDynamicID ObjectId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CisTaggingTagAssociationAttachRequest {\n");
            sb.Append("  ObjectId: ").Append(ObjectId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
