/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// The Content.Library.Item.DownloadSessionModel schema provides information on an active *Content.Library.Item.DownloadSession* resource.
    /// </summary>
    [DataContract(Name = "Content.Library.Item.DownloadSessionModel")]
    public partial class ContentLibraryItemDownloadSessionModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ContentLibraryItemDownloadSessionModel" /> class.
        /// </summary>
        /// <param name="id">The identifier of this download session.  This property is not used for the &#x60;create&#x60; operation. It will not be present in the response of the &#x60;get&#x60; or &#x60;list&#x60; operations. It is not used for the &#x60;update&#x60; operation.  When clients pass a value of this schema as a parameter, the property must be an identifier for the resource type: &#x60;com.vmware.content.library.item.DownloadSession&#x60;. When operations return a value of this schema as a response, the property will be an identifier for the resource type: &#x60;com.vmware.content.library.item.DownloadSession&#x60;..</param>
        /// <param name="libraryItemId">The identifier of the library item whose content is being downloaded.  This property must be provided for the &#x60;create&#x60; operation. It will always be present in the response of the &#x60;get&#x60; or &#x60;list&#x60; operations. It is not used for the &#x60;update&#x60; operation.  When clients pass a value of this schema as a parameter, the property must be an identifier for the resource type: &#x60;com.vmware.content.library.Item&#x60;. When operations return a value of this schema as a response, the property will be an identifier for the resource type: &#x60;com.vmware.content.library.Item&#x60;..</param>
        /// <param name="libraryItemContentVersion">The content version of the library item whose content is being downloaded. This value is the *Content.Library.ItemModel.content_version* at the time when the session is created for the library item.  This property is not used for the &#x60;create&#x60; operation. It will always be present in the response of the &#x60;get&#x60; or &#x60;list&#x60; operations. It is not used for the &#x60;update&#x60; operation..</param>
        /// <param name="errorMessage">If the session is in the *Content.Library.Item.DownloadSessionModel.State.ERROR* status this property will have more details about the error.  This property is not used for the &#x60;create&#x60; operation. It is optional in the response of the &#x60;get&#x60; or &#x60;list&#x60; operations. It is not used for the &#x60;update&#x60; operation..</param>
        /// <param name="clientProgress">The progress that has been made with the download. This property is to be updated by the client during the download process to indicate the progress of its work in completing the download. The initial progress is 0 until updated by the client. The maximum value is 100, which indicates that the download is complete.  This property is not used for the &#x60;create&#x60; operation. It will always be present in the response of the &#x60;get&#x60; or &#x60;list&#x60; operations. It is optional for the &#x60;update&#x60; operation..</param>
        /// <param name="state">The current state (State) of the download session.  Possible values:   - &#x60;ACTIVE&#x60;: The session is active. Individual files may be in the process of being transferred and may become ready for download at different times.   - &#x60;CANCELED&#x60;: The session has been canceled. On-going downloads may fail. The session will stay in this state until it is either deleted by the user or automatically cleaned up by the Content Library Service.   - &#x60;ERROR&#x60;: Indicates there was an error during the session lifecycle.   For more information see: *Content.Library.Item.DownloadSessionModel.State*.  This property is not used for the &#x60;create&#x60; operation. It will always be present in the response of the &#x60;get&#x60; or &#x60;list&#x60; operations. It is not used for the &#x60;update&#x60; operation..</param>
        /// <param name="expirationTime">Indicates the time after which the session will expire. The session is guaranteed not to expire before this time.  This property is not used for the &#x60;create&#x60; operation. It will always be present in the response of the &#x60;get&#x60; or &#x60;list&#x60; operations. It is not used for the &#x60;update&#x60; operation..</param>
        public ContentLibraryItemDownloadSessionModel(string id = default, string libraryItemId = default, string libraryItemContentVersion = default, VapiStdLocalizableMessage errorMessage = default, long clientProgress = default, string state = default, DateTime expirationTime = default)
        {
            this.Id = id;
            this.LibraryItemId = libraryItemId;
            this.LibraryItemContentVersion = libraryItemContentVersion;
            this.ErrorMessage = errorMessage;
            this.ClientProgress = clientProgress;
            this.State = state;
            this.ExpirationTime = expirationTime;
        }

        /// <summary>
        /// The identifier of this download session.  This property is not used for the &#x60;create&#x60; operation. It will not be present in the response of the &#x60;get&#x60; or &#x60;list&#x60; operations. It is not used for the &#x60;update&#x60; operation.  When clients pass a value of this schema as a parameter, the property must be an identifier for the resource type: &#x60;com.vmware.content.library.item.DownloadSession&#x60;. When operations return a value of this schema as a response, the property will be an identifier for the resource type: &#x60;com.vmware.content.library.item.DownloadSession&#x60;.
        /// </summary>
        /// <value>The identifier of this download session.  This property is not used for the &#x60;create&#x60; operation. It will not be present in the response of the &#x60;get&#x60; or &#x60;list&#x60; operations. It is not used for the &#x60;update&#x60; operation.  When clients pass a value of this schema as a parameter, the property must be an identifier for the resource type: &#x60;com.vmware.content.library.item.DownloadSession&#x60;. When operations return a value of this schema as a response, the property will be an identifier for the resource type: &#x60;com.vmware.content.library.item.DownloadSession&#x60;.</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// The identifier of the library item whose content is being downloaded.  This property must be provided for the &#x60;create&#x60; operation. It will always be present in the response of the &#x60;get&#x60; or &#x60;list&#x60; operations. It is not used for the &#x60;update&#x60; operation.  When clients pass a value of this schema as a parameter, the property must be an identifier for the resource type: &#x60;com.vmware.content.library.Item&#x60;. When operations return a value of this schema as a response, the property will be an identifier for the resource type: &#x60;com.vmware.content.library.Item&#x60;.
        /// </summary>
        /// <value>The identifier of the library item whose content is being downloaded.  This property must be provided for the &#x60;create&#x60; operation. It will always be present in the response of the &#x60;get&#x60; or &#x60;list&#x60; operations. It is not used for the &#x60;update&#x60; operation.  When clients pass a value of this schema as a parameter, the property must be an identifier for the resource type: &#x60;com.vmware.content.library.Item&#x60;. When operations return a value of this schema as a response, the property will be an identifier for the resource type: &#x60;com.vmware.content.library.Item&#x60;.</value>
        [DataMember(Name = "library_item_id", EmitDefaultValue = false)]
        public string LibraryItemId { get; set; }

        /// <summary>
        /// The content version of the library item whose content is being downloaded. This value is the *Content.Library.ItemModel.content_version* at the time when the session is created for the library item.  This property is not used for the &#x60;create&#x60; operation. It will always be present in the response of the &#x60;get&#x60; or &#x60;list&#x60; operations. It is not used for the &#x60;update&#x60; operation.
        /// </summary>
        /// <value>The content version of the library item whose content is being downloaded. This value is the *Content.Library.ItemModel.content_version* at the time when the session is created for the library item.  This property is not used for the &#x60;create&#x60; operation. It will always be present in the response of the &#x60;get&#x60; or &#x60;list&#x60; operations. It is not used for the &#x60;update&#x60; operation.</value>
        [DataMember(Name = "library_item_content_version", EmitDefaultValue = false)]
        public string LibraryItemContentVersion { get; set; }

        /// <summary>
        /// If the session is in the *Content.Library.Item.DownloadSessionModel.State.ERROR* status this property will have more details about the error.  This property is not used for the &#x60;create&#x60; operation. It is optional in the response of the &#x60;get&#x60; or &#x60;list&#x60; operations. It is not used for the &#x60;update&#x60; operation.
        /// </summary>
        /// <value>If the session is in the *Content.Library.Item.DownloadSessionModel.State.ERROR* status this property will have more details about the error.  This property is not used for the &#x60;create&#x60; operation. It is optional in the response of the &#x60;get&#x60; or &#x60;list&#x60; operations. It is not used for the &#x60;update&#x60; operation.</value>
        [DataMember(Name = "error_message", EmitDefaultValue = false)]
        public VapiStdLocalizableMessage ErrorMessage { get; set; }

        /// <summary>
        /// The progress that has been made with the download. This property is to be updated by the client during the download process to indicate the progress of its work in completing the download. The initial progress is 0 until updated by the client. The maximum value is 100, which indicates that the download is complete.  This property is not used for the &#x60;create&#x60; operation. It will always be present in the response of the &#x60;get&#x60; or &#x60;list&#x60; operations. It is optional for the &#x60;update&#x60; operation.
        /// </summary>
        /// <value>The progress that has been made with the download. This property is to be updated by the client during the download process to indicate the progress of its work in completing the download. The initial progress is 0 until updated by the client. The maximum value is 100, which indicates that the download is complete.  This property is not used for the &#x60;create&#x60; operation. It will always be present in the response of the &#x60;get&#x60; or &#x60;list&#x60; operations. It is optional for the &#x60;update&#x60; operation.</value>
        [DataMember(Name = "client_progress", EmitDefaultValue = false)]
        public long ClientProgress { get; set; }

        /// <summary>
        /// The current state (State) of the download session.  Possible values:   - &#x60;ACTIVE&#x60;: The session is active. Individual files may be in the process of being transferred and may become ready for download at different times.   - &#x60;CANCELED&#x60;: The session has been canceled. On-going downloads may fail. The session will stay in this state until it is either deleted by the user or automatically cleaned up by the Content Library Service.   - &#x60;ERROR&#x60;: Indicates there was an error during the session lifecycle.   For more information see: *Content.Library.Item.DownloadSessionModel.State*.  This property is not used for the &#x60;create&#x60; operation. It will always be present in the response of the &#x60;get&#x60; or &#x60;list&#x60; operations. It is not used for the &#x60;update&#x60; operation.
        /// </summary>
        /// <value>The current state (State) of the download session.  Possible values:   - &#x60;ACTIVE&#x60;: The session is active. Individual files may be in the process of being transferred and may become ready for download at different times.   - &#x60;CANCELED&#x60;: The session has been canceled. On-going downloads may fail. The session will stay in this state until it is either deleted by the user or automatically cleaned up by the Content Library Service.   - &#x60;ERROR&#x60;: Indicates there was an error during the session lifecycle.   For more information see: *Content.Library.Item.DownloadSessionModel.State*.  This property is not used for the &#x60;create&#x60; operation. It will always be present in the response of the &#x60;get&#x60; or &#x60;list&#x60; operations. It is not used for the &#x60;update&#x60; operation.</value>
        [DataMember(Name = "state", EmitDefaultValue = false)]
        public string State { get; set; }

        /// <summary>
        /// Indicates the time after which the session will expire. The session is guaranteed not to expire before this time.  This property is not used for the &#x60;create&#x60; operation. It will always be present in the response of the &#x60;get&#x60; or &#x60;list&#x60; operations. It is not used for the &#x60;update&#x60; operation.
        /// </summary>
        /// <value>Indicates the time after which the session will expire. The session is guaranteed not to expire before this time.  This property is not used for the &#x60;create&#x60; operation. It will always be present in the response of the &#x60;get&#x60; or &#x60;list&#x60; operations. It is not used for the &#x60;update&#x60; operation.</value>
        [DataMember(Name = "expiration_time", EmitDefaultValue = false)]
        public DateTime ExpirationTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ContentLibraryItemDownloadSessionModel {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  LibraryItemId: ").Append(LibraryItemId).Append("\n");
            sb.Append("  LibraryItemContentVersion: ").Append(LibraryItemContentVersion).Append("\n");
            sb.Append("  ErrorMessage: ").Append(ErrorMessage).Append("\n");
            sb.Append("  ClientProgress: ").Append(ClientProgress).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  ExpirationTime: ").Append(ExpirationTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
