/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// Provide network information in a template VM.
    /// </summary>
    [DataContract(Name = "Content.Type.Ovf.Network")]
    public partial class ContentTypeOvfNetwork : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ContentTypeOvfNetwork" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ContentTypeOvfNetwork() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ContentTypeOvfNetwork" /> class.
        /// </summary>
        /// <param name="name">Name of the network (required).</param>
        /// <param name="description">Description of the network  Networks do not require a description..</param>
        public ContentTypeOvfNetwork(string name = default, string description = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for ContentTypeOvfNetwork and cannot be null");
            }
            this.Name = name;
            this.Description = description;
        }

        /// <summary>
        /// Name of the network
        /// </summary>
        /// <value>Name of the network</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Description of the network  Networks do not require a description.
        /// </summary>
        /// <value>Description of the network  Networks do not require a description.</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ContentTypeOvfNetwork {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
