/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// The Esx.Settings.Depots.Offline.AuthenticationSpec.AuthenticationMethod enumerated type defines the possible methods of authentication supported when connecting to the remote depot.  Possible values:   - &#x60;HEADER_AUTH&#x60;: HEADER_AUTH is intended to be used when connecting to a remote depot   This enumeration was added in __vSphere API 9.0.0.0__.
    /// </summary>
    /// <value>The Esx.Settings.Depots.Offline.AuthenticationSpec.AuthenticationMethod enumerated type defines the possible methods of authentication supported when connecting to the remote depot.  Possible values:   - &#x60;HEADER_AUTH&#x60;: HEADER_AUTH is intended to be used when connecting to a remote depot   This enumeration was added in __vSphere API 9.0.0.0__.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum EsxSettingsDepotsOfflineAuthenticationSpecAuthenticationMethod
    {
        /// <summary>
        /// Enum HEADERAUTH for value: HEADER_AUTH
        /// </summary>
        [EnumMember(Value = "HEADER_AUTH")]
        HEADERAUTH = 1
    }

}
