/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// The possible sources of the schema.  Possible values:   - &#x60;IMAGE_PROFILE&#x60;: The schema was derived from a VLCM image profile.   - &#x60;HOST&#x60;: The schema was extracted from a reference host.   This enumeration was added in __vSphere API 8.0.3.0__.
    /// </summary>
    /// <value>The possible sources of the schema.  Possible values:   - &#x60;IMAGE_PROFILE&#x60;: The schema was derived from a VLCM image profile.   - &#x60;HOST&#x60;: The schema was extracted from a reference host.   This enumeration was added in __vSphere API 8.0.3.0__.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum EsxSettingsClustersConfigurationSchemaResultSource
    {
        /// <summary>
        /// Enum IMAGEPROFILE for value: IMAGE_PROFILE
        /// </summary>
        [EnumMember(Value = "IMAGE_PROFILE")]
        IMAGEPROFILE = 1,

        /// <summary>
        /// Enum HOST for value: HOST
        /// </summary>
        [EnumMember(Value = "HOST")]
        HOST = 2
    }

}
