/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// The Esx.Settings.Depots.Offline.CreateResult schema defines the result information for a new offline depot.  This schema was added in __vSphere API 7.0.0.0__.
    /// </summary>
    [DataContract(Name = "Esx.Settings.Depots.Offline.CreateResult")]
    public partial class EsxSettingsDepotsOfflineCreateResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EsxSettingsDepotsOfflineCreateResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EsxSettingsDepotsOfflineCreateResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EsxSettingsDepotsOfflineCreateResult" /> class.
        /// </summary>
        /// <param name="depot">Identifier of the offline depot.  This property was added in __vSphere API 7.0.0.0__.  When clients pass a value of this schema as a parameter, the property must be an identifier for the resource type: &#x60;com.vmware.esx.settings.depots.offline&#x60;. When operations return a value of this schema as a response, the property will be an identifier for the resource type: &#x60;com.vmware.esx.settings.depots.offline&#x60;. (required).</param>
        public EsxSettingsDepotsOfflineCreateResult(string depot = default)
        {
            // to ensure "depot" is required (not null)
            if (depot == null)
            {
                throw new ArgumentNullException("depot is a required property for EsxSettingsDepotsOfflineCreateResult and cannot be null");
            }
            this.Depot = depot;
        }

        /// <summary>
        /// Identifier of the offline depot.  This property was added in __vSphere API 7.0.0.0__.  When clients pass a value of this schema as a parameter, the property must be an identifier for the resource type: &#x60;com.vmware.esx.settings.depots.offline&#x60;. When operations return a value of this schema as a response, the property will be an identifier for the resource type: &#x60;com.vmware.esx.settings.depots.offline&#x60;.
        /// </summary>
        /// <value>Identifier of the offline depot.  This property was added in __vSphere API 7.0.0.0__.  When clients pass a value of this schema as a parameter, the property must be an identifier for the resource type: &#x60;com.vmware.esx.settings.depots.offline&#x60;. When operations return a value of this schema as a response, the property will be an identifier for the resource type: &#x60;com.vmware.esx.settings.depots.offline&#x60;.</value>
        [DataMember(Name = "depot", IsRequired = true, EmitDefaultValue = true)]
        public string Depot { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EsxSettingsDepotsOfflineCreateResult {\n");
            sb.Append("  Depot: ").Append(Depot).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
