/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// This Esx.Settings.HostSoftwarePolicySpecResetInfo schema contains properties that describes the outcome when the configured settings that govern the software behaviour in the *POST /esx/settings/hosts/{host}/software?action&#x3D;apply* API are reset.  This schema was added in __vSphere API 9.1.0.0__.
    /// </summary>
    [DataContract(Name = "Esx.Settings.HostSoftwarePolicySpecResetInfo")]
    public partial class EsxSettingsHostSoftwarePolicySpecResetInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EsxSettingsHostSoftwarePolicySpecResetInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EsxSettingsHostSoftwarePolicySpecResetInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EsxSettingsHostSoftwarePolicySpecResetInfo" /> class.
        /// </summary>
        /// <param name="from">The configured values of *Esx.Settings.Hosts.Policies.Apply.ConfiguredPolicySpec.software_policy_spec*.  This property was added in __vSphere API 9.1.0.0__. (required).</param>
        /// <param name="to">The values of *Esx.Settings.Hosts.Policies.Apply.ConfiguredPolicySpec.software_policy_spec* when the configured value is reset.  This property was added in __vSphere API 9.1.0.0__. (required).</param>
        public EsxSettingsHostSoftwarePolicySpecResetInfo(EsxSettingsHostSoftwarePolicySpec from = default, EsxSettingsHostSoftwarePolicySpec to = default)
        {
            // to ensure "from" is required (not null)
            if (from == null)
            {
                throw new ArgumentNullException("from is a required property for EsxSettingsHostSoftwarePolicySpecResetInfo and cannot be null");
            }
            this.From = from;
            // to ensure "to" is required (not null)
            if (to == null)
            {
                throw new ArgumentNullException("to is a required property for EsxSettingsHostSoftwarePolicySpecResetInfo and cannot be null");
            }
            this.To = to;
        }

        /// <summary>
        /// The configured values of *Esx.Settings.Hosts.Policies.Apply.ConfiguredPolicySpec.software_policy_spec*.  This property was added in __vSphere API 9.1.0.0__.
        /// </summary>
        /// <value>The configured values of *Esx.Settings.Hosts.Policies.Apply.ConfiguredPolicySpec.software_policy_spec*.  This property was added in __vSphere API 9.1.0.0__.</value>
        [DataMember(Name = "from", IsRequired = true, EmitDefaultValue = true)]
        public EsxSettingsHostSoftwarePolicySpec From { get; set; }

        /// <summary>
        /// The values of *Esx.Settings.Hosts.Policies.Apply.ConfiguredPolicySpec.software_policy_spec* when the configured value is reset.  This property was added in __vSphere API 9.1.0.0__.
        /// </summary>
        /// <value>The values of *Esx.Settings.Hosts.Policies.Apply.ConfiguredPolicySpec.software_policy_spec* when the configured value is reset.  This property was added in __vSphere API 9.1.0.0__.</value>
        [DataMember(Name = "to", IsRequired = true, EmitDefaultValue = true)]
        public EsxSettingsHostSoftwarePolicySpec To { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EsxSettingsHostSoftwarePolicySpecResetInfo {\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
