/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// The Esx.Settings.Clusters.Configuration.Drafts.ChangedProperty schema contains information about a property that is different in this draft from the committed configuration.  This schema was added in __vSphere API 8.0.2.0__.
    /// </summary>
    [DataContract(Name = "Esx.Settings.Clusters.Configuration.Drafts.ChangedProperty")]
    public partial class EsxSettingsClustersConfigurationDraftsChangedProperty : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EsxSettingsClustersConfigurationDraftsChangedProperty" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EsxSettingsClustersConfigurationDraftsChangedProperty() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EsxSettingsClustersConfigurationDraftsChangedProperty" /> class.
        /// </summary>
        /// <param name="path">A JSON-Pointer that refers to the property that has been changed.  This property was added in __vSphere API 8.0.2.0__. (required).</param>
        /// <param name="displayPath">A list of the display names for components of *Esx.Settings.Clusters.Configuration.Drafts.ChangedProperty.path* property.  This property was added in __vSphere API 9.1.0.0__.  This field is missing or &#x60;null&#x60; if the display names cannot be computed..</param>
        /// <param name="type">The data type of the property pointed by {#path}.  Possible values:   - &#x60;PRIMITIVE&#x60;: The changed property is of primitive data type.   - &#x60;OBJECT&#x60;: The changed property is of type object.   - &#x60;ARRAY_OF_OBJECTS&#x60;: The changed property is of array of object data type.   - &#x60;ARRAY_OF_PRIMITIVES&#x60;: The changed property is of array of primitive data type.   For more information see: *Esx.Settings.Clusters.Configuration.Drafts.ChangedProperty.Type*.  This property was added in __vSphere API 9.1.0.0__.  This field is missing or &#x60;null&#x60; if the data type of the property is not available..</param>
        /// <param name="current">This property was added in __vSphere API 8.0.2.0__.  If set, the current value of the property in the cluster configuration. If not set, the property does not exist in the current cluster configuration..</param>
        /// <param name="draft">This property was added in __vSphere API 8.0.2.0__.  If set, this is the new value for the property in this draft. If not set, the property has been deleted in this draft..</param>
        public EsxSettingsClustersConfigurationDraftsChangedProperty(string path = default, List<string> displayPath = default, string type = default, string current = default, string draft = default)
        {
            // to ensure "path" is required (not null)
            if (path == null)
            {
                throw new ArgumentNullException("path is a required property for EsxSettingsClustersConfigurationDraftsChangedProperty and cannot be null");
            }
            this.Path = path;
            this.DisplayPath = displayPath;
            this.Type = type;
            this.Current = current;
            this.Draft = draft;
        }

        /// <summary>
        /// A JSON-Pointer that refers to the property that has been changed.  This property was added in __vSphere API 8.0.2.0__.
        /// </summary>
        /// <value>A JSON-Pointer that refers to the property that has been changed.  This property was added in __vSphere API 8.0.2.0__.</value>
        [DataMember(Name = "path", IsRequired = true, EmitDefaultValue = true)]
        public string Path { get; set; }

        /// <summary>
        /// A list of the display names for components of *Esx.Settings.Clusters.Configuration.Drafts.ChangedProperty.path* property.  This property was added in __vSphere API 9.1.0.0__.  This field is missing or &#x60;null&#x60; if the display names cannot be computed.
        /// </summary>
        /// <value>A list of the display names for components of *Esx.Settings.Clusters.Configuration.Drafts.ChangedProperty.path* property.  This property was added in __vSphere API 9.1.0.0__.  This field is missing or &#x60;null&#x60; if the display names cannot be computed.</value>
        [DataMember(Name = "display_path", EmitDefaultValue = false)]
        public List<string> DisplayPath { get; set; }

        /// <summary>
        /// The data type of the property pointed by {#path}.  Possible values:   - &#x60;PRIMITIVE&#x60;: The changed property is of primitive data type.   - &#x60;OBJECT&#x60;: The changed property is of type object.   - &#x60;ARRAY_OF_OBJECTS&#x60;: The changed property is of array of object data type.   - &#x60;ARRAY_OF_PRIMITIVES&#x60;: The changed property is of array of primitive data type.   For more information see: *Esx.Settings.Clusters.Configuration.Drafts.ChangedProperty.Type*.  This property was added in __vSphere API 9.1.0.0__.  This field is missing or &#x60;null&#x60; if the data type of the property is not available.
        /// </summary>
        /// <value>The data type of the property pointed by {#path}.  Possible values:   - &#x60;PRIMITIVE&#x60;: The changed property is of primitive data type.   - &#x60;OBJECT&#x60;: The changed property is of type object.   - &#x60;ARRAY_OF_OBJECTS&#x60;: The changed property is of array of object data type.   - &#x60;ARRAY_OF_PRIMITIVES&#x60;: The changed property is of array of primitive data type.   For more information see: *Esx.Settings.Clusters.Configuration.Drafts.ChangedProperty.Type*.  This property was added in __vSphere API 9.1.0.0__.  This field is missing or &#x60;null&#x60; if the data type of the property is not available.</value>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// This property was added in __vSphere API 8.0.2.0__.  If set, the current value of the property in the cluster configuration. If not set, the property does not exist in the current cluster configuration.
        /// </summary>
        /// <value>This property was added in __vSphere API 8.0.2.0__.  If set, the current value of the property in the cluster configuration. If not set, the property does not exist in the current cluster configuration.</value>
        [DataMember(Name = "current", EmitDefaultValue = false)]
        public string Current { get; set; }

        /// <summary>
        /// This property was added in __vSphere API 8.0.2.0__.  If set, this is the new value for the property in this draft. If not set, the property has been deleted in this draft.
        /// </summary>
        /// <value>This property was added in __vSphere API 8.0.2.0__.  If set, this is the new value for the property in this draft. If not set, the property has been deleted in this draft.</value>
        [DataMember(Name = "draft", EmitDefaultValue = false)]
        public string Draft { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EsxSettingsClustersConfigurationDraftsChangedProperty {\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("  DisplayPath: ").Append(DisplayPath).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Current: ").Append(Current).Append("\n");
            sb.Append("  Draft: ").Append(Draft).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
