/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// The Esx.Settings.Clusters.Vms.Solutions.ApplyStatus schema contains properties that describe the status of an *POST /esx/settings/clusters/{cluster}/vms/solutions?action&#x3D;apply* operation.  This schema was added in __vSphere API 9.0.0.0__.
    /// </summary>
    [DataContract(Name = "Esx.Settings.Clusters.Vms.Solutions.ApplyStatus")]
    public partial class EsxSettingsClustersVmsSolutionsApplyStatus : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EsxSettingsClustersVmsSolutionsApplyStatus" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EsxSettingsClustersVmsSolutionsApplyStatus() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EsxSettingsClustersVmsSolutionsApplyStatus" /> class.
        /// </summary>
        /// <param name="status">The status of the operation.  Possible values:   - &#x60;SUCCESS&#x60;: The apply operation completed successfully.   - &#x60;ERROR&#x60;: The apply operation encountered an error.   For more information see: *Esx.Settings.Clusters.Vms.Solutions.ApplyStatus.Status*.  This property was added in __vSphere API 9.0.0.0__.  missing or &#x60;null&#x60; if the operation is not completed..</param>
        /// <param name="startTime">The vLCM system time when the operation started.  This property was added in __vSphere API 9.0.0.0__. (required).</param>
        /// <param name="endTime">The vLCM system time when the operation completed.  This property was added in __vSphere API 9.0.0.0__.  This property is optional and it is only relevant when the value of status is one of *Esx.Settings.Clusters.Vms.Solutions.ApplyStatus.Status.SUCCESS* or *Esx.Settings.Clusters.Vms.Solutions.ApplyStatus.Status.ERROR*..</param>
        public EsxSettingsClustersVmsSolutionsApplyStatus(string status = default, DateTime startTime = default, DateTime endTime = default)
        {
            this.StartTime = startTime;
            this.Status = status;
            this.EndTime = endTime;
        }

        /// <summary>
        /// The status of the operation.  Possible values:   - &#x60;SUCCESS&#x60;: The apply operation completed successfully.   - &#x60;ERROR&#x60;: The apply operation encountered an error.   For more information see: *Esx.Settings.Clusters.Vms.Solutions.ApplyStatus.Status*.  This property was added in __vSphere API 9.0.0.0__.  missing or &#x60;null&#x60; if the operation is not completed.
        /// </summary>
        /// <value>The status of the operation.  Possible values:   - &#x60;SUCCESS&#x60;: The apply operation completed successfully.   - &#x60;ERROR&#x60;: The apply operation encountered an error.   For more information see: *Esx.Settings.Clusters.Vms.Solutions.ApplyStatus.Status*.  This property was added in __vSphere API 9.0.0.0__.  missing or &#x60;null&#x60; if the operation is not completed.</value>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public string Status { get; set; }

        /// <summary>
        /// The vLCM system time when the operation started.  This property was added in __vSphere API 9.0.0.0__.
        /// </summary>
        /// <value>The vLCM system time when the operation started.  This property was added in __vSphere API 9.0.0.0__.</value>
        [DataMember(Name = "start_time", IsRequired = true, EmitDefaultValue = true)]
        public DateTime StartTime { get; set; }

        /// <summary>
        /// The vLCM system time when the operation completed.  This property was added in __vSphere API 9.0.0.0__.  This property is optional and it is only relevant when the value of status is one of *Esx.Settings.Clusters.Vms.Solutions.ApplyStatus.Status.SUCCESS* or *Esx.Settings.Clusters.Vms.Solutions.ApplyStatus.Status.ERROR*.
        /// </summary>
        /// <value>The vLCM system time when the operation completed.  This property was added in __vSphere API 9.0.0.0__.  This property is optional and it is only relevant when the value of status is one of *Esx.Settings.Clusters.Vms.Solutions.ApplyStatus.Status.SUCCESS* or *Esx.Settings.Clusters.Vms.Solutions.ApplyStatus.Status.ERROR*.</value>
        [DataMember(Name = "end_time", EmitDefaultValue = false)]
        public DateTime EndTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EsxSettingsClustersVmsSolutionsApplyStatus {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  StartTime: ").Append(StartTime).Append("\n");
            sb.Append("  EndTime: ").Append(EndTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
