/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// The Esx.Settings.Clusters.Software.Reports.StorageDeviceCompliance schema contains information that describe the compliance result of all storage devices from all hosts in the cluster with respect to the storage device model and the firmware certification  This schema was added in __vSphere API 7.0.2.1__.
    /// </summary>
    [DataContract(Name = "Esx.Settings.Clusters.Software.Reports.StorageDeviceCompliance")]
    public partial class EsxSettingsClustersSoftwareReportsStorageDeviceCompliance : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EsxSettingsClustersSoftwareReportsStorageDeviceCompliance" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EsxSettingsClustersSoftwareReportsStorageDeviceCompliance() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EsxSettingsClustersSoftwareReportsStorageDeviceCompliance" /> class.
        /// </summary>
        /// <param name="status">Overall compliance status of storage devices in the cluster with respect to all hosts in the cluster.  Possible values:   - &#x60;COMPATIBLE&#x60;: Target hardware is compliant with Broadcom Compatibility Guide (BCG)   - &#x60;INCOMPATIBLE&#x60;: Target hardware is not (recognizably) compliant with Broadcom Compatibility Guide (BCG)   - &#x60;HCL_DATA_UNAVAILABLE&#x60;: Never returned by the HCL compliance APIs  HCL data can not be fetched to validate cluster hardware.   - &#x60;UNAVAILABLE&#x60;: Target hardware compliance with Broadcom Compatibility Guide (BCG) cannot be determined.   - &#x60;NO_FIRMWARE_PROVIDER&#x60;: Never returned by the HCL compliance APIs  No Firmware HSM present in Software Spec to get Firmware Details *Esx.Settings.HardwareSupportPackageInfo* schema   For more information see: *Esx.Settings.Clusters.Software.Reports.ComplianceStatus*.  This property was added in __vSphere API 7.0.2.1__. (required).</param>
        /// <param name="compatibleDevices">Lists compliance information for storage devices found to be compliant with Broadcom Compatibility Guide (BCG) during the last check operation.    Note that complianceStatus of every device is not necessarily COMPATIBLE due to changes made after this check was run; entries are only rearranged when a new check operation is invoked. lastOverrideTime being greater than the scanTime is an indication that there were changes made after the last check operation  This property was added in __vSphere API 7.0.2.1__. (required).</param>
        /// <param name="incompatibleDevices">Lists compliance information for storage devices found to be non-compliant with Broadcom Compatibility Guide (BCG) during the last check operation.    Note that complianceStatus of every device is not necessarily INCOMPATIBLE due to changes made after this check was run; entries are only rearranged when a new check operation is invoked. lastOverrideTime being greater than the scanTime is an indication that there were changes made after the last check operation  This property was added in __vSphere API 7.0.2.1__. (required).</param>
        /// <param name="unknownDevices">Lists storage devices whose compliance information could not be computed successfully during the last check operation.    Note that complianceStatus of every device is not necessarily UNAVAILABLE due to changes made after this check was run; entries are only rearranged when a new check operation is invoked. lastOverrideTime being greater than the scanTime is an indication that there were changes made after the last check operation  This property was added in __vSphere API 7.0.2.1__. (required).</param>
        /// <param name="notifications">Storage device compliance specific notifications describing the compliance result.  This property was added in __vSphere API 7.0.2.1__.  This property will be missing or &#x60;null&#x60; if there are no notifications.</param>
        public EsxSettingsClustersSoftwareReportsStorageDeviceCompliance(string status = default, List<EsxSettingsClustersSoftwareReportsStorageDeviceComplianceInfo> compatibleDevices = default, List<EsxSettingsClustersSoftwareReportsStorageDeviceComplianceInfo> incompatibleDevices = default, List<EsxSettingsClustersSoftwareReportsStorageDeviceComplianceInfo> unknownDevices = default, EsxSettingsNotifications notifications = default)
        {
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for EsxSettingsClustersSoftwareReportsStorageDeviceCompliance and cannot be null");
            }
            this.Status = status;
            // to ensure "compatibleDevices" is required (not null)
            if (compatibleDevices == null)
            {
                throw new ArgumentNullException("compatibleDevices is a required property for EsxSettingsClustersSoftwareReportsStorageDeviceCompliance and cannot be null");
            }
            this.CompatibleDevices = compatibleDevices;
            // to ensure "incompatibleDevices" is required (not null)
            if (incompatibleDevices == null)
            {
                throw new ArgumentNullException("incompatibleDevices is a required property for EsxSettingsClustersSoftwareReportsStorageDeviceCompliance and cannot be null");
            }
            this.IncompatibleDevices = incompatibleDevices;
            // to ensure "unknownDevices" is required (not null)
            if (unknownDevices == null)
            {
                throw new ArgumentNullException("unknownDevices is a required property for EsxSettingsClustersSoftwareReportsStorageDeviceCompliance and cannot be null");
            }
            this.UnknownDevices = unknownDevices;
            this.Notifications = notifications;
        }

        /// <summary>
        /// Overall compliance status of storage devices in the cluster with respect to all hosts in the cluster.  Possible values:   - &#x60;COMPATIBLE&#x60;: Target hardware is compliant with Broadcom Compatibility Guide (BCG)   - &#x60;INCOMPATIBLE&#x60;: Target hardware is not (recognizably) compliant with Broadcom Compatibility Guide (BCG)   - &#x60;HCL_DATA_UNAVAILABLE&#x60;: Never returned by the HCL compliance APIs  HCL data can not be fetched to validate cluster hardware.   - &#x60;UNAVAILABLE&#x60;: Target hardware compliance with Broadcom Compatibility Guide (BCG) cannot be determined.   - &#x60;NO_FIRMWARE_PROVIDER&#x60;: Never returned by the HCL compliance APIs  No Firmware HSM present in Software Spec to get Firmware Details *Esx.Settings.HardwareSupportPackageInfo* schema   For more information see: *Esx.Settings.Clusters.Software.Reports.ComplianceStatus*.  This property was added in __vSphere API 7.0.2.1__.
        /// </summary>
        /// <value>Overall compliance status of storage devices in the cluster with respect to all hosts in the cluster.  Possible values:   - &#x60;COMPATIBLE&#x60;: Target hardware is compliant with Broadcom Compatibility Guide (BCG)   - &#x60;INCOMPATIBLE&#x60;: Target hardware is not (recognizably) compliant with Broadcom Compatibility Guide (BCG)   - &#x60;HCL_DATA_UNAVAILABLE&#x60;: Never returned by the HCL compliance APIs  HCL data can not be fetched to validate cluster hardware.   - &#x60;UNAVAILABLE&#x60;: Target hardware compliance with Broadcom Compatibility Guide (BCG) cannot be determined.   - &#x60;NO_FIRMWARE_PROVIDER&#x60;: Never returned by the HCL compliance APIs  No Firmware HSM present in Software Spec to get Firmware Details *Esx.Settings.HardwareSupportPackageInfo* schema   For more information see: *Esx.Settings.Clusters.Software.Reports.ComplianceStatus*.  This property was added in __vSphere API 7.0.2.1__.</value>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// Lists compliance information for storage devices found to be compliant with Broadcom Compatibility Guide (BCG) during the last check operation.    Note that complianceStatus of every device is not necessarily COMPATIBLE due to changes made after this check was run; entries are only rearranged when a new check operation is invoked. lastOverrideTime being greater than the scanTime is an indication that there were changes made after the last check operation  This property was added in __vSphere API 7.0.2.1__.
        /// </summary>
        /// <value>Lists compliance information for storage devices found to be compliant with Broadcom Compatibility Guide (BCG) during the last check operation.    Note that complianceStatus of every device is not necessarily COMPATIBLE due to changes made after this check was run; entries are only rearranged when a new check operation is invoked. lastOverrideTime being greater than the scanTime is an indication that there were changes made after the last check operation  This property was added in __vSphere API 7.0.2.1__.</value>
        [DataMember(Name = "compatible_devices", IsRequired = true, EmitDefaultValue = true)]
        public List<EsxSettingsClustersSoftwareReportsStorageDeviceComplianceInfo> CompatibleDevices { get; set; }

        /// <summary>
        /// Lists compliance information for storage devices found to be non-compliant with Broadcom Compatibility Guide (BCG) during the last check operation.    Note that complianceStatus of every device is not necessarily INCOMPATIBLE due to changes made after this check was run; entries are only rearranged when a new check operation is invoked. lastOverrideTime being greater than the scanTime is an indication that there were changes made after the last check operation  This property was added in __vSphere API 7.0.2.1__.
        /// </summary>
        /// <value>Lists compliance information for storage devices found to be non-compliant with Broadcom Compatibility Guide (BCG) during the last check operation.    Note that complianceStatus of every device is not necessarily INCOMPATIBLE due to changes made after this check was run; entries are only rearranged when a new check operation is invoked. lastOverrideTime being greater than the scanTime is an indication that there were changes made after the last check operation  This property was added in __vSphere API 7.0.2.1__.</value>
        [DataMember(Name = "incompatible_devices", IsRequired = true, EmitDefaultValue = true)]
        public List<EsxSettingsClustersSoftwareReportsStorageDeviceComplianceInfo> IncompatibleDevices { get; set; }

        /// <summary>
        /// Lists storage devices whose compliance information could not be computed successfully during the last check operation.    Note that complianceStatus of every device is not necessarily UNAVAILABLE due to changes made after this check was run; entries are only rearranged when a new check operation is invoked. lastOverrideTime being greater than the scanTime is an indication that there were changes made after the last check operation  This property was added in __vSphere API 7.0.2.1__.
        /// </summary>
        /// <value>Lists storage devices whose compliance information could not be computed successfully during the last check operation.    Note that complianceStatus of every device is not necessarily UNAVAILABLE due to changes made after this check was run; entries are only rearranged when a new check operation is invoked. lastOverrideTime being greater than the scanTime is an indication that there were changes made after the last check operation  This property was added in __vSphere API 7.0.2.1__.</value>
        [DataMember(Name = "unknown_devices", IsRequired = true, EmitDefaultValue = true)]
        public List<EsxSettingsClustersSoftwareReportsStorageDeviceComplianceInfo> UnknownDevices { get; set; }

        /// <summary>
        /// Storage device compliance specific notifications describing the compliance result.  This property was added in __vSphere API 7.0.2.1__.  This property will be missing or &#x60;null&#x60; if there are no notifications
        /// </summary>
        /// <value>Storage device compliance specific notifications describing the compliance result.  This property was added in __vSphere API 7.0.2.1__.  This property will be missing or &#x60;null&#x60; if there are no notifications</value>
        [DataMember(Name = "notifications", EmitDefaultValue = false)]
        public EsxSettingsNotifications Notifications { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EsxSettingsClustersSoftwareReportsStorageDeviceCompliance {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CompatibleDevices: ").Append(CompatibleDevices).Append("\n");
            sb.Append("  IncompatibleDevices: ").Append(IncompatibleDevices).Append("\n");
            sb.Append("  UnknownDevices: ").Append(UnknownDevices).Append("\n");
            sb.Append("  Notifications: ").Append(Notifications).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
