/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// The Esx.Settings.Clusters.Configuration.Drafts.ApplySpec schema contains properties that are used to create a new commit.  This schema was added in __vSphere API 8.0.2.0__.
    /// </summary>
    [DataContract(Name = "Esx.Settings.Clusters.Configuration.Drafts.ApplySpec")]
    public partial class EsxSettingsClustersConfigurationDraftsApplySpec : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EsxSettingsClustersConfigurationDraftsApplySpec" /> class.
        /// </summary>
        /// <param name="message">Message to include with the commit.  This property was added in __vSphere API 8.0.2.0__.  If missing or &#x60;null&#x60;, message is set to empty string..</param>
        /// <param name="applyPolicySpec">The parameter can be used to override the default remediation policies for the apply task.  This property was added in __vSphere API 8.0.2.0__.  if missing or &#x60;null&#x60; the default cluster remediation policies are used..</param>
        /// <param name="driftReviews">This field contains the drifts that need review from the user before apply.  This property was added in __vSphere API 9.1.0.0__.  This property is optional because it was added in a newer version than its parent node..</param>
        public EsxSettingsClustersConfigurationDraftsApplySpec(string message = default, EsxSettingsClustersPoliciesApplyEffectiveEffectivePolicySpec applyPolicySpec = default, List<EsxSettingsClustersConfigurationDriftReview> driftReviews = default)
        {
            this.Message = message;
            this.ApplyPolicySpec = applyPolicySpec;
            this.DriftReviews = driftReviews;
        }

        /// <summary>
        /// Message to include with the commit.  This property was added in __vSphere API 8.0.2.0__.  If missing or &#x60;null&#x60;, message is set to empty string.
        /// </summary>
        /// <value>Message to include with the commit.  This property was added in __vSphere API 8.0.2.0__.  If missing or &#x60;null&#x60;, message is set to empty string.</value>
        [DataMember(Name = "message", EmitDefaultValue = false)]
        public string Message { get; set; }

        /// <summary>
        /// The parameter can be used to override the default remediation policies for the apply task.  This property was added in __vSphere API 8.0.2.0__.  if missing or &#x60;null&#x60; the default cluster remediation policies are used.
        /// </summary>
        /// <value>The parameter can be used to override the default remediation policies for the apply task.  This property was added in __vSphere API 8.0.2.0__.  if missing or &#x60;null&#x60; the default cluster remediation policies are used.</value>
        [DataMember(Name = "apply_policy_spec", EmitDefaultValue = false)]
        public EsxSettingsClustersPoliciesApplyEffectiveEffectivePolicySpec ApplyPolicySpec { get; set; }

        /// <summary>
        /// This field contains the drifts that need review from the user before apply.  This property was added in __vSphere API 9.1.0.0__.  This property is optional because it was added in a newer version than its parent node.
        /// </summary>
        /// <value>This field contains the drifts that need review from the user before apply.  This property was added in __vSphere API 9.1.0.0__.  This property is optional because it was added in a newer version than its parent node.</value>
        [DataMember(Name = "drift_reviews", EmitDefaultValue = false)]
        public List<EsxSettingsClustersConfigurationDriftReview> DriftReviews { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EsxSettingsClustersConfigurationDraftsApplySpec {\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  ApplyPolicySpec: ").Append(ApplyPolicySpec).Append("\n");
            sb.Append("  DriftReviews: ").Append(DriftReviews).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
