/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// The Esx.Settings.Clusters.Vms.LifecycleHooks.ListResult schema contains properties that describe all activated hooks that the system is waiting to be processed by a given solution.  This schema was added in __vSphere API 9.0.0.0__.
    /// </summary>
    [DataContract(Name = "Esx.Settings.Clusters.Vms.LifecycleHooks.ListResult")]
    public partial class EsxSettingsClustersVmsLifecycleHooksListResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EsxSettingsClustersVmsLifecycleHooksListResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EsxSettingsClustersVmsLifecycleHooksListResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EsxSettingsClustersVmsLifecycleHooksListResult" /> class.
        /// </summary>
        /// <param name="hooks">Activated Hooks that the system is waiting for solutions to process.  This property was added in __vSphere API 9.0.0.0__. (required).</param>
        public EsxSettingsClustersVmsLifecycleHooksListResult(List<EsxSettingsClustersVmsLifecycleHookInfo> hooks = default)
        {
            // to ensure "hooks" is required (not null)
            if (hooks == null)
            {
                throw new ArgumentNullException("hooks is a required property for EsxSettingsClustersVmsLifecycleHooksListResult and cannot be null");
            }
            this.Hooks = hooks;
        }

        /// <summary>
        /// Activated Hooks that the system is waiting for solutions to process.  This property was added in __vSphere API 9.0.0.0__.
        /// </summary>
        /// <value>Activated Hooks that the system is waiting for solutions to process.  This property was added in __vSphere API 9.0.0.0__.</value>
        [DataMember(Name = "hooks", IsRequired = true, EmitDefaultValue = true)]
        public List<EsxSettingsClustersVmsLifecycleHookInfo> Hooks { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EsxSettingsClustersVmsLifecycleHooksListResult {\n");
            sb.Append("  Hooks: ").Append(Hooks).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
