/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// The Vcenter.Deployment.Question.Info schema contains properties to describe questions raised during the deployment process.  This schema was added in __vSphere API 6.7__.
    /// </summary>
    [DataContract(Name = "Vcenter.Deployment.Question.Info")]
    public partial class VcenterDeploymentQuestionInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VcenterDeploymentQuestionInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VcenterDeploymentQuestionInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VcenterDeploymentQuestionInfo" /> class.
        /// </summary>
        /// <param name="questions">One or more questions raised during the deployment.  This property was added in __vSphere API 6.7__. (required).</param>
        public VcenterDeploymentQuestionInfo(List<VcenterDeploymentQuestionQuestion> questions = default)
        {
            // to ensure "questions" is required (not null)
            if (questions == null)
            {
                throw new ArgumentNullException("questions is a required property for VcenterDeploymentQuestionInfo and cannot be null");
            }
            this.Questions = questions;
        }

        /// <summary>
        /// One or more questions raised during the deployment.  This property was added in __vSphere API 6.7__.
        /// </summary>
        /// <value>One or more questions raised during the deployment.  This property was added in __vSphere API 6.7__.</value>
        [DataMember(Name = "questions", IsRequired = true, EmitDefaultValue = true)]
        public List<VcenterDeploymentQuestionQuestion> Questions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VcenterDeploymentQuestionInfo {\n");
            sb.Append("  Questions: ").Append(Questions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
