/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// The Vcenter.TrustedInfrastructure.Hosts.Hardware.Tpm.EventLog.Info schema contains information that describes an event log.  This schema was added in __vSphere API 8.0.0.1__.
    /// </summary>
    [DataContract(Name = "Vcenter.TrustedInfrastructure.Hosts.Hardware.Tpm.EventLog.Info")]
    public partial class VcenterTrustedInfrastructureHostsHardwareTpmEventLogInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VcenterTrustedInfrastructureHostsHardwareTpmEventLogInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VcenterTrustedInfrastructureHostsHardwareTpmEventLogInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VcenterTrustedInfrastructureHostsHardwareTpmEventLogInfo" /> class.
        /// </summary>
        /// <param name="type">Type of the event log.  Possible values:   - &#x60;EFI_TCG2_EVENT_LOG_FORMAT_TCG_2&#x60;: TCG EFI Protocol Specification, Family \&quot;2.0\&quot;, Level 00 Revision 00.13, March 30, 2016, Section 5.2 Crypto Agile Log Entry Format.   For more information see: *Vcenter.TrustedInfrastructure.Hosts.Hardware.Tpm.EventLog.Type*.  This property was added in __vSphere API 8.0.0.1__. (required).</param>
        /// <param name="data">Event log data in the format described by *Vcenter.TrustedInfrastructure.Hosts.Hardware.Tpm.EventLog.Info.type*.  This property was added in __vSphere API 8.0.0.1__.  This property is currently required. It may be optional in a future version..</param>
        /// <param name="truncated">Indicates if the event log is truncated.    An event log is truncated when there was insufficient memory to store one or more event entries.  This property was added in __vSphere API 8.0.0.1__. (required).</param>
        /// <param name="banks">The resulting PCR banks from event log replay.  This property was added in __vSphere API 8.0.0.1__. (required).</param>
        public VcenterTrustedInfrastructureHostsHardwareTpmEventLogInfo(string type = default, byte[] data = default, bool truncated = default, List<VcenterTrustedInfrastructureHostsHardwareTpmPcrBank> banks = default)
        {
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for VcenterTrustedInfrastructureHostsHardwareTpmEventLogInfo and cannot be null");
            }
            this.Type = type;
            this.Truncated = truncated;
            // to ensure "banks" is required (not null)
            if (banks == null)
            {
                throw new ArgumentNullException("banks is a required property for VcenterTrustedInfrastructureHostsHardwareTpmEventLogInfo and cannot be null");
            }
            this.Banks = banks;
            this.Data = data;
        }

        /// <summary>
        /// Type of the event log.  Possible values:   - &#x60;EFI_TCG2_EVENT_LOG_FORMAT_TCG_2&#x60;: TCG EFI Protocol Specification, Family \&quot;2.0\&quot;, Level 00 Revision 00.13, March 30, 2016, Section 5.2 Crypto Agile Log Entry Format.   For more information see: *Vcenter.TrustedInfrastructure.Hosts.Hardware.Tpm.EventLog.Type*.  This property was added in __vSphere API 8.0.0.1__.
        /// </summary>
        /// <value>Type of the event log.  Possible values:   - &#x60;EFI_TCG2_EVENT_LOG_FORMAT_TCG_2&#x60;: TCG EFI Protocol Specification, Family \&quot;2.0\&quot;, Level 00 Revision 00.13, March 30, 2016, Section 5.2 Crypto Agile Log Entry Format.   For more information see: *Vcenter.TrustedInfrastructure.Hosts.Hardware.Tpm.EventLog.Type*.  This property was added in __vSphere API 8.0.0.1__.</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Event log data in the format described by *Vcenter.TrustedInfrastructure.Hosts.Hardware.Tpm.EventLog.Info.type*.  This property was added in __vSphere API 8.0.0.1__.  This property is currently required. It may be optional in a future version.
        /// </summary>
        /// <value>Event log data in the format described by *Vcenter.TrustedInfrastructure.Hosts.Hardware.Tpm.EventLog.Info.type*.  This property was added in __vSphere API 8.0.0.1__.  This property is currently required. It may be optional in a future version.</value>
        [DataMember(Name = "data", EmitDefaultValue = false)]
        public byte[] Data { get; set; }

        /// <summary>
        /// Indicates if the event log is truncated.    An event log is truncated when there was insufficient memory to store one or more event entries.  This property was added in __vSphere API 8.0.0.1__.
        /// </summary>
        /// <value>Indicates if the event log is truncated.    An event log is truncated when there was insufficient memory to store one or more event entries.  This property was added in __vSphere API 8.0.0.1__.</value>
        [DataMember(Name = "truncated", IsRequired = true, EmitDefaultValue = true)]
        public bool Truncated { get; set; }

        /// <summary>
        /// The resulting PCR banks from event log replay.  This property was added in __vSphere API 8.0.0.1__.
        /// </summary>
        /// <value>The resulting PCR banks from event log replay.  This property was added in __vSphere API 8.0.0.1__.</value>
        [DataMember(Name = "banks", IsRequired = true, EmitDefaultValue = true)]
        public List<VcenterTrustedInfrastructureHostsHardwareTpmPcrBank> Banks { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VcenterTrustedInfrastructureHostsHardwareTpmEventLogInfo {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Truncated: ").Append(Truncated).Append("\n");
            sb.Append("  Banks: ").Append(Banks).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
