/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// The Vcenter.Vcha.Cluster.Passive.CheckResult schema contains the warnings and errors that will occur during the clone operation.  This schema was added in __vSphere API 6.7.1__.
    /// </summary>
    [DataContract(Name = "Vcenter.Vcha.Cluster.Passive.CheckResult")]
    public partial class VcenterVchaClusterPassiveCheckResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VcenterVchaClusterPassiveCheckResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VcenterVchaClusterPassiveCheckResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VcenterVchaClusterPassiveCheckResult" /> class.
        /// </summary>
        /// <param name="warnings">A list of problems which may require attention, but which are not fatal.  This property was added in __vSphere API 6.7.1__. (required).</param>
        /// <param name="errors">A list of problems which are fatal to the operation and the operation will fail.  This property was added in __vSphere API 6.7.1__. (required).</param>
        public VcenterVchaClusterPassiveCheckResult(List<VapiStdLocalizableMessage> warnings = default, List<VapiStdLocalizableMessage> errors = default)
        {
            // to ensure "warnings" is required (not null)
            if (warnings == null)
            {
                throw new ArgumentNullException("warnings is a required property for VcenterVchaClusterPassiveCheckResult and cannot be null");
            }
            this.Warnings = warnings;
            // to ensure "errors" is required (not null)
            if (errors == null)
            {
                throw new ArgumentNullException("errors is a required property for VcenterVchaClusterPassiveCheckResult and cannot be null");
            }
            this.Errors = errors;
        }

        /// <summary>
        /// A list of problems which may require attention, but which are not fatal.  This property was added in __vSphere API 6.7.1__.
        /// </summary>
        /// <value>A list of problems which may require attention, but which are not fatal.  This property was added in __vSphere API 6.7.1__.</value>
        [DataMember(Name = "warnings", IsRequired = true, EmitDefaultValue = true)]
        public List<VapiStdLocalizableMessage> Warnings { get; set; }

        /// <summary>
        /// A list of problems which are fatal to the operation and the operation will fail.  This property was added in __vSphere API 6.7.1__.
        /// </summary>
        /// <value>A list of problems which are fatal to the operation and the operation will fail.  This property was added in __vSphere API 6.7.1__.</value>
        [DataMember(Name = "errors", IsRequired = true, EmitDefaultValue = true)]
        public List<VapiStdLocalizableMessage> Errors { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VcenterVchaClusterPassiveCheckResult {\n");
            sb.Append("  Warnings: ").Append(Warnings).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
