/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// The Vcenter.NamespaceManagement.Networks.Nsx.Projects.Vpcs.ListResult schema represents the result of the *GET /vcenter/namespace-management/networks/nsx/projects/{project}/vpcs* operation. With *Vcenter.NamespaceManagement.Networks.Nsx.Projects.Vpcs.FilterSpec.compatible* set to true, will only return compatible VPCs that have been pre-created on NSX, filtering out pre-created VPCs from Supervisor or VCF Automation.  This schema was added in __vSphere API 9.0.0.0__.
    /// </summary>
    [DataContract(Name = "Vcenter.NamespaceManagement.Networks.Nsx.Projects.Vpcs.ListResult")]
    public partial class VcenterNamespaceManagementNetworksNsxProjectsVpcsListResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VcenterNamespaceManagementNetworksNsxProjectsVpcsListResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VcenterNamespaceManagementNetworksNsxProjectsVpcsListResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VcenterNamespaceManagementNetworksNsxProjectsVpcsListResult" /> class.
        /// </summary>
        /// <param name="vpcs">List of all VPCs.  This property was added in __vSphere API 9.0.0.0__. (required).</param>
        public VcenterNamespaceManagementNetworksNsxProjectsVpcsListResult(List<VcenterNamespaceManagementNetworksNsxProjectsVpcsInfo> vpcs = default)
        {
            // to ensure "vpcs" is required (not null)
            if (vpcs == null)
            {
                throw new ArgumentNullException("vpcs is a required property for VcenterNamespaceManagementNetworksNsxProjectsVpcsListResult and cannot be null");
            }
            this.Vpcs = vpcs;
        }

        /// <summary>
        /// List of all VPCs.  This property was added in __vSphere API 9.0.0.0__.
        /// </summary>
        /// <value>List of all VPCs.  This property was added in __vSphere API 9.0.0.0__.</value>
        [DataMember(Name = "vpcs", IsRequired = true, EmitDefaultValue = true)]
        public List<VcenterNamespaceManagementNetworksNsxProjectsVpcsInfo> Vpcs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VcenterNamespaceManagementNetworksNsxProjectsVpcsListResult {\n");
            sb.Append("  Vpcs: ").Append(Vpcs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
