/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// Guest customization settings to customize a Linux guest operating system with raw cloud-init data.    The Vcenter.Guest.CloudinitConfiguration schema contains settings that configure a Linux machine with raw cloud-init data. See https://cloudinit.readthedocs.io/en/latest about cloud-init.  This schema was added in __vSphere API 7.0.3.0__.
    /// </summary>
    [DataContract(Name = "Vcenter.Guest.CloudinitConfiguration")]
    public partial class VcenterGuestCloudinitConfiguration : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VcenterGuestCloudinitConfiguration" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VcenterGuestCloudinitConfiguration() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VcenterGuestCloudinitConfiguration" /> class.
        /// </summary>
        /// <param name="metadata">Metadata includes the network, instance id and hostname that cloud-init processes to configure the virtual machine. It is in json or yaml format. The max size of the metadata is 524288 bytes. See https://cloudinit.readthedocs.io/en/latest/topics/datasources/ovf.html about supported meta data formats.  This property was added in __vSphere API 7.0.3.0__. (required).</param>
        /// <param name="userdata">Userdata is the user customized content that cloud-init processes to configure the virtual machine. See https://cloudinit.readthedocs.io/en/latest/topics/format.html about user data formats. See https://cloudinit.readthedocs.io/en/latest/topics/modules.html# about user data modules. The max size of the userdata is 524288 bytes.  This property was added in __vSphere API 7.0.3.0__.  If missing or &#x60;null&#x60;, no cloud-init user data will be used as part of the cloud-init configuration..</param>
        public VcenterGuestCloudinitConfiguration(string metadata = default, string userdata = default)
        {
            // to ensure "metadata" is required (not null)
            if (metadata == null)
            {
                throw new ArgumentNullException("metadata is a required property for VcenterGuestCloudinitConfiguration and cannot be null");
            }
            this.Metadata = metadata;
            this.Userdata = userdata;
        }

        /// <summary>
        /// Metadata includes the network, instance id and hostname that cloud-init processes to configure the virtual machine. It is in json or yaml format. The max size of the metadata is 524288 bytes. See https://cloudinit.readthedocs.io/en/latest/topics/datasources/ovf.html about supported meta data formats.  This property was added in __vSphere API 7.0.3.0__.
        /// </summary>
        /// <value>Metadata includes the network, instance id and hostname that cloud-init processes to configure the virtual machine. It is in json or yaml format. The max size of the metadata is 524288 bytes. See https://cloudinit.readthedocs.io/en/latest/topics/datasources/ovf.html about supported meta data formats.  This property was added in __vSphere API 7.0.3.0__.</value>
        [DataMember(Name = "metadata", IsRequired = true, EmitDefaultValue = true)]
        public string Metadata { get; set; }

        /// <summary>
        /// Userdata is the user customized content that cloud-init processes to configure the virtual machine. See https://cloudinit.readthedocs.io/en/latest/topics/format.html about user data formats. See https://cloudinit.readthedocs.io/en/latest/topics/modules.html# about user data modules. The max size of the userdata is 524288 bytes.  This property was added in __vSphere API 7.0.3.0__.  If missing or &#x60;null&#x60;, no cloud-init user data will be used as part of the cloud-init configuration.
        /// </summary>
        /// <value>Userdata is the user customized content that cloud-init processes to configure the virtual machine. See https://cloudinit.readthedocs.io/en/latest/topics/format.html about user data formats. See https://cloudinit.readthedocs.io/en/latest/topics/modules.html# about user data modules. The max size of the userdata is 524288 bytes.  This property was added in __vSphere API 7.0.3.0__.  If missing or &#x60;null&#x60;, no cloud-init user data will be used as part of the cloud-init configuration.</value>
        [DataMember(Name = "userdata", EmitDefaultValue = false)]
        public string Userdata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VcenterGuestCloudinitConfiguration {\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  Userdata: ").Append(Userdata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
