/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// VcenterGuestCustomizationSpecsImportSpecificationRequest
    /// </summary>
    [DataContract(Name = "Vcenter_Guest_CustomizationSpecs_importSpecification_request")]
    public partial class VcenterGuestCustomizationSpecsImportSpecificationRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VcenterGuestCustomizationSpecsImportSpecificationRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VcenterGuestCustomizationSpecsImportSpecificationRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VcenterGuestCustomizationSpecsImportSpecificationRequest" /> class.
        /// </summary>
        /// <param name="customizationSpec">content to be converted to the spec. (required).</param>
        public VcenterGuestCustomizationSpecsImportSpecificationRequest(string customizationSpec = default)
        {
            // to ensure "customizationSpec" is required (not null)
            if (customizationSpec == null)
            {
                throw new ArgumentNullException("customizationSpec is a required property for VcenterGuestCustomizationSpecsImportSpecificationRequest and cannot be null");
            }
            this.CustomizationSpec = customizationSpec;
        }

        /// <summary>
        /// content to be converted to the spec.
        /// </summary>
        /// <value>content to be converted to the spec.</value>
        [DataMember(Name = "customization_spec", IsRequired = true, EmitDefaultValue = true)]
        public string CustomizationSpec { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VcenterGuestCustomizationSpecsImportSpecificationRequest {\n");
            sb.Append("  CustomizationSpec: ").Append(CustomizationSpec).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
