/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// The Vcenter.Vcha.Cluster.IpInfo schema contains properties related to an ip.  This schema was added in __vSphere API 6.7.1__.
    /// </summary>
    [DataContract(Name = "Vcenter.Vcha.Cluster.IpInfo")]
    public partial class VcenterVchaClusterIpInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VcenterVchaClusterIpInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VcenterVchaClusterIpInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VcenterVchaClusterIpInfo" /> class.
        /// </summary>
        /// <param name="ipFamily">Family of the ip.  Possible values:   - &#x60;IPV4&#x60;: IPV4 address family.   - &#x60;IPV6&#x60;: IPV6 address family.   For more information see: *Vcenter.Vcha.Cluster.IpFamily*.  This property was added in __vSphere API 6.7.1__. (required).</param>
        /// <param name="ipv4">If the type of the ip family is IPV4, then this will point to IPv4 address specification.  This property was added in __vSphere API 6.7.1__.  This property is optional and it is only relevant when the value of ip_family is *Vcenter.Vcha.Cluster.IpFamily.IP_v4*..</param>
        /// <param name="ipv6">If the type of the ip family is IPV6, then this will point to IPv6 address specification.  This property was added in __vSphere API 6.7.1__.  This property is optional and it is only relevant when the value of ip_family is *Vcenter.Vcha.Cluster.IpFamily.IP_v6*..</param>
        /// <param name="gatewayIp">Gateway IP address.  This property was added in __vSphere API 6.7.1__.  If missing or &#x60;null&#x60;, no gateway is specified..</param>
        public VcenterVchaClusterIpInfo(string ipFamily = default, VcenterVchaClusterIpv4Info ipv4 = default, VcenterVchaClusterIpv6Info ipv6 = default, string gatewayIp = default)
        {
            // to ensure "ipFamily" is required (not null)
            if (ipFamily == null)
            {
                throw new ArgumentNullException("ipFamily is a required property for VcenterVchaClusterIpInfo and cannot be null");
            }
            this.IpFamily = ipFamily;
            this.Ipv4 = ipv4;
            this.Ipv6 = ipv6;
            this.GatewayIp = gatewayIp;
        }

        /// <summary>
        /// Family of the ip.  Possible values:   - &#x60;IPV4&#x60;: IPV4 address family.   - &#x60;IPV6&#x60;: IPV6 address family.   For more information see: *Vcenter.Vcha.Cluster.IpFamily*.  This property was added in __vSphere API 6.7.1__.
        /// </summary>
        /// <value>Family of the ip.  Possible values:   - &#x60;IPV4&#x60;: IPV4 address family.   - &#x60;IPV6&#x60;: IPV6 address family.   For more information see: *Vcenter.Vcha.Cluster.IpFamily*.  This property was added in __vSphere API 6.7.1__.</value>
        [DataMember(Name = "ip_family", IsRequired = true, EmitDefaultValue = true)]
        public string IpFamily { get; set; }

        /// <summary>
        /// If the type of the ip family is IPV4, then this will point to IPv4 address specification.  This property was added in __vSphere API 6.7.1__.  This property is optional and it is only relevant when the value of ip_family is *Vcenter.Vcha.Cluster.IpFamily.IP_v4*.
        /// </summary>
        /// <value>If the type of the ip family is IPV4, then this will point to IPv4 address specification.  This property was added in __vSphere API 6.7.1__.  This property is optional and it is only relevant when the value of ip_family is *Vcenter.Vcha.Cluster.IpFamily.IP_v4*.</value>
        [DataMember(Name = "ipv4", EmitDefaultValue = false)]
        public VcenterVchaClusterIpv4Info Ipv4 { get; set; }

        /// <summary>
        /// If the type of the ip family is IPV6, then this will point to IPv6 address specification.  This property was added in __vSphere API 6.7.1__.  This property is optional and it is only relevant when the value of ip_family is *Vcenter.Vcha.Cluster.IpFamily.IP_v6*.
        /// </summary>
        /// <value>If the type of the ip family is IPV6, then this will point to IPv6 address specification.  This property was added in __vSphere API 6.7.1__.  This property is optional and it is only relevant when the value of ip_family is *Vcenter.Vcha.Cluster.IpFamily.IP_v6*.</value>
        [DataMember(Name = "ipv6", EmitDefaultValue = false)]
        public VcenterVchaClusterIpv6Info Ipv6 { get; set; }

        /// <summary>
        /// Gateway IP address.  This property was added in __vSphere API 6.7.1__.  If missing or &#x60;null&#x60;, no gateway is specified.
        /// </summary>
        /// <value>Gateway IP address.  This property was added in __vSphere API 6.7.1__.  If missing or &#x60;null&#x60;, no gateway is specified.</value>
        [DataMember(Name = "gateway_ip", EmitDefaultValue = false)]
        public string GatewayIp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VcenterVchaClusterIpInfo {\n");
            sb.Append("  IpFamily: ").Append(IpFamily).Append("\n");
            sb.Append("  Ipv4: ").Append(Ipv4).Append("\n");
            sb.Append("  Ipv6: ").Append(Ipv6).Append("\n");
            sb.Append("  GatewayIp: ").Append(GatewayIp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
