/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// The Vcenter.NamespaceManagement.Supervisors.Certificates.KeySizes.UpdateSpec schema contains updates to options declared for the Supervisor.  This schema was added in __vSphere API 9.1.0.0__.
    /// </summary>
    [DataContract(Name = "Vcenter.NamespaceManagement.Supervisors.Certificates.KeySizes.UpdateSpec")]
    public partial class VcenterNamespaceManagementSupervisorsCertificatesKeySizesUpdateSpec : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VcenterNamespaceManagementSupervisorsCertificatesKeySizesUpdateSpec" /> class.
        /// </summary>
        /// <param name="internalCertsKeySize">Supervisor internal certificates key size. The Supervisor will update the size of the signing key for internal certificates.  This property was added in __vSphere API 9.1.0.0__.  If missing or &#x60;null&#x60; then no update will be made..</param>
        public VcenterNamespaceManagementSupervisorsCertificatesKeySizesUpdateSpec(string internalCertsKeySize = default)
        {
            this.InternalCertsKeySize = internalCertsKeySize;
        }

        /// <summary>
        /// Supervisor internal certificates key size. The Supervisor will update the size of the signing key for internal certificates.  This property was added in __vSphere API 9.1.0.0__.  If missing or &#x60;null&#x60; then no update will be made.
        /// </summary>
        /// <value>Supervisor internal certificates key size. The Supervisor will update the size of the signing key for internal certificates.  This property was added in __vSphere API 9.1.0.0__.  If missing or &#x60;null&#x60; then no update will be made.</value>
        [DataMember(Name = "internal_certs_key_size", EmitDefaultValue = false)]
        public string InternalCertsKeySize { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VcenterNamespaceManagementSupervisorsCertificatesKeySizesUpdateSpec {\n");
            sb.Append("  InternalCertsKeySize: ").Append(InternalCertsKeySize).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
