/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// Vcenter.NamespaceManagement.Supervisors.Networks.Management.NetworkBackingEnum enumerates types of network backings supported by the Supervisor for the management network.  Possible values:   - &#x60;NETWORK&#x60;: This constant is deprecated as of __vSphere API 8.0.3.0__. Use *Vcenter.NamespaceManagement.Supervisors.Networks.Management.NetworkBackingEnum.NETWORK_SEGMENT* instead.  Indicates a virtual infrastructure management Network. It may include items like opaque networks or Distributed Virtual Port Groups.   - &#x60;NETWORK_SEGMENT&#x60;: Indicates a virtual infrastructure management Network Segment. The Network Segment can be backed by either a single Port Group or a set of Port Groups in the same layer 2 broadcast domain. From this set of one or more Port Groups, at least one Port Group must be available on each vSphere Zone and its associated vSphere clusters that Supervisor control plane is configured to be enabled on.  This constant was added in __vSphere API 8.0.3.0__.   This enumeration was added in __vSphere API 8.0.0.1__.
    /// </summary>
    /// <value>Vcenter.NamespaceManagement.Supervisors.Networks.Management.NetworkBackingEnum enumerates types of network backings supported by the Supervisor for the management network.  Possible values:   - &#x60;NETWORK&#x60;: This constant is deprecated as of __vSphere API 8.0.3.0__. Use *Vcenter.NamespaceManagement.Supervisors.Networks.Management.NetworkBackingEnum.NETWORK_SEGMENT* instead.  Indicates a virtual infrastructure management Network. It may include items like opaque networks or Distributed Virtual Port Groups.   - &#x60;NETWORK_SEGMENT&#x60;: Indicates a virtual infrastructure management Network Segment. The Network Segment can be backed by either a single Port Group or a set of Port Groups in the same layer 2 broadcast domain. From this set of one or more Port Groups, at least one Port Group must be available on each vSphere Zone and its associated vSphere clusters that Supervisor control plane is configured to be enabled on.  This constant was added in __vSphere API 8.0.3.0__.   This enumeration was added in __vSphere API 8.0.0.1__.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VcenterNamespaceManagementSupervisorsNetworksManagementNetworkBackingEnum
    {
        /// <summary>
        /// Enum NETWORK for value: NETWORK
        /// </summary>
        [EnumMember(Value = "NETWORK")]
        NETWORK = 1,

        /// <summary>
        /// Enum NETWORKSEGMENT for value: NETWORK_SEGMENT
        /// </summary>
        [EnumMember(Value = "NETWORK_SEGMENT")]
        NETWORKSEGMENT = 2
    }

}
