/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// The Vcenter.Authorization.Permissions.FilterSpec schema contains properties based on which authorization permissions can be filtered. Any permission matching all of the conditions is returned.  This schema was added in __vSphere API 9.0.0.0__.
    /// </summary>
    [DataContract(Name = "Vcenter.Authorization.Permissions.FilterSpec")]
    public partial class VcenterAuthorizationPermissionsFilterSpec : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VcenterAuthorizationPermissionsFilterSpec" /> class.
        /// </summary>
        /// <param name="objects">Objects which permissions are assigned on.  This property was added in __vSphere API 9.0.0.0__.  If missing or &#x60;null&#x60; all permissions match..</param>
        /// <param name="principals">Principals who permissions are assigned for.  This property was added in __vSphere API 9.0.0.0__.  If missing or &#x60;null&#x60; all permissions match..</param>
        /// <param name="roles">The roles granted by the permissions.  This property was added in __vSphere API 9.0.0.0__.  If missing or &#x60;null&#x60; all permissions match.  When clients pass a value of this schema as a parameter, the property must contain identifiers for the resource type: &#x60;com.vmware.vcenter.authorization.Role&#x60;. When operations return a value of this schema as a response, the property will contain identifiers for the resource type: &#x60;com.vmware.vcenter.authorization.Role&#x60;..</param>
        /// <param name="isPropagating">Whether the permission is propagating.  This property was added in __vSphere API 9.0.0.0__.  If missing or &#x60;null&#x60; all permissions match..</param>
        public VcenterAuthorizationPermissionsFilterSpec(List<VapiStdDynamicID> objects = default, List<VcenterAuthorizationPermissionsPrincipal> principals = default, List<string> roles = default, bool isPropagating = default)
        {
            this.Objects = objects;
            this.Principals = principals;
            this.Roles = roles;
            this.IsPropagating = isPropagating;
        }

        /// <summary>
        /// Objects which permissions are assigned on.  This property was added in __vSphere API 9.0.0.0__.  If missing or &#x60;null&#x60; all permissions match.
        /// </summary>
        /// <value>Objects which permissions are assigned on.  This property was added in __vSphere API 9.0.0.0__.  If missing or &#x60;null&#x60; all permissions match.</value>
        [DataMember(Name = "objects", EmitDefaultValue = false)]
        public List<VapiStdDynamicID> Objects { get; set; }

        /// <summary>
        /// Principals who permissions are assigned for.  This property was added in __vSphere API 9.0.0.0__.  If missing or &#x60;null&#x60; all permissions match.
        /// </summary>
        /// <value>Principals who permissions are assigned for.  This property was added in __vSphere API 9.0.0.0__.  If missing or &#x60;null&#x60; all permissions match.</value>
        [DataMember(Name = "principals", EmitDefaultValue = false)]
        public List<VcenterAuthorizationPermissionsPrincipal> Principals { get; set; }

        /// <summary>
        /// The roles granted by the permissions.  This property was added in __vSphere API 9.0.0.0__.  If missing or &#x60;null&#x60; all permissions match.  When clients pass a value of this schema as a parameter, the property must contain identifiers for the resource type: &#x60;com.vmware.vcenter.authorization.Role&#x60;. When operations return a value of this schema as a response, the property will contain identifiers for the resource type: &#x60;com.vmware.vcenter.authorization.Role&#x60;.
        /// </summary>
        /// <value>The roles granted by the permissions.  This property was added in __vSphere API 9.0.0.0__.  If missing or &#x60;null&#x60; all permissions match.  When clients pass a value of this schema as a parameter, the property must contain identifiers for the resource type: &#x60;com.vmware.vcenter.authorization.Role&#x60;. When operations return a value of this schema as a response, the property will contain identifiers for the resource type: &#x60;com.vmware.vcenter.authorization.Role&#x60;.</value>
        [DataMember(Name = "roles", EmitDefaultValue = false)]
        public List<string> Roles { get; set; }

        /// <summary>
        /// Whether the permission is propagating.  This property was added in __vSphere API 9.0.0.0__.  If missing or &#x60;null&#x60; all permissions match.
        /// </summary>
        /// <value>Whether the permission is propagating.  This property was added in __vSphere API 9.0.0.0__.  If missing or &#x60;null&#x60; all permissions match.</value>
        [DataMember(Name = "is_propagating", EmitDefaultValue = true)]
        public bool IsPropagating { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VcenterAuthorizationPermissionsFilterSpec {\n");
            sb.Append("  Objects: ").Append(Objects).Append("\n");
            sb.Append("  Principals: ").Append(Principals).Append("\n");
            sb.Append("  Roles: ").Append(Roles).Append("\n");
            sb.Append("  IsPropagating: ").Append(IsPropagating).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
