/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    ///   The Vcenter.NamespaceManagement.Networks.IPRange schema is used to express a range of IP addresses. The IP address supported by this structure will depend on the IP version that is being used by Supervisor.   Currently, the Supervisor only supports IPv4.  This schema was added in __vSphere API 8.0.0.1__.
    /// </summary>
    [DataContract(Name = "Vcenter.NamespaceManagement.Networks.IPRange")]
    public partial class VcenterNamespaceManagementNetworksIPRange : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VcenterNamespaceManagementNetworksIPRange" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VcenterNamespaceManagementNetworksIPRange() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VcenterNamespaceManagementNetworksIPRange" /> class.
        /// </summary>
        /// <param name="address">*Vcenter.NamespaceManagement.Networks.IPRange.address* is the starting IP address of the Vcenter.NamespaceManagement.Networks.IPRange.  This property was added in __vSphere API 8.0.0.1__. (required).</param>
        /// <param name="count">  *Vcenter.NamespaceManagement.Networks.IPRange.count* is number of IP addresses in the range.   For example:   A /24 subnet will have a count of 256.   A /24 subnet with a gateway address and a broadcast address will have a count of 254.  This property was added in __vSphere API 8.0.0.1__. (required).</param>
        public VcenterNamespaceManagementNetworksIPRange(string address = default, long count = default)
        {
            // to ensure "address" is required (not null)
            if (address == null)
            {
                throw new ArgumentNullException("address is a required property for VcenterNamespaceManagementNetworksIPRange and cannot be null");
            }
            this.Address = address;
            this.Count = count;
        }

        /// <summary>
        /// *Vcenter.NamespaceManagement.Networks.IPRange.address* is the starting IP address of the Vcenter.NamespaceManagement.Networks.IPRange.  This property was added in __vSphere API 8.0.0.1__.
        /// </summary>
        /// <value>*Vcenter.NamespaceManagement.Networks.IPRange.address* is the starting IP address of the Vcenter.NamespaceManagement.Networks.IPRange.  This property was added in __vSphere API 8.0.0.1__.</value>
        [DataMember(Name = "address", IsRequired = true, EmitDefaultValue = true)]
        public string Address { get; set; }

        /// <summary>
        ///   *Vcenter.NamespaceManagement.Networks.IPRange.count* is number of IP addresses in the range.   For example:   A /24 subnet will have a count of 256.   A /24 subnet with a gateway address and a broadcast address will have a count of 254.  This property was added in __vSphere API 8.0.0.1__.
        /// </summary>
        /// <value>  *Vcenter.NamespaceManagement.Networks.IPRange.count* is number of IP addresses in the range.   For example:   A /24 subnet will have a count of 256.   A /24 subnet with a gateway address and a broadcast address will have a count of 254.  This property was added in __vSphere API 8.0.0.1__.</value>
        [DataMember(Name = "count", IsRequired = true, EmitDefaultValue = true)]
        public long Count { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VcenterNamespaceManagementNetworksIPRange {\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
