/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// The Vcenter.NamespaceManagement.Storage.Profiles.Summary schema contains the information about compatible storage profiles and represents the result of *POST /vcenter/namespace-management/storage/profiles?action&#x3D;check_compatibility* operation.  This schema was added in __vSphere API 8.0.0.1__.
    /// </summary>
    [DataContract(Name = "Vcenter.NamespaceManagement.Storage.Profiles.Summary")]
    public partial class VcenterNamespaceManagementStorageProfilesSummary : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VcenterNamespaceManagementStorageProfilesSummary" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VcenterNamespaceManagementStorageProfilesSummary() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VcenterNamespaceManagementStorageProfilesSummary" /> class.
        /// </summary>
        /// <param name="profile">Identifier of the compatible storage profile. A storage profile is compatible if it results in at least one datastore in each of the specified zones.  This property was added in __vSphere API 8.0.0.1__.  When clients pass a value of this schema as a parameter, the property must be an identifier for the resource type: &#x60;SpsStorageProfile&#x60;. When operations return a value of this schema as a response, the property will be an identifier for the resource type: &#x60;SpsStorageProfile&#x60;. (required).</param>
        /// <param name="profileName">Human-readable identifier of the storage profile.  This property was added in __vSphere API 8.0.0.1__. (required).</param>
        /// <param name="compatible">Compatibility of this storage profile with the specified vSphere Zones.  This property was added in __vSphere API 8.0.0.1__. (required).</param>
        /// <param name="items">The list of Vcenter.NamespaceManagement.Storage.Profiles.Item which correspond to the storage profile.  This property was added in __vSphere API 8.0.0.1__. (required).</param>
        /// <param name="incompatibilityReasons">The reason for incompatibility. If empty, this profile is compatible with the given vSphere Zones specified in the *Vcenter.NamespaceManagement.Storage.Profiles.FilterSpec*.  This property was added in __vSphere API 8.0.0.1__. (required).</param>
        public VcenterNamespaceManagementStorageProfilesSummary(string profile = default, string profileName = default, bool compatible = default, List<VcenterNamespaceManagementStorageProfilesItem> items = default, List<VapiStdLocalizableMessage> incompatibilityReasons = default)
        {
            // to ensure "profile" is required (not null)
            if (profile == null)
            {
                throw new ArgumentNullException("profile is a required property for VcenterNamespaceManagementStorageProfilesSummary and cannot be null");
            }
            this.Profile = profile;
            // to ensure "profileName" is required (not null)
            if (profileName == null)
            {
                throw new ArgumentNullException("profileName is a required property for VcenterNamespaceManagementStorageProfilesSummary and cannot be null");
            }
            this.ProfileName = profileName;
            this.Compatible = compatible;
            // to ensure "items" is required (not null)
            if (items == null)
            {
                throw new ArgumentNullException("items is a required property for VcenterNamespaceManagementStorageProfilesSummary and cannot be null");
            }
            this.Items = items;
            // to ensure "incompatibilityReasons" is required (not null)
            if (incompatibilityReasons == null)
            {
                throw new ArgumentNullException("incompatibilityReasons is a required property for VcenterNamespaceManagementStorageProfilesSummary and cannot be null");
            }
            this.IncompatibilityReasons = incompatibilityReasons;
        }

        /// <summary>
        /// Identifier of the compatible storage profile. A storage profile is compatible if it results in at least one datastore in each of the specified zones.  This property was added in __vSphere API 8.0.0.1__.  When clients pass a value of this schema as a parameter, the property must be an identifier for the resource type: &#x60;SpsStorageProfile&#x60;. When operations return a value of this schema as a response, the property will be an identifier for the resource type: &#x60;SpsStorageProfile&#x60;.
        /// </summary>
        /// <value>Identifier of the compatible storage profile. A storage profile is compatible if it results in at least one datastore in each of the specified zones.  This property was added in __vSphere API 8.0.0.1__.  When clients pass a value of this schema as a parameter, the property must be an identifier for the resource type: &#x60;SpsStorageProfile&#x60;. When operations return a value of this schema as a response, the property will be an identifier for the resource type: &#x60;SpsStorageProfile&#x60;.</value>
        [DataMember(Name = "profile", IsRequired = true, EmitDefaultValue = true)]
        public string Profile { get; set; }

        /// <summary>
        /// Human-readable identifier of the storage profile.  This property was added in __vSphere API 8.0.0.1__.
        /// </summary>
        /// <value>Human-readable identifier of the storage profile.  This property was added in __vSphere API 8.0.0.1__.</value>
        [DataMember(Name = "profile_name", IsRequired = true, EmitDefaultValue = true)]
        public string ProfileName { get; set; }

        /// <summary>
        /// Compatibility of this storage profile with the specified vSphere Zones.  This property was added in __vSphere API 8.0.0.1__.
        /// </summary>
        /// <value>Compatibility of this storage profile with the specified vSphere Zones.  This property was added in __vSphere API 8.0.0.1__.</value>
        [DataMember(Name = "compatible", IsRequired = true, EmitDefaultValue = true)]
        public bool Compatible { get; set; }

        /// <summary>
        /// The list of Vcenter.NamespaceManagement.Storage.Profiles.Item which correspond to the storage profile.  This property was added in __vSphere API 8.0.0.1__.
        /// </summary>
        /// <value>The list of Vcenter.NamespaceManagement.Storage.Profiles.Item which correspond to the storage profile.  This property was added in __vSphere API 8.0.0.1__.</value>
        [DataMember(Name = "items", IsRequired = true, EmitDefaultValue = true)]
        public List<VcenterNamespaceManagementStorageProfilesItem> Items { get; set; }

        /// <summary>
        /// The reason for incompatibility. If empty, this profile is compatible with the given vSphere Zones specified in the *Vcenter.NamespaceManagement.Storage.Profiles.FilterSpec*.  This property was added in __vSphere API 8.0.0.1__.
        /// </summary>
        /// <value>The reason for incompatibility. If empty, this profile is compatible with the given vSphere Zones specified in the *Vcenter.NamespaceManagement.Storage.Profiles.FilterSpec*.  This property was added in __vSphere API 8.0.0.1__.</value>
        [DataMember(Name = "incompatibility_reasons", IsRequired = true, EmitDefaultValue = true)]
        public List<VapiStdLocalizableMessage> IncompatibilityReasons { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VcenterNamespaceManagementStorageProfilesSummary {\n");
            sb.Append("  Profile: ").Append(Profile).Append("\n");
            sb.Append("  ProfileName: ").Append(ProfileName).Append("\n");
            sb.Append("  Compatible: ").Append(Compatible).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("  IncompatibilityReasons: ").Append(IncompatibilityReasons).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
