/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// The Vcenter.VmTemplate.LibraryItems.EthernetInfo.NetworkBackingType enumerated type defines valid network backing types for a virtual Ethernet adapter.  Possible values:   - &#x60;STANDARD_PORTGROUP&#x60;: vSphere standard portgroup network backing.   - &#x60;HOST_DEVICE&#x60;: Legacy host device network backing. Imported VMs may have virtual Ethernet adapters with this type of backing, but this type of backing cannot be used to create or to update a virtual Ethernet adapter.   - &#x60;DISTRIBUTED_PORTGROUP&#x60;: Distributed virtual switch backing.   - &#x60;OPAQUE_NETWORK&#x60;: Opaque network backing.   This enumeration was added in __vSphere API 6.8__.
    /// </summary>
    /// <value>The Vcenter.VmTemplate.LibraryItems.EthernetInfo.NetworkBackingType enumerated type defines valid network backing types for a virtual Ethernet adapter.  Possible values:   - &#x60;STANDARD_PORTGROUP&#x60;: vSphere standard portgroup network backing.   - &#x60;HOST_DEVICE&#x60;: Legacy host device network backing. Imported VMs may have virtual Ethernet adapters with this type of backing, but this type of backing cannot be used to create or to update a virtual Ethernet adapter.   - &#x60;DISTRIBUTED_PORTGROUP&#x60;: Distributed virtual switch backing.   - &#x60;OPAQUE_NETWORK&#x60;: Opaque network backing.   This enumeration was added in __vSphere API 6.8__.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VcenterVmTemplateLibraryItemsEthernetInfoNetworkBackingType
    {
        /// <summary>
        /// Enum STANDARDPORTGROUP for value: STANDARD_PORTGROUP
        /// </summary>
        [EnumMember(Value = "STANDARD_PORTGROUP")]
        STANDARDPORTGROUP = 1,

        /// <summary>
        /// Enum HOSTDEVICE for value: HOST_DEVICE
        /// </summary>
        [EnumMember(Value = "HOST_DEVICE")]
        HOSTDEVICE = 2,

        /// <summary>
        /// Enum DISTRIBUTEDPORTGROUP for value: DISTRIBUTED_PORTGROUP
        /// </summary>
        [EnumMember(Value = "DISTRIBUTED_PORTGROUP")]
        DISTRIBUTEDPORTGROUP = 3,

        /// <summary>
        /// Enum OPAQUENETWORK for value: OPAQUE_NETWORK
        /// </summary>
        [EnumMember(Value = "OPAQUE_NETWORK")]
        OPAQUENETWORK = 4
    }

}
