/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// The Vcenter.NamespaceManagement.Supervisors.Conditions.Condition schema defines an observation of the configuration state of a Supervisor.  This schema was added in __vSphere API 8.0.0.1__.
    /// </summary>
    [DataContract(Name = "Vcenter.NamespaceManagement.Supervisors.Conditions.Condition")]
    public partial class VcenterNamespaceManagementSupervisorsConditionsCondition : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VcenterNamespaceManagementSupervisorsConditionsCondition" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VcenterNamespaceManagementSupervisorsConditionsCondition() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VcenterNamespaceManagementSupervisorsConditionsCondition" /> class.
        /// </summary>
        /// <param name="type">The type of the condition is a CamelCase, machine readable identifier, indicating the configuration stage. InfrastructureInitialized, ControlPlaneVMsDeployed and ControlPlaneVMsConfigured are examples of such identifiers.  This property was added in __vSphere API 8.0.0.1__. (required).</param>
        /// <param name="description">Description of the condition type in a human readable format.  This property was added in __vSphere API 8.0.0.1__. (required).</param>
        /// <param name="status">The status of the condition.  Possible values:   - &#x60;TRUE&#x60;: Indicates that the condition has reached the desired state.   - &#x60;FALSE&#x60;: Indicates that the condition has not reached the desired state.   - &#x60;UNKNOWN&#x60;: Indicates that the status of the condition can not be determined.   For more information see: *Vcenter.NamespaceManagement.Supervisors.Conditions.Condition.Status*.  This property was added in __vSphere API 8.0.0.1__. (required).</param>
        /// <param name="lastTransitionTime">Last time the condition transitioned from one state to another. A transition happens when the value of status or severity field changes.  This property was added in __vSphere API 8.0.0.1__.  if missing or &#x60;null&#x60;, there are no ongoing operations related to bringing the condition to the desired state..</param>
        /// <param name="reason">A brief CamelCase message indicating details about the reason for the last transition. FailedWithSystemError, ManagementDNSServersMissing and WaitForNodeUpgrade are examples of such messages.  This property was added in __vSphere API 8.0.0.1__. (required).</param>
        /// <param name="severity">Provides an explicit classification of the reason identifier. Can be set when the value of status is not TRUE.  Possible values:   - &#x60;INFO&#x60;: Informational message.   - &#x60;WARNING&#x60;: Warning message.   - &#x60;ERROR&#x60;: Error message.   For more information see: *Vcenter.NamespaceManagement.Supervisors.Conditions.Severity*.  This property was added in __vSphere API 8.0.0.1__. (required).</param>
        /// <param name="messages">A list of human-readable messages that provide additional details about the last transition.  This property was added in __vSphere API 8.0.0.1__. (required).</param>
        public VcenterNamespaceManagementSupervisorsConditionsCondition(string type = default, VapiStdLocalizableMessage description = default, string status = default, DateTime lastTransitionTime = default, string reason = default, string severity = default, List<VcenterNamespaceManagementSupervisorsConditionsMessage> messages = default)
        {
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for VcenterNamespaceManagementSupervisorsConditionsCondition and cannot be null");
            }
            this.Type = type;
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new ArgumentNullException("description is a required property for VcenterNamespaceManagementSupervisorsConditionsCondition and cannot be null");
            }
            this.Description = description;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for VcenterNamespaceManagementSupervisorsConditionsCondition and cannot be null");
            }
            this.Status = status;
            // to ensure "reason" is required (not null)
            if (reason == null)
            {
                throw new ArgumentNullException("reason is a required property for VcenterNamespaceManagementSupervisorsConditionsCondition and cannot be null");
            }
            this.Reason = reason;
            // to ensure "severity" is required (not null)
            if (severity == null)
            {
                throw new ArgumentNullException("severity is a required property for VcenterNamespaceManagementSupervisorsConditionsCondition and cannot be null");
            }
            this.Severity = severity;
            // to ensure "messages" is required (not null)
            if (messages == null)
            {
                throw new ArgumentNullException("messages is a required property for VcenterNamespaceManagementSupervisorsConditionsCondition and cannot be null");
            }
            this.Messages = messages;
            this.LastTransitionTime = lastTransitionTime;
        }

        /// <summary>
        /// The type of the condition is a CamelCase, machine readable identifier, indicating the configuration stage. InfrastructureInitialized, ControlPlaneVMsDeployed and ControlPlaneVMsConfigured are examples of such identifiers.  This property was added in __vSphere API 8.0.0.1__.
        /// </summary>
        /// <value>The type of the condition is a CamelCase, machine readable identifier, indicating the configuration stage. InfrastructureInitialized, ControlPlaneVMsDeployed and ControlPlaneVMsConfigured are examples of such identifiers.  This property was added in __vSphere API 8.0.0.1__.</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Description of the condition type in a human readable format.  This property was added in __vSphere API 8.0.0.1__.
        /// </summary>
        /// <value>Description of the condition type in a human readable format.  This property was added in __vSphere API 8.0.0.1__.</value>
        [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = true)]
        public VapiStdLocalizableMessage Description { get; set; }

        /// <summary>
        /// The status of the condition.  Possible values:   - &#x60;TRUE&#x60;: Indicates that the condition has reached the desired state.   - &#x60;FALSE&#x60;: Indicates that the condition has not reached the desired state.   - &#x60;UNKNOWN&#x60;: Indicates that the status of the condition can not be determined.   For more information see: *Vcenter.NamespaceManagement.Supervisors.Conditions.Condition.Status*.  This property was added in __vSphere API 8.0.0.1__.
        /// </summary>
        /// <value>The status of the condition.  Possible values:   - &#x60;TRUE&#x60;: Indicates that the condition has reached the desired state.   - &#x60;FALSE&#x60;: Indicates that the condition has not reached the desired state.   - &#x60;UNKNOWN&#x60;: Indicates that the status of the condition can not be determined.   For more information see: *Vcenter.NamespaceManagement.Supervisors.Conditions.Condition.Status*.  This property was added in __vSphere API 8.0.0.1__.</value>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// Last time the condition transitioned from one state to another. A transition happens when the value of status or severity field changes.  This property was added in __vSphere API 8.0.0.1__.  if missing or &#x60;null&#x60;, there are no ongoing operations related to bringing the condition to the desired state.
        /// </summary>
        /// <value>Last time the condition transitioned from one state to another. A transition happens when the value of status or severity field changes.  This property was added in __vSphere API 8.0.0.1__.  if missing or &#x60;null&#x60;, there are no ongoing operations related to bringing the condition to the desired state.</value>
        [DataMember(Name = "last_transition_time", EmitDefaultValue = false)]
        public DateTime LastTransitionTime { get; set; }

        /// <summary>
        /// A brief CamelCase message indicating details about the reason for the last transition. FailedWithSystemError, ManagementDNSServersMissing and WaitForNodeUpgrade are examples of such messages.  This property was added in __vSphere API 8.0.0.1__.
        /// </summary>
        /// <value>A brief CamelCase message indicating details about the reason for the last transition. FailedWithSystemError, ManagementDNSServersMissing and WaitForNodeUpgrade are examples of such messages.  This property was added in __vSphere API 8.0.0.1__.</value>
        [DataMember(Name = "reason", IsRequired = true, EmitDefaultValue = true)]
        public string Reason { get; set; }

        /// <summary>
        /// Provides an explicit classification of the reason identifier. Can be set when the value of status is not TRUE.  Possible values:   - &#x60;INFO&#x60;: Informational message.   - &#x60;WARNING&#x60;: Warning message.   - &#x60;ERROR&#x60;: Error message.   For more information see: *Vcenter.NamespaceManagement.Supervisors.Conditions.Severity*.  This property was added in __vSphere API 8.0.0.1__.
        /// </summary>
        /// <value>Provides an explicit classification of the reason identifier. Can be set when the value of status is not TRUE.  Possible values:   - &#x60;INFO&#x60;: Informational message.   - &#x60;WARNING&#x60;: Warning message.   - &#x60;ERROR&#x60;: Error message.   For more information see: *Vcenter.NamespaceManagement.Supervisors.Conditions.Severity*.  This property was added in __vSphere API 8.0.0.1__.</value>
        [DataMember(Name = "severity", IsRequired = true, EmitDefaultValue = true)]
        public string Severity { get; set; }

        /// <summary>
        /// A list of human-readable messages that provide additional details about the last transition.  This property was added in __vSphere API 8.0.0.1__.
        /// </summary>
        /// <value>A list of human-readable messages that provide additional details about the last transition.  This property was added in __vSphere API 8.0.0.1__.</value>
        [DataMember(Name = "messages", IsRequired = true, EmitDefaultValue = true)]
        public List<VcenterNamespaceManagementSupervisorsConditionsMessage> Messages { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VcenterNamespaceManagementSupervisorsConditionsCondition {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  LastTransitionTime: ").Append(LastTransitionTime).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  Severity: ").Append(Severity).Append("\n");
            sb.Append("  Messages: ").Append(Messages).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
