/*
 * vSphere Automation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.Automation.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.Automation.OpenApi.Model
{
    /// <summary>
    /// The Vcenter.Datastore.Type enumerated type defines the supported types of vCenter datastores.  Possible values:   - &#x60;VMFS&#x60;: VMware File System (ESX Server only).   - &#x60;NFS&#x60;: Network file system v3 (linux &amp; esx servers only).   - &#x60;NFS41&#x60;: Network file system v4.1 (linux &amp; esx servers only).   - &#x60;CIFS&#x60;: Common Internet File System.   - &#x60;VSAN&#x60;: Virtual SAN (ESX Server only).   - &#x60;VFFS&#x60;: Flash Read Cache (ESX Server only).   - &#x60;VVOL&#x60;: vSphere Virtual Volume (ESX Server only). 
    /// </summary>
    /// <value>The Vcenter.Datastore.Type enumerated type defines the supported types of vCenter datastores.  Possible values:   - &#x60;VMFS&#x60;: VMware File System (ESX Server only).   - &#x60;NFS&#x60;: Network file system v3 (linux &amp; esx servers only).   - &#x60;NFS41&#x60;: Network file system v4.1 (linux &amp; esx servers only).   - &#x60;CIFS&#x60;: Common Internet File System.   - &#x60;VSAN&#x60;: Virtual SAN (ESX Server only).   - &#x60;VFFS&#x60;: Flash Read Cache (ESX Server only).   - &#x60;VVOL&#x60;: vSphere Virtual Volume (ESX Server only). </value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VcenterDatastoreType
    {
        /// <summary>
        /// Enum VMFS for value: VMFS
        /// </summary>
        [EnumMember(Value = "VMFS")]
        VMFS = 1,

        /// <summary>
        /// Enum NFS for value: NFS
        /// </summary>
        [EnumMember(Value = "NFS")]
        NFS = 2,

        /// <summary>
        /// Enum NFS41 for value: NFS41
        /// </summary>
        [EnumMember(Value = "NFS41")]
        NFS41 = 3,

        /// <summary>
        /// Enum CIFS for value: CIFS
        /// </summary>
        [EnumMember(Value = "CIFS")]
        CIFS = 4,

        /// <summary>
        /// Enum VSAN for value: VSAN
        /// </summary>
        [EnumMember(Value = "VSAN")]
        VSAN = 5,

        /// <summary>
        /// Enum VFFS for value: VFFS
        /// </summary>
        [EnumMember(Value = "VFFS")]
        VFFS = 6,

        /// <summary>
        /// Enum VVOL for value: VVOL
        /// </summary>
        [EnumMember(Value = "VVOL")]
        VVOL = 7
    }

}
