/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// AnswerFileStatusResult
    /// </summary>
    [DataContract(Name = "AnswerFileStatusResult")]
    public partial class AnswerFileStatusResult : DataObject, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AnswerFileStatusResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AnswerFileStatusResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AnswerFileStatusResult" /> class.
        /// </summary>
        /// <param name="checkedTime">Time that the answer file status was determined.  (required).</param>
        /// <param name="host">Host associated with the answer file.  Refers instance of *HostSystem*.  (required).</param>
        /// <param name="status">Status of the answer file.  See *HostProfileManagerAnswerFileStatus_enum* for valid values.  (required).</param>
        /// <param name="error">If &lt;code&gt;status&lt;/code&gt; is &lt;code&gt;invalid&lt;/code&gt;, this property contains a list of status error objects. .</param>
        /// <param name="typeName">The type discriminator. Refers to the name of a valid data object type.  (required) (default to &quot;AnswerFileStatusResult&quot;).</param>
        public AnswerFileStatusResult(DateTime checkedTime = default, ManagedObjectReference host = default, string status = default, List<AnswerFileStatusError> error = default, string typeName = @"AnswerFileStatusResult") : base()
        {
            this.CheckedTime = checkedTime;
            // to ensure "host" is required (not null)
            if (host == null)
            {
                throw new ArgumentNullException("host is a required property for AnswerFileStatusResult and cannot be null");
            }
            this.Host = host;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for AnswerFileStatusResult and cannot be null");
            }
            this.Status = status;
            this.Error = error;
        }

        /// <summary>
        /// Time that the answer file status was determined. 
        /// </summary>
        /// <value>Time that the answer file status was determined. </value>
        [DataMember(Name = "checkedTime", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CheckedTime { get; set; }

        /// <summary>
        /// Host associated with the answer file.  Refers instance of *HostSystem*. 
        /// </summary>
        /// <value>Host associated with the answer file.  Refers instance of *HostSystem*. </value>
        [DataMember(Name = "host", IsRequired = true, EmitDefaultValue = true)]
        public ManagedObjectReference Host { get; set; }

        /// <summary>
        /// Status of the answer file.  See *HostProfileManagerAnswerFileStatus_enum* for valid values. 
        /// </summary>
        /// <value>Status of the answer file.  See *HostProfileManagerAnswerFileStatus_enum* for valid values. </value>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// If &lt;code&gt;status&lt;/code&gt; is &lt;code&gt;invalid&lt;/code&gt;, this property contains a list of status error objects. 
        /// </summary>
        /// <value>If &lt;code&gt;status&lt;/code&gt; is &lt;code&gt;invalid&lt;/code&gt;, this property contains a list of status error objects. </value>
        [DataMember(Name = "error", EmitDefaultValue = false)]
        public List<AnswerFileStatusError> Error { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AnswerFileStatusResult {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  CheckedTime: ").Append(CheckedTime).Append("\n");
            sb.Append("  Host: ").Append(Host).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
