/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// Possible reasons why an access request is declined.  Possible values: - &#x60;invalid_request&#x60;: The request is missing a required parameter, includes an unsupported   parameter or parameter value, repeats the same parameter, uses more   than one method for including an access token, or is otherwise   malformed. - &#x60;invalid_token&#x60;: The access token is invalid, expired, revoked or is invalid for   other reasons.      The client may request a new access token and   retry the request. - &#x60;insufficient_scope&#x60;: The request requires higher privileges than provided by the access   token. - &#x60;registration_required&#x60;: vCenter requires registration of the full user claims to enable the   provided access token use in vCenter.      The client application should   obtain the full claims token from the authorization server on the   \&quot;ovl\&quot; field specified URI and register the full claims token with   vCenter. After registration, the client application should retry   the request. 
    /// </summary>
    /// <value>Possible reasons why an access request is declined.  Possible values: - &#x60;invalid_request&#x60;: The request is missing a required parameter, includes an unsupported   parameter or parameter value, repeats the same parameter, uses more   than one method for including an access token, or is otherwise   malformed. - &#x60;invalid_token&#x60;: The access token is invalid, expired, revoked or is invalid for   other reasons.      The client may request a new access token and   retry the request. - &#x60;insufficient_scope&#x60;: The request requires higher privileges than provided by the access   token. - &#x60;registration_required&#x60;: vCenter requires registration of the full user claims to enable the   provided access token use in vCenter.      The client application should   obtain the full claims token from the authorization server on the   \&quot;ovl\&quot; field specified URI and register the full claims token with   vCenter. After registration, the client application should retry   the request. </value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum AuthenticationRequiredErrorTypeEnum
    {
        /// <summary>
        /// Enum InvalidRequest for value: invalid_request
        /// </summary>
        [EnumMember(Value = "invalid_request")]
        InvalidRequest = 1,

        /// <summary>
        /// Enum InvalidToken for value: invalid_token
        /// </summary>
        [EnumMember(Value = "invalid_token")]
        InvalidToken = 2,

        /// <summary>
        /// Enum InsufficientScope for value: insufficient_scope
        /// </summary>
        [EnumMember(Value = "insufficient_scope")]
        InsufficientScope = 3,

        /// <summary>
        /// Enum RegistrationRequired for value: registration_required
        /// </summary>
        [EnumMember(Value = "registration_required")]
        RegistrationRequired = 4
    }

}
