/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// DiagnosticManagerLogHeader
    /// </summary>
    [DataContract(Name = "DiagnosticManagerLogHeader")]
    public partial class DiagnosticManagerLogHeader : DataObject, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DiagnosticManagerLogHeader" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DiagnosticManagerLogHeader() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DiagnosticManagerLogHeader" /> class.
        /// </summary>
        /// <param name="lineStart">The first line of this log segment.  (required).</param>
        /// <param name="lineEnd">The last line of this log segment.  (required).</param>
        /// <param name="lineText">Log entries, listed by line, for this log segment. .</param>
        /// <param name="typeName">The type discriminator. Refers to the name of a valid data object type.  (required) (default to &quot;DiagnosticManagerLogHeader&quot;).</param>
        public DiagnosticManagerLogHeader(int lineStart = default, int lineEnd = default, List<string> lineText = default, string typeName = @"DiagnosticManagerLogHeader") : base()
        {
            this.LineStart = lineStart;
            this.LineEnd = lineEnd;
            this.LineText = lineText;
        }

        /// <summary>
        /// The first line of this log segment. 
        /// </summary>
        /// <value>The first line of this log segment. </value>
        [DataMember(Name = "lineStart", IsRequired = true, EmitDefaultValue = true)]
        public int LineStart { get; set; }

        /// <summary>
        /// The last line of this log segment. 
        /// </summary>
        /// <value>The last line of this log segment. </value>
        [DataMember(Name = "lineEnd", IsRequired = true, EmitDefaultValue = true)]
        public int LineEnd { get; set; }

        /// <summary>
        /// Log entries, listed by line, for this log segment. 
        /// </summary>
        /// <value>Log entries, listed by line, for this log segment. </value>
        [DataMember(Name = "lineText", EmitDefaultValue = false)]
        public List<string> LineText { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DiagnosticManagerLogHeader {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  LineStart: ").Append(LineStart).Append("\n");
            sb.Append("  LineEnd: ").Append(LineEnd).Append("\n");
            sb.Append("  LineText: ").Append(LineText).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
