/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// Describe the runtime state of the uplink.  Possible values: - &#x60;active&#x60; - &#x60;standby&#x60; 
    /// </summary>
    /// <value>Describe the runtime state of the uplink.  Possible values: - &#x60;active&#x60; - &#x60;standby&#x60; </value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DistributedVirtualSwitchHostMemberHostUplinkStateStateEnum
    {
        /// <summary>
        /// Enum Active for value: active
        /// </summary>
        [EnumMember(Value = "active")]
        Active = 1,

        /// <summary>
        /// Enum Standby for value: standby
        /// </summary>
        [EnumMember(Value = "standby")]
        Standby = 2
    }

}
