/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// DpuStatusInfoOperationalInfo
    /// </summary>
    [DataContract(Name = "DpuStatusInfoOperationalInfo")]
    public partial class DpuStatusInfoOperationalInfo : DataObject, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DpuStatusInfoOperationalInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DpuStatusInfoOperationalInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DpuStatusInfoOperationalInfo" /> class.
        /// </summary>
        /// <param name="sensorId">This string uniquely identifies a sensor in the DPU.  (required).</param>
        /// <param name="healthState">The health state of the element indicated by the sensor.  See also *HostNumericSensorHealthState_enum*. .</param>
        /// <param name="reading">A description of the state of the sensor such as: N watts, Y RPM, or other measurement.  (required).</param>
        /// <param name="units">If provided by underlying API, the base units in which the sensor reading is specified, \&quot;RPM\&quot;, \&quot;WATTS\&quot; and so forth. .</param>
        /// <param name="timeStamp">Reports the ISO 8601 Timestamp when this sensor was last updated by management controller if the this sensor is capable of tracking when it was last updated.  Property timeStampRaw, which comes from vendor firmware is convertible to DateTime, it will be provided. .</param>
        /// <param name="typeName">The type discriminator. Refers to the name of a valid data object type.  (required) (default to &quot;DpuStatusInfoOperationalInfo&quot;).</param>
        public DpuStatusInfoOperationalInfo(string sensorId = default, ElementDescription healthState = default, string reading = default, string units = default, DateTime timeStamp = default, string typeName = @"DpuStatusInfoOperationalInfo") : base()
        {
            // to ensure "sensorId" is required (not null)
            if (sensorId == null)
            {
                throw new ArgumentNullException("sensorId is a required property for DpuStatusInfoOperationalInfo and cannot be null");
            }
            this.SensorId = sensorId;
            // to ensure "reading" is required (not null)
            if (reading == null)
            {
                throw new ArgumentNullException("reading is a required property for DpuStatusInfoOperationalInfo and cannot be null");
            }
            this.Reading = reading;
            this.HealthState = healthState;
            this.Units = units;
            this.TimeStamp = timeStamp;
        }

        /// <summary>
        /// This string uniquely identifies a sensor in the DPU. 
        /// </summary>
        /// <value>This string uniquely identifies a sensor in the DPU. </value>
        [DataMember(Name = "sensorId", IsRequired = true, EmitDefaultValue = true)]
        public string SensorId { get; set; }

        /// <summary>
        /// The health state of the element indicated by the sensor.  See also *HostNumericSensorHealthState_enum*. 
        /// </summary>
        /// <value>The health state of the element indicated by the sensor.  See also *HostNumericSensorHealthState_enum*. </value>
        [DataMember(Name = "healthState", EmitDefaultValue = false)]
        public ElementDescription HealthState { get; set; }

        /// <summary>
        /// A description of the state of the sensor such as: N watts, Y RPM, or other measurement. 
        /// </summary>
        /// <value>A description of the state of the sensor such as: N watts, Y RPM, or other measurement. </value>
        [DataMember(Name = "reading", IsRequired = true, EmitDefaultValue = true)]
        public string Reading { get; set; }

        /// <summary>
        /// If provided by underlying API, the base units in which the sensor reading is specified, \&quot;RPM\&quot;, \&quot;WATTS\&quot; and so forth. 
        /// </summary>
        /// <value>If provided by underlying API, the base units in which the sensor reading is specified, \&quot;RPM\&quot;, \&quot;WATTS\&quot; and so forth. </value>
        [DataMember(Name = "units", EmitDefaultValue = false)]
        public string Units { get; set; }

        /// <summary>
        /// Reports the ISO 8601 Timestamp when this sensor was last updated by management controller if the this sensor is capable of tracking when it was last updated.  Property timeStampRaw, which comes from vendor firmware is convertible to DateTime, it will be provided. 
        /// </summary>
        /// <value>Reports the ISO 8601 Timestamp when this sensor was last updated by management controller if the this sensor is capable of tracking when it was last updated.  Property timeStampRaw, which comes from vendor firmware is convertible to DateTime, it will be provided. </value>
        [DataMember(Name = "timeStamp", EmitDefaultValue = false)]
        public DateTime TimeStamp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DpuStatusInfoOperationalInfo {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  SensorId: ").Append(SensorId).Append("\n");
            sb.Append("  HealthState: ").Append(HealthState).Append("\n");
            sb.Append("  Reading: ").Append(Reading).Append("\n");
            sb.Append("  Units: ").Append(Units).Append("\n");
            sb.Append("  TimeStamp: ").Append(TimeStamp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
