/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// DVPortgroupConfigSpec
    /// </summary>
    [DataContract(Name = "DVPortgroupConfigSpec")]
    public partial class DVPortgroupConfigSpec : DataObject, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DVPortgroupConfigSpec" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DVPortgroupConfigSpec() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DVPortgroupConfigSpec" /> class.
        /// </summary>
        /// <param name="dynamicProperty">Set of dynamic properties.  This property is optional because only the properties of an object that are unknown to a client will be part of this set. This property is not readonly just in case we want to send such properties from a client in the future. .</param>
        /// <param name="configVersion">Version string of the configuration that this spec is trying to change.  This property is required in reconfiguring a portgroup and should be set to the same value as the *DVPortgroupConfigInfo.configVersion*. This property is ignored in creating a portgroup if set. .</param>
        /// <param name="name">Name of the portgroup. .</param>
        /// <param name="numPorts">Number of ports in the portgroup.  Setting this number larger than the number of existing ports in the portgroup causes new ports to be added to the portgroup to meet the number. Setting this property smaller than the number of existing ports deletes the free ports from the portgroup. If the number cannot be met by deleting free ports, a fault is raised. If new ports are added to the portgroup, they are also added to the switch. For portgroups of type ephemeral this property is ignored. .</param>
        /// <param name="portNameFormat">Format of the name of the ports when ports are created in the portgroup.  For details see *DVPortgroupConfigInfo.portNameFormat*. .</param>
        /// <param name="defaultPortConfig">Default network setting for all the ports in the portgroup. .</param>
        /// <param name="description">Description of the portgroup. .</param>
        /// <param name="type">Type of portgroup.  See *DistributedVirtualPortgroup*.*DistributedVirtualPortgroupPortgroupType_enum* for possible values. .</param>
        /// <param name="backingType">Backing type of portgroup.  See *DistributedVirtualPortgroup*.*DistributedVirtualPortgroupBackingType_enum* for possible values. The default value is \&quot;standard\&quot; .</param>
        /// <param name="scope">Deprecated as of vSphere API 5.5.  Eligible entities that can connect to the port.  See *DVPortgroupConfigInfo*.*DVPortgroupConfigInfo.scope*.  Refers instances of *ManagedEntity*. .</param>
        /// <param name="policy">Portgroup policy. .</param>
        /// <param name="vendorSpecificConfig">Opaque binary blob that stores vendor specific configuration. .</param>
        /// <param name="autoExpand">If set to true, this property ignores the limit on the number of ports in the portgroup.  When a Virtual Machine/Host tries to connect to the portgroup and there are no free ports available in the portgroup, new ports will be automatically added to the portgroup. The flag is currently supported only for static portgroups.  Setting this property to true makes the portgroup a potential candidate for auto-shrink. Once the portgroup has auto-expanded then its disconnected ports are likely to be deleted automatically, as a part of auto-shrink step, if there are more than certain number of free ports. If the portgroup never auto-expanded, then it will never lose any free ports. .</param>
        /// <param name="vmVnicNetworkResourcePoolKey">The key of virtual NIC network resource pool to be associated with a portgroup.  Setting this property to \&quot;-1\&quot;, would mean that this portgroup is not associated with any virtual NIC network resource pool. .</param>
        /// <param name="transportZoneUuid">The UUID of transport zone to be associated with a NSX portgroup. .</param>
        /// <param name="transportZoneName">The name of transport zone to be associated with a NSX portgroup. .</param>
        /// <param name="logicalSwitchUuid">The logical switch UUID, which is used by NSX portgroup .</param>
        /// <param name="segmentId">The segment ID of logical switch .</param>
        /// <param name="subnetId">The subnet ID of logical switch  ***Since:*** vSphere API Release 9.0.0.0 .</param>
        /// <param name="nsxConfig">The NSX-related configurations.  Update semantics: This structure uses an override model: the provided values replace existing ones, and omitted or unset properties are cleared.  ***Since:*** vSphere API Release 9.1.0.0 .</param>
        /// <param name="typeName">The type discriminator. Refers to the name of a valid data object type.  (required) (default to &quot;DVPortgroupConfigSpec&quot;).</param>
        public DVPortgroupConfigSpec(List<DynamicProperty> dynamicProperty = default, string configVersion = default, string name = default, int numPorts = default, string portNameFormat = default, DVPortSetting defaultPortConfig = default, string description = default, string type = default, string backingType = default, List<ManagedObjectReference> scope = default, DVPortgroupPolicy policy = default, List<DistributedVirtualSwitchKeyedOpaqueBlob> vendorSpecificConfig = default, bool autoExpand = default, string vmVnicNetworkResourcePoolKey = default, string transportZoneUuid = default, string transportZoneName = default, string logicalSwitchUuid = default, string segmentId = default, string subnetId = default, DVPortgroupNsxConfig nsxConfig = default, string typeName = @"DVPortgroupConfigSpec") : base()
        {
            this.DynamicProperty = dynamicProperty;
            this.ConfigVersion = configVersion;
            this.Name = name;
            this.NumPorts = numPorts;
            this.PortNameFormat = portNameFormat;
            this.DefaultPortConfig = defaultPortConfig;
            this.Description = description;
            this.Type = type;
            this.BackingType = backingType;
            this.Scope = scope;
            this.Policy = policy;
            this.VendorSpecificConfig = vendorSpecificConfig;
            this.AutoExpand = autoExpand;
            this.VmVnicNetworkResourcePoolKey = vmVnicNetworkResourcePoolKey;
            this.TransportZoneUuid = transportZoneUuid;
            this.TransportZoneName = transportZoneName;
            this.LogicalSwitchUuid = logicalSwitchUuid;
            this.SegmentId = segmentId;
            this.SubnetId = subnetId;
            this.NsxConfig = nsxConfig;
        }

        /// <summary>
        /// Set of dynamic properties.  This property is optional because only the properties of an object that are unknown to a client will be part of this set. This property is not readonly just in case we want to send such properties from a client in the future. 
        /// </summary>
        /// <value>Set of dynamic properties.  This property is optional because only the properties of an object that are unknown to a client will be part of this set. This property is not readonly just in case we want to send such properties from a client in the future. </value>
        [DataMember(Name = "dynamicProperty", EmitDefaultValue = false)]
        public List<DynamicProperty> DynamicProperty { get; set; }

        /// <summary>
        /// Version string of the configuration that this spec is trying to change.  This property is required in reconfiguring a portgroup and should be set to the same value as the *DVPortgroupConfigInfo.configVersion*. This property is ignored in creating a portgroup if set. 
        /// </summary>
        /// <value>Version string of the configuration that this spec is trying to change.  This property is required in reconfiguring a portgroup and should be set to the same value as the *DVPortgroupConfigInfo.configVersion*. This property is ignored in creating a portgroup if set. </value>
        [DataMember(Name = "configVersion", EmitDefaultValue = false)]
        public string ConfigVersion { get; set; }

        /// <summary>
        /// Name of the portgroup. 
        /// </summary>
        /// <value>Name of the portgroup. </value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Number of ports in the portgroup.  Setting this number larger than the number of existing ports in the portgroup causes new ports to be added to the portgroup to meet the number. Setting this property smaller than the number of existing ports deletes the free ports from the portgroup. If the number cannot be met by deleting free ports, a fault is raised. If new ports are added to the portgroup, they are also added to the switch. For portgroups of type ephemeral this property is ignored. 
        /// </summary>
        /// <value>Number of ports in the portgroup.  Setting this number larger than the number of existing ports in the portgroup causes new ports to be added to the portgroup to meet the number. Setting this property smaller than the number of existing ports deletes the free ports from the portgroup. If the number cannot be met by deleting free ports, a fault is raised. If new ports are added to the portgroup, they are also added to the switch. For portgroups of type ephemeral this property is ignored. </value>
        [DataMember(Name = "numPorts", EmitDefaultValue = false)]
        public int NumPorts { get; set; }

        /// <summary>
        /// Format of the name of the ports when ports are created in the portgroup.  For details see *DVPortgroupConfigInfo.portNameFormat*. 
        /// </summary>
        /// <value>Format of the name of the ports when ports are created in the portgroup.  For details see *DVPortgroupConfigInfo.portNameFormat*. </value>
        [DataMember(Name = "portNameFormat", EmitDefaultValue = false)]
        public string PortNameFormat { get; set; }

        /// <summary>
        /// Default network setting for all the ports in the portgroup. 
        /// </summary>
        /// <value>Default network setting for all the ports in the portgroup. </value>
        [DataMember(Name = "defaultPortConfig", EmitDefaultValue = false)]
        public DVPortSetting DefaultPortConfig { get; set; }

        /// <summary>
        /// Description of the portgroup. 
        /// </summary>
        /// <value>Description of the portgroup. </value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Type of portgroup.  See *DistributedVirtualPortgroup*.*DistributedVirtualPortgroupPortgroupType_enum* for possible values. 
        /// </summary>
        /// <value>Type of portgroup.  See *DistributedVirtualPortgroup*.*DistributedVirtualPortgroupPortgroupType_enum* for possible values. </value>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// Backing type of portgroup.  See *DistributedVirtualPortgroup*.*DistributedVirtualPortgroupBackingType_enum* for possible values. The default value is \&quot;standard\&quot; 
        /// </summary>
        /// <value>Backing type of portgroup.  See *DistributedVirtualPortgroup*.*DistributedVirtualPortgroupBackingType_enum* for possible values. The default value is \&quot;standard\&quot; </value>
        [DataMember(Name = "backingType", EmitDefaultValue = false)]
        public string BackingType { get; set; }

        /// <summary>
        /// Deprecated as of vSphere API 5.5.  Eligible entities that can connect to the port.  See *DVPortgroupConfigInfo*.*DVPortgroupConfigInfo.scope*.  Refers instances of *ManagedEntity*. 
        /// </summary>
        /// <value>Deprecated as of vSphere API 5.5.  Eligible entities that can connect to the port.  See *DVPortgroupConfigInfo*.*DVPortgroupConfigInfo.scope*.  Refers instances of *ManagedEntity*. </value>
        [DataMember(Name = "scope", EmitDefaultValue = false)]
        [Obsolete]
        public List<ManagedObjectReference> Scope { get; set; }

        /// <summary>
        /// Portgroup policy. 
        /// </summary>
        /// <value>Portgroup policy. </value>
        [DataMember(Name = "policy", EmitDefaultValue = false)]
        public DVPortgroupPolicy Policy { get; set; }

        /// <summary>
        /// Opaque binary blob that stores vendor specific configuration. 
        /// </summary>
        /// <value>Opaque binary blob that stores vendor specific configuration. </value>
        [DataMember(Name = "vendorSpecificConfig", EmitDefaultValue = false)]
        public List<DistributedVirtualSwitchKeyedOpaqueBlob> VendorSpecificConfig { get; set; }

        /// <summary>
        /// If set to true, this property ignores the limit on the number of ports in the portgroup.  When a Virtual Machine/Host tries to connect to the portgroup and there are no free ports available in the portgroup, new ports will be automatically added to the portgroup. The flag is currently supported only for static portgroups.  Setting this property to true makes the portgroup a potential candidate for auto-shrink. Once the portgroup has auto-expanded then its disconnected ports are likely to be deleted automatically, as a part of auto-shrink step, if there are more than certain number of free ports. If the portgroup never auto-expanded, then it will never lose any free ports. 
        /// </summary>
        /// <value>If set to true, this property ignores the limit on the number of ports in the portgroup.  When a Virtual Machine/Host tries to connect to the portgroup and there are no free ports available in the portgroup, new ports will be automatically added to the portgroup. The flag is currently supported only for static portgroups.  Setting this property to true makes the portgroup a potential candidate for auto-shrink. Once the portgroup has auto-expanded then its disconnected ports are likely to be deleted automatically, as a part of auto-shrink step, if there are more than certain number of free ports. If the portgroup never auto-expanded, then it will never lose any free ports. </value>
        [DataMember(Name = "autoExpand", EmitDefaultValue = true)]
        public bool AutoExpand { get; set; }

        /// <summary>
        /// The key of virtual NIC network resource pool to be associated with a portgroup.  Setting this property to \&quot;-1\&quot;, would mean that this portgroup is not associated with any virtual NIC network resource pool. 
        /// </summary>
        /// <value>The key of virtual NIC network resource pool to be associated with a portgroup.  Setting this property to \&quot;-1\&quot;, would mean that this portgroup is not associated with any virtual NIC network resource pool. </value>
        [DataMember(Name = "vmVnicNetworkResourcePoolKey", EmitDefaultValue = false)]
        public string VmVnicNetworkResourcePoolKey { get; set; }

        /// <summary>
        /// The UUID of transport zone to be associated with a NSX portgroup. 
        /// </summary>
        /// <value>The UUID of transport zone to be associated with a NSX portgroup. </value>
        [DataMember(Name = "transportZoneUuid", EmitDefaultValue = false)]
        public string TransportZoneUuid { get; set; }

        /// <summary>
        /// The name of transport zone to be associated with a NSX portgroup. 
        /// </summary>
        /// <value>The name of transport zone to be associated with a NSX portgroup. </value>
        [DataMember(Name = "transportZoneName", EmitDefaultValue = false)]
        public string TransportZoneName { get; set; }

        /// <summary>
        /// The logical switch UUID, which is used by NSX portgroup 
        /// </summary>
        /// <value>The logical switch UUID, which is used by NSX portgroup </value>
        [DataMember(Name = "logicalSwitchUuid", EmitDefaultValue = false)]
        public string LogicalSwitchUuid { get; set; }

        /// <summary>
        /// The segment ID of logical switch 
        /// </summary>
        /// <value>The segment ID of logical switch </value>
        [DataMember(Name = "segmentId", EmitDefaultValue = false)]
        public string SegmentId { get; set; }

        /// <summary>
        /// The subnet ID of logical switch  ***Since:*** vSphere API Release 9.0.0.0 
        /// </summary>
        /// <value>The subnet ID of logical switch  ***Since:*** vSphere API Release 9.0.0.0 </value>
        [DataMember(Name = "subnetId", EmitDefaultValue = false)]
        public string SubnetId { get; set; }

        /// <summary>
        /// The NSX-related configurations.  Update semantics: This structure uses an override model: the provided values replace existing ones, and omitted or unset properties are cleared.  ***Since:*** vSphere API Release 9.1.0.0 
        /// </summary>
        /// <value>The NSX-related configurations.  Update semantics: This structure uses an override model: the provided values replace existing ones, and omitted or unset properties are cleared.  ***Since:*** vSphere API Release 9.1.0.0 </value>
        [DataMember(Name = "nsxConfig", EmitDefaultValue = false)]
        public DVPortgroupNsxConfig NsxConfig { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DVPortgroupConfigSpec {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  DynamicProperty: ").Append(DynamicProperty).Append("\n");
            sb.Append("  ConfigVersion: ").Append(ConfigVersion).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  NumPorts: ").Append(NumPorts).Append("\n");
            sb.Append("  PortNameFormat: ").Append(PortNameFormat).Append("\n");
            sb.Append("  DefaultPortConfig: ").Append(DefaultPortConfig).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  BackingType: ").Append(BackingType).Append("\n");
            sb.Append("  Scope: ").Append(Scope).Append("\n");
            sb.Append("  Policy: ").Append(Policy).Append("\n");
            sb.Append("  VendorSpecificConfig: ").Append(VendorSpecificConfig).Append("\n");
            sb.Append("  AutoExpand: ").Append(AutoExpand).Append("\n");
            sb.Append("  VmVnicNetworkResourcePoolKey: ").Append(VmVnicNetworkResourcePoolKey).Append("\n");
            sb.Append("  TransportZoneUuid: ").Append(TransportZoneUuid).Append("\n");
            sb.Append("  TransportZoneName: ").Append(TransportZoneName).Append("\n");
            sb.Append("  LogicalSwitchUuid: ").Append(LogicalSwitchUuid).Append("\n");
            sb.Append("  SegmentId: ").Append(SegmentId).Append("\n");
            sb.Append("  SubnetId: ").Append(SubnetId).Append("\n");
            sb.Append("  NsxConfig: ").Append(NsxConfig).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
