/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// GuestFileAttributes
    /// </summary>
    [DataContract(Name = "GuestFileAttributes")]
    [JsonConverter(typeof(JsonSubtypes), "TypeName")]
    [JsonSubtypes.KnownSubType(typeof(ArrayOfURI), "ArrayOfAnyURI")]
    [JsonSubtypes.KnownSubType(typeof(ArrayOfBinary), "ArrayOfBase64Binary")]
    [JsonSubtypes.KnownSubType(typeof(ArrayOfPropPath), "ArrayOfPropertyPath")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveMethodName), "MethodName")]
    [JsonSubtypes.KnownSubType(typeof(PrimitivePropPath), "PropertyPath")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveTypeName), "TypeName")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveURI), "anyURI")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveBinary), "base64Binary")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveBoolean), "boolean")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveByte), "byte")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveDateTime), "dateTime")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveDouble), "double")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveFloat), "float")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveInt), "int")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveLong), "long")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveShort), "short")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveString), "string")]
    [JsonSubtypes.KnownSubType(typeof(GuestPosixFileAttributes), "GuestPosixFileAttributes")]
    [JsonSubtypes.KnownSubType(typeof(GuestWindowsFileAttributes), "GuestWindowsFileAttributes")]
    public partial class GuestFileAttributes : DataObject, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GuestFileAttributes" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GuestFileAttributes() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GuestFileAttributes" /> class.
        /// </summary>
        /// <param name="modificationTime">The date and time the file was last modified.  If this property is not specified when passing a *GuestFileAttributes* object to *GuestFileManager.InitiateFileTransferToGuest*, the default value will be the time when the file is created inside the guest. .</param>
        /// <param name="accessTime">The date and time the file was last accessed.  If this property is not specified when passing a *GuestFileAttributes* object to *GuestFileManager.InitiateFileTransferToGuest*, the default value will be the time when the file is created inside the guest. .</param>
        /// <param name="symlinkTarget">The target for the file if it&#39;s a symbolic link.  This is currently only set for Linux guest operating systems, but may be supported in the future on Windows guest operating systems that support symbolic links. This property gives information about files when returned from *GuestFileManager.ListFilesInGuest* or *GuestFileManager.InitiateFileTransferFromGuest* as part of a *GuestFileAttributes* object. This property will be ignored when passing a *GuestFileAttributes* object to *GuestFileManager.InitiateFileTransferToGuest* or *GuestFileManager.ChangeFileAttributesInGuest*. If the file is a symbolic link, then the attributes of the target are returned, not those of the symbolic link. .</param>
        /// <param name="typeName">The type discriminator. Refers to the name of a valid data object type.  (required) (default to &quot;GuestFileAttributes&quot;).</param>
        public GuestFileAttributes(DateTime modificationTime = default, DateTime accessTime = default, string symlinkTarget = default, string typeName = @"GuestFileAttributes") : base()
        {
            this.ModificationTime = modificationTime;
            this.AccessTime = accessTime;
            this.SymlinkTarget = symlinkTarget;
        }

        /// <summary>
        /// The date and time the file was last modified.  If this property is not specified when passing a *GuestFileAttributes* object to *GuestFileManager.InitiateFileTransferToGuest*, the default value will be the time when the file is created inside the guest. 
        /// </summary>
        /// <value>The date and time the file was last modified.  If this property is not specified when passing a *GuestFileAttributes* object to *GuestFileManager.InitiateFileTransferToGuest*, the default value will be the time when the file is created inside the guest. </value>
        [DataMember(Name = "modificationTime", EmitDefaultValue = false)]
        public DateTime ModificationTime { get; set; }

        /// <summary>
        /// The date and time the file was last accessed.  If this property is not specified when passing a *GuestFileAttributes* object to *GuestFileManager.InitiateFileTransferToGuest*, the default value will be the time when the file is created inside the guest. 
        /// </summary>
        /// <value>The date and time the file was last accessed.  If this property is not specified when passing a *GuestFileAttributes* object to *GuestFileManager.InitiateFileTransferToGuest*, the default value will be the time when the file is created inside the guest. </value>
        [DataMember(Name = "accessTime", EmitDefaultValue = false)]
        public DateTime AccessTime { get; set; }

        /// <summary>
        /// The target for the file if it&#39;s a symbolic link.  This is currently only set for Linux guest operating systems, but may be supported in the future on Windows guest operating systems that support symbolic links. This property gives information about files when returned from *GuestFileManager.ListFilesInGuest* or *GuestFileManager.InitiateFileTransferFromGuest* as part of a *GuestFileAttributes* object. This property will be ignored when passing a *GuestFileAttributes* object to *GuestFileManager.InitiateFileTransferToGuest* or *GuestFileManager.ChangeFileAttributesInGuest*. If the file is a symbolic link, then the attributes of the target are returned, not those of the symbolic link. 
        /// </summary>
        /// <value>The target for the file if it&#39;s a symbolic link.  This is currently only set for Linux guest operating systems, but may be supported in the future on Windows guest operating systems that support symbolic links. This property gives information about files when returned from *GuestFileManager.ListFilesInGuest* or *GuestFileManager.InitiateFileTransferFromGuest* as part of a *GuestFileAttributes* object. This property will be ignored when passing a *GuestFileAttributes* object to *GuestFileManager.InitiateFileTransferToGuest* or *GuestFileManager.ChangeFileAttributesInGuest*. If the file is a symbolic link, then the attributes of the target are returned, not those of the symbolic link. </value>
        [DataMember(Name = "symlinkTarget", EmitDefaultValue = false)]
        public string SymlinkTarget { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GuestFileAttributes {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  ModificationTime: ").Append(ModificationTime).Append("\n");
            sb.Append("  AccessTime: ").Append(AccessTime).Append("\n");
            sb.Append("  SymlinkTarget: ").Append(SymlinkTarget).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
