/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// Possible values: - &#x60;Memory&#x60; - &#x60;Power&#x60; - &#x60;Fan&#x60; - &#x60;Network&#x60; - &#x60;Storage&#x60; 
    /// </summary>
    /// <value>Possible values: - &#x60;Memory&#x60; - &#x60;Power&#x60; - &#x60;Fan&#x60; - &#x60;Network&#x60; - &#x60;Storage&#x60; </value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum HealthUpdateInfoComponentTypeEnum
    {
        /// <summary>
        /// Enum Memory for value: Memory
        /// </summary>
        [EnumMember(Value = "Memory")]
        Memory = 1,

        /// <summary>
        /// Enum Power for value: Power
        /// </summary>
        [EnumMember(Value = "Power")]
        Power = 2,

        /// <summary>
        /// Enum Fan for value: Fan
        /// </summary>
        [EnumMember(Value = "Fan")]
        Fan = 3,

        /// <summary>
        /// Enum Network for value: Network
        /// </summary>
        [EnumMember(Value = "Network")]
        Network = 4,

        /// <summary>
        /// Enum Storage for value: Storage
        /// </summary>
        [EnumMember(Value = "Storage")]
        Storage = 5
    }

}
