/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// Deprecated as of vSphere API 6.0.  Set of possible values for *HostCapability.replayUnsupportedReason* and *HostCapability.replayCompatibilityIssues*.  Possible values: - &#x60;incompatibleProduct&#x60; - &#x60;incompatibleCpu&#x60; - &#x60;hvDisabled&#x60; - &#x60;cpuidLimitSet&#x60; - &#x60;oldBIOS&#x60; - &#x60;unknown&#x60; 
    /// </summary>
    /// <value>Deprecated as of vSphere API 6.0.  Set of possible values for *HostCapability.replayUnsupportedReason* and *HostCapability.replayCompatibilityIssues*.  Possible values: - &#x60;incompatibleProduct&#x60; - &#x60;incompatibleCpu&#x60; - &#x60;hvDisabled&#x60; - &#x60;cpuidLimitSet&#x60; - &#x60;oldBIOS&#x60; - &#x60;unknown&#x60; </value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum HostReplayUnsupportedReasonEnum
    {
        /// <summary>
        /// Enum IncompatibleProduct for value: incompatibleProduct
        /// </summary>
        [EnumMember(Value = "incompatibleProduct")]
        IncompatibleProduct = 1,

        /// <summary>
        /// Enum IncompatibleCpu for value: incompatibleCpu
        /// </summary>
        [EnumMember(Value = "incompatibleCpu")]
        IncompatibleCpu = 2,

        /// <summary>
        /// Enum HvDisabled for value: hvDisabled
        /// </summary>
        [EnumMember(Value = "hvDisabled")]
        HvDisabled = 3,

        /// <summary>
        /// Enum CpuidLimitSet for value: cpuidLimitSet
        /// </summary>
        [EnumMember(Value = "cpuidLimitSet")]
        CpuidLimitSet = 4,

        /// <summary>
        /// Enum OldBIOS for value: oldBIOS
        /// </summary>
        [EnumMember(Value = "oldBIOS")]
        OldBIOS = 5,

        /// <summary>
        /// Enum Unknown for value: unknown
        /// </summary>
        [EnumMember(Value = "unknown")]
        Unknown = 6
    }

}
