/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// HostProfileManagerCompositionResult
    /// </summary>
    [DataContract(Name = "HostProfileManagerCompositionResult")]
    public partial class HostProfileManagerCompositionResult : DataObject, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HostProfileManagerCompositionResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected HostProfileManagerCompositionResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="HostProfileManagerCompositionResult" /> class.
        /// </summary>
        /// <param name="errors">The composition errors for all targets, for example, the source profile doesn&#39;t exist. .</param>
        /// <param name="results">The array of *HostProfileManagerCompositionResultResultElement* for all the target host profiles. .</param>
        /// <param name="typeName">The type discriminator. Refers to the name of a valid data object type.  (required) (default to &quot;HostProfileManagerCompositionResult&quot;).</param>
        public HostProfileManagerCompositionResult(List<LocalizableMessage> errors = default, List<HostProfileManagerCompositionResultResultElement> results = default, string typeName = @"HostProfileManagerCompositionResult") : base()
        {
            this.Errors = errors;
            this.Results = results;
        }

        /// <summary>
        /// The composition errors for all targets, for example, the source profile doesn&#39;t exist. 
        /// </summary>
        /// <value>The composition errors for all targets, for example, the source profile doesn&#39;t exist. </value>
        [DataMember(Name = "errors", EmitDefaultValue = false)]
        public List<LocalizableMessage> Errors { get; set; }

        /// <summary>
        /// The array of *HostProfileManagerCompositionResultResultElement* for all the target host profiles. 
        /// </summary>
        /// <value>The array of *HostProfileManagerCompositionResultResultElement* for all the target host profiles. </value>
        [DataMember(Name = "results", EmitDefaultValue = false)]
        public List<HostProfileManagerCompositionResultResultElement> Results { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HostProfileManagerCompositionResult {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("  Results: ").Append(Results).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
