/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// HostInternetScsiHbaIPCapabilities
    /// </summary>
    [DataContract(Name = "HostInternetScsiHbaIPCapabilities")]
    public partial class HostInternetScsiHbaIPCapabilities : DataObject, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HostInternetScsiHbaIPCapabilities" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected HostInternetScsiHbaIPCapabilities() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="HostInternetScsiHbaIPCapabilities" /> class.
        /// </summary>
        /// <param name="addressSettable">True if the host bus adapter supports setting its IPv4 address.  (required).</param>
        /// <param name="ipConfigurationMethodSettable">True if the host bus adapter supports DHCPv4.  (required).</param>
        /// <param name="subnetMaskSettable">True if the host bus adapter supports setting its IPv4 subnet mask.  (required).</param>
        /// <param name="defaultGatewaySettable">True if the host bus adapter supports setting its IPv4 gateway.  (required).</param>
        /// <param name="primaryDnsServerAddressSettable">True if the host bus adapter supports setting its primary DNS.  (required).</param>
        /// <param name="alternateDnsServerAddressSettable">True if the host bus adapter supports setting its secondary DNS.  (required).</param>
        /// <param name="ipv6Supported">True if the host bus adapter supports the use of IPv6 addresses .</param>
        /// <param name="arpRedirectSettable">True if the host bus adapter supports setting its ARP Redirect value .</param>
        /// <param name="mtuSettable">True if the host bus adapter supports setting its MTU, (for Jumbo Frames, etc) .</param>
        /// <param name="hostNameAsTargetAddress">True if the discovery and static targets can be configured with a host name as opposed to an IP address. .</param>
        /// <param name="nameAliasSettable">True if the host bus adapter supports setting its name and alias .</param>
        /// <param name="ipv4EnableSettable">True if IPv4 addressing can be enabled or disabled on the host bus adapter. .</param>
        /// <param name="ipv6EnableSettable">True if IPv6 addressing can be enabled or disabled on the host bus adapter. .</param>
        /// <param name="ipv6PrefixLengthSettable">True if the Host bus adapter supports setting IPv6 Prefix Length. .</param>
        /// <param name="ipv6PrefixLength">Provides the value that user should be using if host bus adapter does not support changing of prefix length. .</param>
        /// <param name="ipv6DhcpConfigurationSettable">True if the Host bus adapter supports DHCPv6 configuration. .</param>
        /// <param name="ipv6LinkLocalAutoConfigurationSettable">True if the Host bus adapter supports setting configuration of its IPv6 link local address User can specify link local static address if link local auto configuration is set to false.  link local address usually starts with fe80: and has prefix 64. .</param>
        /// <param name="ipv6RouterAdvertisementConfigurationSettable">True if the Host bus adapter supports router advertisement configuration method.  Note: Currently Qlogic adapter does not support plumbing of any user specified static address if router advertisement method is enabled. .</param>
        /// <param name="ipv6DefaultGatewaySettable">True if the Host bus adapter supports setting its IPv6 default gateway. .</param>
        /// <param name="ipv6MaxStaticAddressesSupported">The maximum number of supported IPv6 static addresses on the host bus adapter that user can set. .</param>
        /// <param name="typeName">The type discriminator. Refers to the name of a valid data object type.  (required) (default to &quot;HostInternetScsiHbaIPCapabilities&quot;).</param>
        public HostInternetScsiHbaIPCapabilities(bool addressSettable = default, bool ipConfigurationMethodSettable = default, bool subnetMaskSettable = default, bool defaultGatewaySettable = default, bool primaryDnsServerAddressSettable = default, bool alternateDnsServerAddressSettable = default, bool ipv6Supported = default, bool arpRedirectSettable = default, bool mtuSettable = default, bool hostNameAsTargetAddress = default, bool nameAliasSettable = default, bool ipv4EnableSettable = default, bool ipv6EnableSettable = default, bool ipv6PrefixLengthSettable = default, int ipv6PrefixLength = default, bool ipv6DhcpConfigurationSettable = default, bool ipv6LinkLocalAutoConfigurationSettable = default, bool ipv6RouterAdvertisementConfigurationSettable = default, bool ipv6DefaultGatewaySettable = default, int ipv6MaxStaticAddressesSupported = default, string typeName = @"HostInternetScsiHbaIPCapabilities") : base()
        {
            this.AddressSettable = addressSettable;
            this.IpConfigurationMethodSettable = ipConfigurationMethodSettable;
            this.SubnetMaskSettable = subnetMaskSettable;
            this.DefaultGatewaySettable = defaultGatewaySettable;
            this.PrimaryDnsServerAddressSettable = primaryDnsServerAddressSettable;
            this.AlternateDnsServerAddressSettable = alternateDnsServerAddressSettable;
            this.Ipv6Supported = ipv6Supported;
            this.ArpRedirectSettable = arpRedirectSettable;
            this.MtuSettable = mtuSettable;
            this.HostNameAsTargetAddress = hostNameAsTargetAddress;
            this.NameAliasSettable = nameAliasSettable;
            this.Ipv4EnableSettable = ipv4EnableSettable;
            this.Ipv6EnableSettable = ipv6EnableSettable;
            this.Ipv6PrefixLengthSettable = ipv6PrefixLengthSettable;
            this.Ipv6PrefixLength = ipv6PrefixLength;
            this.Ipv6DhcpConfigurationSettable = ipv6DhcpConfigurationSettable;
            this.Ipv6LinkLocalAutoConfigurationSettable = ipv6LinkLocalAutoConfigurationSettable;
            this.Ipv6RouterAdvertisementConfigurationSettable = ipv6RouterAdvertisementConfigurationSettable;
            this.Ipv6DefaultGatewaySettable = ipv6DefaultGatewaySettable;
            this.Ipv6MaxStaticAddressesSupported = ipv6MaxStaticAddressesSupported;
        }

        /// <summary>
        /// True if the host bus adapter supports setting its IPv4 address. 
        /// </summary>
        /// <value>True if the host bus adapter supports setting its IPv4 address. </value>
        [DataMember(Name = "addressSettable", IsRequired = true, EmitDefaultValue = true)]
        public bool AddressSettable { get; set; }

        /// <summary>
        /// True if the host bus adapter supports DHCPv4. 
        /// </summary>
        /// <value>True if the host bus adapter supports DHCPv4. </value>
        [DataMember(Name = "ipConfigurationMethodSettable", IsRequired = true, EmitDefaultValue = true)]
        public bool IpConfigurationMethodSettable { get; set; }

        /// <summary>
        /// True if the host bus adapter supports setting its IPv4 subnet mask. 
        /// </summary>
        /// <value>True if the host bus adapter supports setting its IPv4 subnet mask. </value>
        [DataMember(Name = "subnetMaskSettable", IsRequired = true, EmitDefaultValue = true)]
        public bool SubnetMaskSettable { get; set; }

        /// <summary>
        /// True if the host bus adapter supports setting its IPv4 gateway. 
        /// </summary>
        /// <value>True if the host bus adapter supports setting its IPv4 gateway. </value>
        [DataMember(Name = "defaultGatewaySettable", IsRequired = true, EmitDefaultValue = true)]
        public bool DefaultGatewaySettable { get; set; }

        /// <summary>
        /// True if the host bus adapter supports setting its primary DNS. 
        /// </summary>
        /// <value>True if the host bus adapter supports setting its primary DNS. </value>
        [DataMember(Name = "primaryDnsServerAddressSettable", IsRequired = true, EmitDefaultValue = true)]
        public bool PrimaryDnsServerAddressSettable { get; set; }

        /// <summary>
        /// True if the host bus adapter supports setting its secondary DNS. 
        /// </summary>
        /// <value>True if the host bus adapter supports setting its secondary DNS. </value>
        [DataMember(Name = "alternateDnsServerAddressSettable", IsRequired = true, EmitDefaultValue = true)]
        public bool AlternateDnsServerAddressSettable { get; set; }

        /// <summary>
        /// True if the host bus adapter supports the use of IPv6 addresses 
        /// </summary>
        /// <value>True if the host bus adapter supports the use of IPv6 addresses </value>
        [DataMember(Name = "ipv6Supported", EmitDefaultValue = true)]
        public bool Ipv6Supported { get; set; }

        /// <summary>
        /// True if the host bus adapter supports setting its ARP Redirect value 
        /// </summary>
        /// <value>True if the host bus adapter supports setting its ARP Redirect value </value>
        [DataMember(Name = "arpRedirectSettable", EmitDefaultValue = true)]
        public bool ArpRedirectSettable { get; set; }

        /// <summary>
        /// True if the host bus adapter supports setting its MTU, (for Jumbo Frames, etc) 
        /// </summary>
        /// <value>True if the host bus adapter supports setting its MTU, (for Jumbo Frames, etc) </value>
        [DataMember(Name = "mtuSettable", EmitDefaultValue = true)]
        public bool MtuSettable { get; set; }

        /// <summary>
        /// True if the discovery and static targets can be configured with a host name as opposed to an IP address. 
        /// </summary>
        /// <value>True if the discovery and static targets can be configured with a host name as opposed to an IP address. </value>
        [DataMember(Name = "hostNameAsTargetAddress", EmitDefaultValue = true)]
        public bool HostNameAsTargetAddress { get; set; }

        /// <summary>
        /// True if the host bus adapter supports setting its name and alias 
        /// </summary>
        /// <value>True if the host bus adapter supports setting its name and alias </value>
        [DataMember(Name = "nameAliasSettable", EmitDefaultValue = true)]
        public bool NameAliasSettable { get; set; }

        /// <summary>
        /// True if IPv4 addressing can be enabled or disabled on the host bus adapter. 
        /// </summary>
        /// <value>True if IPv4 addressing can be enabled or disabled on the host bus adapter. </value>
        [DataMember(Name = "ipv4EnableSettable", EmitDefaultValue = true)]
        public bool Ipv4EnableSettable { get; set; }

        /// <summary>
        /// True if IPv6 addressing can be enabled or disabled on the host bus adapter. 
        /// </summary>
        /// <value>True if IPv6 addressing can be enabled or disabled on the host bus adapter. </value>
        [DataMember(Name = "ipv6EnableSettable", EmitDefaultValue = true)]
        public bool Ipv6EnableSettable { get; set; }

        /// <summary>
        /// True if the Host bus adapter supports setting IPv6 Prefix Length. 
        /// </summary>
        /// <value>True if the Host bus adapter supports setting IPv6 Prefix Length. </value>
        [DataMember(Name = "ipv6PrefixLengthSettable", EmitDefaultValue = true)]
        public bool Ipv6PrefixLengthSettable { get; set; }

        /// <summary>
        /// Provides the value that user should be using if host bus adapter does not support changing of prefix length. 
        /// </summary>
        /// <value>Provides the value that user should be using if host bus adapter does not support changing of prefix length. </value>
        [DataMember(Name = "ipv6PrefixLength", EmitDefaultValue = false)]
        public int Ipv6PrefixLength { get; set; }

        /// <summary>
        /// True if the Host bus adapter supports DHCPv6 configuration. 
        /// </summary>
        /// <value>True if the Host bus adapter supports DHCPv6 configuration. </value>
        [DataMember(Name = "ipv6DhcpConfigurationSettable", EmitDefaultValue = true)]
        public bool Ipv6DhcpConfigurationSettable { get; set; }

        /// <summary>
        /// True if the Host bus adapter supports setting configuration of its IPv6 link local address User can specify link local static address if link local auto configuration is set to false.  link local address usually starts with fe80: and has prefix 64. 
        /// </summary>
        /// <value>True if the Host bus adapter supports setting configuration of its IPv6 link local address User can specify link local static address if link local auto configuration is set to false.  link local address usually starts with fe80: and has prefix 64. </value>
        [DataMember(Name = "ipv6LinkLocalAutoConfigurationSettable", EmitDefaultValue = true)]
        public bool Ipv6LinkLocalAutoConfigurationSettable { get; set; }

        /// <summary>
        /// True if the Host bus adapter supports router advertisement configuration method.  Note: Currently Qlogic adapter does not support plumbing of any user specified static address if router advertisement method is enabled. 
        /// </summary>
        /// <value>True if the Host bus adapter supports router advertisement configuration method.  Note: Currently Qlogic adapter does not support plumbing of any user specified static address if router advertisement method is enabled. </value>
        [DataMember(Name = "ipv6RouterAdvertisementConfigurationSettable", EmitDefaultValue = true)]
        public bool Ipv6RouterAdvertisementConfigurationSettable { get; set; }

        /// <summary>
        /// True if the Host bus adapter supports setting its IPv6 default gateway. 
        /// </summary>
        /// <value>True if the Host bus adapter supports setting its IPv6 default gateway. </value>
        [DataMember(Name = "ipv6DefaultGatewaySettable", EmitDefaultValue = true)]
        public bool Ipv6DefaultGatewaySettable { get; set; }

        /// <summary>
        /// The maximum number of supported IPv6 static addresses on the host bus adapter that user can set. 
        /// </summary>
        /// <value>The maximum number of supported IPv6 static addresses on the host bus adapter that user can set. </value>
        [DataMember(Name = "ipv6MaxStaticAddressesSupported", EmitDefaultValue = false)]
        public int Ipv6MaxStaticAddressesSupported { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HostInternetScsiHbaIPCapabilities {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  AddressSettable: ").Append(AddressSettable).Append("\n");
            sb.Append("  IpConfigurationMethodSettable: ").Append(IpConfigurationMethodSettable).Append("\n");
            sb.Append("  SubnetMaskSettable: ").Append(SubnetMaskSettable).Append("\n");
            sb.Append("  DefaultGatewaySettable: ").Append(DefaultGatewaySettable).Append("\n");
            sb.Append("  PrimaryDnsServerAddressSettable: ").Append(PrimaryDnsServerAddressSettable).Append("\n");
            sb.Append("  AlternateDnsServerAddressSettable: ").Append(AlternateDnsServerAddressSettable).Append("\n");
            sb.Append("  Ipv6Supported: ").Append(Ipv6Supported).Append("\n");
            sb.Append("  ArpRedirectSettable: ").Append(ArpRedirectSettable).Append("\n");
            sb.Append("  MtuSettable: ").Append(MtuSettable).Append("\n");
            sb.Append("  HostNameAsTargetAddress: ").Append(HostNameAsTargetAddress).Append("\n");
            sb.Append("  NameAliasSettable: ").Append(NameAliasSettable).Append("\n");
            sb.Append("  Ipv4EnableSettable: ").Append(Ipv4EnableSettable).Append("\n");
            sb.Append("  Ipv6EnableSettable: ").Append(Ipv6EnableSettable).Append("\n");
            sb.Append("  Ipv6PrefixLengthSettable: ").Append(Ipv6PrefixLengthSettable).Append("\n");
            sb.Append("  Ipv6PrefixLength: ").Append(Ipv6PrefixLength).Append("\n");
            sb.Append("  Ipv6DhcpConfigurationSettable: ").Append(Ipv6DhcpConfigurationSettable).Append("\n");
            sb.Append("  Ipv6LinkLocalAutoConfigurationSettable: ").Append(Ipv6LinkLocalAutoConfigurationSettable).Append("\n");
            sb.Append("  Ipv6RouterAdvertisementConfigurationSettable: ").Append(Ipv6RouterAdvertisementConfigurationSettable).Append("\n");
            sb.Append("  Ipv6DefaultGatewaySettable: ").Append(Ipv6DefaultGatewaySettable).Append("\n");
            sb.Append("  Ipv6MaxStaticAddressesSupported: ").Append(Ipv6MaxStaticAddressesSupported).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
