/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// HostPatchManagerStatusPrerequisitePatch
    /// </summary>
    [DataContract(Name = "HostPatchManagerStatusPrerequisitePatch")]
    public partial class HostPatchManagerStatusPrerequisitePatch : DataObject, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HostPatchManagerStatusPrerequisitePatch" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected HostPatchManagerStatusPrerequisitePatch() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="HostPatchManagerStatusPrerequisitePatch" /> class.
        /// </summary>
        /// <param name="id">Unique identifier of the prerequisite update.  (required).</param>
        /// <param name="installState">The requirement on the server or services running on the server pertaining to the prerequisite update.  For example, this update could require the server to be rebooted after the prerequisite update is installed. Unset if there is no additional requirement on the prerequisite update.  See also *HostPatchManagerInstallState_enum*. .</param>
        /// <param name="typeName">The type discriminator. Refers to the name of a valid data object type.  (required) (default to &quot;HostPatchManagerStatusPrerequisitePatch&quot;).</param>
        public HostPatchManagerStatusPrerequisitePatch(string id = default, List<string> installState = default, string typeName = @"HostPatchManagerStatusPrerequisitePatch") : base()
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for HostPatchManagerStatusPrerequisitePatch and cannot be null");
            }
            this.Id = id;
            this.InstallState = installState;
        }

        /// <summary>
        /// Unique identifier of the prerequisite update. 
        /// </summary>
        /// <value>Unique identifier of the prerequisite update. </value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// The requirement on the server or services running on the server pertaining to the prerequisite update.  For example, this update could require the server to be rebooted after the prerequisite update is installed. Unset if there is no additional requirement on the prerequisite update.  See also *HostPatchManagerInstallState_enum*. 
        /// </summary>
        /// <value>The requirement on the server or services running on the server pertaining to the prerequisite update.  For example, this update could require the server to be rebooted after the prerequisite update is installed. Unset if there is no additional requirement on the prerequisite update.  See also *HostPatchManagerInstallState_enum*. </value>
        [DataMember(Name = "installState", EmitDefaultValue = false)]
        public List<string> InstallState { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HostPatchManagerStatusPrerequisitePatch {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  InstallState: ").Append(InstallState).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
