/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// KmipServerSpecWrappingRotationIntervalKeySpec
    /// </summary>
    [DataContract(Name = "KmipServerSpecWrappingRotationIntervalKeySpec")]
    public partial class KmipServerSpecWrappingRotationIntervalKeySpec : KmipServerSpecKeySpec, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KmipServerSpecWrappingRotationIntervalKeySpec" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected KmipServerSpecWrappingRotationIntervalKeySpec() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="KmipServerSpecWrappingRotationIntervalKeySpec" /> class.
        /// </summary>
        /// <param name="rotationInterval">Wrapping key regular rotation interval (number of days).  The allowed minimum number of days is 30 days, and maximum number of days is 3650 days. If not set, then a system default number of days will be used. .</param>
        /// <param name="typeName">The type discriminator. Refers to the name of a valid data object type.  (required) (default to &quot;KmipServerSpecWrappingRotationIntervalKeySpec&quot;).</param>
        public KmipServerSpecWrappingRotationIntervalKeySpec(int rotationInterval = default, string typeName = @"KmipServerSpecWrappingRotationIntervalKeySpec") : base()
        {
            this.RotationInterval = rotationInterval;
        }

        /// <summary>
        /// Wrapping key regular rotation interval (number of days).  The allowed minimum number of days is 30 days, and maximum number of days is 3650 days. If not set, then a system default number of days will be used. 
        /// </summary>
        /// <value>Wrapping key regular rotation interval (number of days).  The allowed minimum number of days is 30 days, and maximum number of days is 3650 days. If not set, then a system default number of days will be used. </value>
        [DataMember(Name = "rotationInterval", EmitDefaultValue = false)]
        public int RotationInterval { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KmipServerSpecWrappingRotationIntervalKeySpec {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  RotationInterval: ").Append(RotationInterval).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
