/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// LinkLayerDiscoveryProtocolInfo
    /// </summary>
    [DataContract(Name = "LinkLayerDiscoveryProtocolInfo")]
    public partial class LinkLayerDiscoveryProtocolInfo : DataObject, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkLayerDiscoveryProtocolInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LinkLayerDiscoveryProtocolInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkLayerDiscoveryProtocolInfo" /> class.
        /// </summary>
        /// <param name="chassisId">ChassisId represents the chassis identification for the device that transmitted the LLDP frame.  The receiving LLDP agent combines the Chassis ID and portId to represent the entity connected to the port where the frame was received.  (required).</param>
        /// <param name="portId">This property identifies the specific port that transmitted the LLDP frame.  The receiving LLDP agent combines the Chassis ID and Port to represent the entity connected to the port where the frame was received.  (required).</param>
        /// <param name="timeToLive">It is the duration of time in seconds for which information contained in the received LLDP frame shall be valid.  If a value of zero is sent it can also identify a device that has shut down or is no longer transmitting, prompting deletion of the record from the local database.  (required).</param>
        /// <param name="varParameter">LLDP parameters .</param>
        /// <param name="typeName">The type discriminator. Refers to the name of a valid data object type.  (required) (default to &quot;LinkLayerDiscoveryProtocolInfo&quot;).</param>
        public LinkLayerDiscoveryProtocolInfo(string chassisId = default, string portId = default, int timeToLive = default, List<KeyAnyValue> varParameter = default, string typeName = @"LinkLayerDiscoveryProtocolInfo") : base()
        {
            // to ensure "chassisId" is required (not null)
            if (chassisId == null)
            {
                throw new ArgumentNullException("chassisId is a required property for LinkLayerDiscoveryProtocolInfo and cannot be null");
            }
            this.ChassisId = chassisId;
            // to ensure "portId" is required (not null)
            if (portId == null)
            {
                throw new ArgumentNullException("portId is a required property for LinkLayerDiscoveryProtocolInfo and cannot be null");
            }
            this.PortId = portId;
            this.TimeToLive = timeToLive;
            this.Parameter = varParameter;
        }

        /// <summary>
        /// ChassisId represents the chassis identification for the device that transmitted the LLDP frame.  The receiving LLDP agent combines the Chassis ID and portId to represent the entity connected to the port where the frame was received. 
        /// </summary>
        /// <value>ChassisId represents the chassis identification for the device that transmitted the LLDP frame.  The receiving LLDP agent combines the Chassis ID and portId to represent the entity connected to the port where the frame was received. </value>
        [DataMember(Name = "chassisId", IsRequired = true, EmitDefaultValue = true)]
        public string ChassisId { get; set; }

        /// <summary>
        /// This property identifies the specific port that transmitted the LLDP frame.  The receiving LLDP agent combines the Chassis ID and Port to represent the entity connected to the port where the frame was received. 
        /// </summary>
        /// <value>This property identifies the specific port that transmitted the LLDP frame.  The receiving LLDP agent combines the Chassis ID and Port to represent the entity connected to the port where the frame was received. </value>
        [DataMember(Name = "portId", IsRequired = true, EmitDefaultValue = true)]
        public string PortId { get; set; }

        /// <summary>
        /// It is the duration of time in seconds for which information contained in the received LLDP frame shall be valid.  If a value of zero is sent it can also identify a device that has shut down or is no longer transmitting, prompting deletion of the record from the local database. 
        /// </summary>
        /// <value>It is the duration of time in seconds for which information contained in the received LLDP frame shall be valid.  If a value of zero is sent it can also identify a device that has shut down or is no longer transmitting, prompting deletion of the record from the local database. </value>
        [DataMember(Name = "timeToLive", IsRequired = true, EmitDefaultValue = true)]
        public int TimeToLive { get; set; }

        /// <summary>
        /// LLDP parameters 
        /// </summary>
        /// <value>LLDP parameters </value>
        [DataMember(Name = "parameter", EmitDefaultValue = false)]
        public List<KeyAnyValue> Parameter { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LinkLayerDiscoveryProtocolInfo {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  ChassisId: ").Append(ChassisId).Append("\n");
            sb.Append("  PortId: ").Append(PortId).Append("\n");
            sb.Append("  TimeToLive: ").Append(TimeToLive).Append("\n");
            sb.Append("  Parameter: ").Append(Parameter).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
