/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// The parameters of *VirtualMachine.MigrateVM_Task*. 
    /// </summary>
    [DataContract(Name = "MigrateVMRequestType")]
    public partial class MigrateVMRequestType : IValidatableObject
    {

        /// <summary>
        /// The task priority (@see vim.VirtualMachine.MovePriority). 
        /// </summary>
        /// <value>The task priority (@see vim.VirtualMachine.MovePriority). </value>
        [DataMember(Name = "priority", IsRequired = true, EmitDefaultValue = true)]
        public VirtualMachineMovePriorityEnum Priority { get; set; }

        /// <summary>
        /// If specified, the virtual machine migrates only if its state matches the specified state. 
        /// </summary>
        /// <value>If specified, the virtual machine migrates only if its state matches the specified state. </value>
        [DataMember(Name = "state", EmitDefaultValue = false)]
        public VirtualMachinePowerStateEnum? State { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="MigrateVMRequestType" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MigrateVMRequestType() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MigrateVMRequestType" /> class.
        /// </summary>
        /// <param name="pool">The target resource pool for the virtual machine. If the pool parameter is left unset, the virtual machine&#39;s current pool is used as the target pool.  ***Required privileges:*** Resource.AssignVMToPool  Refers instance of *ResourcePool*. .</param>
        /// <param name="host">The target host to which the virtual machine is intended to migrate. The host parameter may be left unset if the compute resource associated with the target pool represents a stand-alone host or a DRS-enabled cluster. In the former case the stand-alone host is used as the target host. In the latter case, the DRS system selects an appropriate target host from the cluster.  Refers instance of *HostSystem*. .</param>
        /// <param name="priority">The task priority (@see vim.VirtualMachine.MovePriority).  (required).</param>
        /// <param name="state">If specified, the virtual machine migrates only if its state matches the specified state. .</param>
        public MigrateVMRequestType(ManagedObjectReference pool = default, ManagedObjectReference host = default, VirtualMachineMovePriorityEnum priority = default, VirtualMachinePowerStateEnum? state = default)
        {
            this.Priority = priority;
            this.Pool = pool;
            this.Host = host;
            this.State = state;
        }

        /// <summary>
        /// The target resource pool for the virtual machine. If the pool parameter is left unset, the virtual machine&#39;s current pool is used as the target pool.  ***Required privileges:*** Resource.AssignVMToPool  Refers instance of *ResourcePool*. 
        /// </summary>
        /// <value>The target resource pool for the virtual machine. If the pool parameter is left unset, the virtual machine&#39;s current pool is used as the target pool.  ***Required privileges:*** Resource.AssignVMToPool  Refers instance of *ResourcePool*. </value>
        [DataMember(Name = "pool", EmitDefaultValue = false)]
        public ManagedObjectReference Pool { get; set; }

        /// <summary>
        /// The target host to which the virtual machine is intended to migrate. The host parameter may be left unset if the compute resource associated with the target pool represents a stand-alone host or a DRS-enabled cluster. In the former case the stand-alone host is used as the target host. In the latter case, the DRS system selects an appropriate target host from the cluster.  Refers instance of *HostSystem*. 
        /// </summary>
        /// <value>The target host to which the virtual machine is intended to migrate. The host parameter may be left unset if the compute resource associated with the target pool represents a stand-alone host or a DRS-enabled cluster. In the former case the stand-alone host is used as the target host. In the latter case, the DRS system selects an appropriate target host from the cluster.  Refers instance of *HostSystem*. </value>
        [DataMember(Name = "host", EmitDefaultValue = false)]
        public ManagedObjectReference Host { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MigrateVMRequestType {\n");
            sb.Append("  Pool: ").Append(Pool).Append("\n");
            sb.Append("  Host: ").Append(Host).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
