/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// NetIpStackInfoDefaultRouter
    /// </summary>
    [DataContract(Name = "NetIpStackInfoDefaultRouter")]
    public partial class NetIpStackInfoDefaultRouter : DataObject, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NetIpStackInfoDefaultRouter" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected NetIpStackInfoDefaultRouter() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="NetIpStackInfoDefaultRouter" /> class.
        /// </summary>
        /// <param name="ipAddress">Unicast IP address of a next-hop router.  (required).</param>
        /// <param name="device">This value will contain the name of the interface as reported by the operating system.  (required).</param>
        /// <param name="lifetime">When this entry will no longer valid.  For IPv6 this value see For IPv6 RFC 2462 sections 4.2 and 6.3.4.  (required).</param>
        /// <param name="preference">Value of this entry compared to others that this IP stack uses when making selection to route traffic on the default route when there are multiple default routers.  Value must be one of *NetIpStackInfoPreference_enum*  (required).</param>
        /// <param name="typeName">The type discriminator. Refers to the name of a valid data object type.  (required) (default to &quot;NetIpStackInfoDefaultRouter&quot;).</param>
        public NetIpStackInfoDefaultRouter(string ipAddress = default, string device = default, DateTime lifetime = default, string preference = default, string typeName = @"NetIpStackInfoDefaultRouter") : base()
        {
            // to ensure "ipAddress" is required (not null)
            if (ipAddress == null)
            {
                throw new ArgumentNullException("ipAddress is a required property for NetIpStackInfoDefaultRouter and cannot be null");
            }
            this.IpAddress = ipAddress;
            // to ensure "device" is required (not null)
            if (device == null)
            {
                throw new ArgumentNullException("device is a required property for NetIpStackInfoDefaultRouter and cannot be null");
            }
            this.Device = device;
            this.Lifetime = lifetime;
            // to ensure "preference" is required (not null)
            if (preference == null)
            {
                throw new ArgumentNullException("preference is a required property for NetIpStackInfoDefaultRouter and cannot be null");
            }
            this.Preference = preference;
        }

        /// <summary>
        /// Unicast IP address of a next-hop router. 
        /// </summary>
        /// <value>Unicast IP address of a next-hop router. </value>
        [DataMember(Name = "ipAddress", IsRequired = true, EmitDefaultValue = true)]
        public string IpAddress { get; set; }

        /// <summary>
        /// This value will contain the name of the interface as reported by the operating system. 
        /// </summary>
        /// <value>This value will contain the name of the interface as reported by the operating system. </value>
        [DataMember(Name = "device", IsRequired = true, EmitDefaultValue = true)]
        public string Device { get; set; }

        /// <summary>
        /// When this entry will no longer valid.  For IPv6 this value see For IPv6 RFC 2462 sections 4.2 and 6.3.4. 
        /// </summary>
        /// <value>When this entry will no longer valid.  For IPv6 this value see For IPv6 RFC 2462 sections 4.2 and 6.3.4. </value>
        [DataMember(Name = "lifetime", IsRequired = true, EmitDefaultValue = true)]
        public DateTime Lifetime { get; set; }

        /// <summary>
        /// Value of this entry compared to others that this IP stack uses when making selection to route traffic on the default route when there are multiple default routers.  Value must be one of *NetIpStackInfoPreference_enum* 
        /// </summary>
        /// <value>Value of this entry compared to others that this IP stack uses when making selection to route traffic on the default route when there are multiple default routers.  Value must be one of *NetIpStackInfoPreference_enum* </value>
        [DataMember(Name = "preference", IsRequired = true, EmitDefaultValue = true)]
        public string Preference { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NetIpStackInfoDefaultRouter {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  IpAddress: ").Append(IpAddress).Append("\n");
            sb.Append("  Device: ").Append(Device).Append("\n");
            sb.Append("  Lifetime: ").Append(Lifetime).Append("\n");
            sb.Append("  Preference: ").Append(Preference).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
