/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// PowerOnFtSecondaryTimedout
    /// </summary>
    [DataContract(Name = "PowerOnFtSecondaryTimedout")]
    public partial class PowerOnFtSecondaryTimedout : Timedout, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PowerOnFtSecondaryTimedout" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PowerOnFtSecondaryTimedout() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PowerOnFtSecondaryTimedout" /> class.
        /// </summary>
        /// <param name="vm">The primary virtual machine corresponding to the secondary that is to be powered on  Refers instance of *VirtualMachine*.  (required).</param>
        /// <param name="vmName">The name of the primary virtual machine corresponding to the secondary that is to be powered on.  (required).</param>
        /// <param name="timeout">The time out value in seconds  (required).</param>
        /// <param name="typeName">The type discriminator. Refers to the name of a valid data object type.  (required) (default to &quot;PowerOnFtSecondaryTimedout&quot;).</param>
        /// <param name="faultCause">Fault which is the cause of this fault. .</param>
        /// <param name="faultMessage">Message which has details about the error Message can also contain a key to message catalog which can be used to generate better localized messages. .</param>
        public PowerOnFtSecondaryTimedout(ManagedObjectReference vm = default, string vmName = default, int timeout = default, string typeName = @"PowerOnFtSecondaryTimedout", MethodFault faultCause = default, List<LocalizableMessage> faultMessage = default) : base()
        {
            // to ensure "vm" is required (not null)
            if (vm == null)
            {
                throw new ArgumentNullException("vm is a required property for PowerOnFtSecondaryTimedout and cannot be null");
            }
            this.Vm = vm;
            // to ensure "vmName" is required (not null)
            if (vmName == null)
            {
                throw new ArgumentNullException("vmName is a required property for PowerOnFtSecondaryTimedout and cannot be null");
            }
            this.VmName = vmName;
            this.Timeout = timeout;
        }

        /// <summary>
        /// The primary virtual machine corresponding to the secondary that is to be powered on  Refers instance of *VirtualMachine*. 
        /// </summary>
        /// <value>The primary virtual machine corresponding to the secondary that is to be powered on  Refers instance of *VirtualMachine*. </value>
        [DataMember(Name = "vm", IsRequired = true, EmitDefaultValue = true)]
        public ManagedObjectReference Vm { get; set; }

        /// <summary>
        /// The name of the primary virtual machine corresponding to the secondary that is to be powered on. 
        /// </summary>
        /// <value>The name of the primary virtual machine corresponding to the secondary that is to be powered on. </value>
        [DataMember(Name = "vmName", IsRequired = true, EmitDefaultValue = true)]
        public string VmName { get; set; }

        /// <summary>
        /// The time out value in seconds 
        /// </summary>
        /// <value>The time out value in seconds </value>
        [DataMember(Name = "timeout", IsRequired = true, EmitDefaultValue = true)]
        public int Timeout { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PowerOnFtSecondaryTimedout {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Vm: ").Append(Vm).Append("\n");
            sb.Append("  VmName: ").Append(VmName).Append("\n");
            sb.Append("  Timeout: ").Append(Timeout).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
