/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// ProfileParameterMetadata
    /// </summary>
    [DataContract(Name = "ProfileParameterMetadata")]
    public partial class ProfileParameterMetadata : DataObject, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProfileParameterMetadata" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ProfileParameterMetadata() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProfileParameterMetadata" /> class.
        /// </summary>
        /// <param name="id">Identifier for the parameter.  (required).</param>
        /// <param name="type">Type of the parameter.  (required).</param>
        /// <param name="optional">Whether the parameter is optional.  (required).</param>
        /// <param name="defaultValue">Default value that can be used for the parameter. .</param>
        /// <param name="hidden">Whether the parameter will not be displayed in UI. .</param>
        /// <param name="securitySensitive">Whether the parameter is security sensitive. .</param>
        /// <param name="readOnly">Indicates that the parameter value is read-only. .</param>
        /// <param name="parameterRelations">Relations with other profile or parameters. .</param>
        /// <param name="typeName">The type discriminator. Refers to the name of a valid data object type.  (required) (default to &quot;ProfileParameterMetadata&quot;).</param>
        public ProfileParameterMetadata(ExtendedElementDescription id = default, string type = default, bool optional = default, Any defaultValue = default, bool hidden = default, bool securitySensitive = default, bool readOnly = default, List<ProfileParameterMetadataParameterRelationMetadata> parameterRelations = default, string typeName = @"ProfileParameterMetadata") : base()
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for ProfileParameterMetadata and cannot be null");
            }
            this.Id = id;
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for ProfileParameterMetadata and cannot be null");
            }
            this.Type = type;
            this.Optional = optional;
            this.DefaultValue = defaultValue;
            this.Hidden = hidden;
            this.SecuritySensitive = securitySensitive;
            this.ReadOnly = readOnly;
            this.ParameterRelations = parameterRelations;
        }

        /// <summary>
        /// Identifier for the parameter. 
        /// </summary>
        /// <value>Identifier for the parameter. </value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public ExtendedElementDescription Id { get; set; }

        /// <summary>
        /// Type of the parameter. 
        /// </summary>
        /// <value>Type of the parameter. </value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Whether the parameter is optional. 
        /// </summary>
        /// <value>Whether the parameter is optional. </value>
        [DataMember(Name = "optional", IsRequired = true, EmitDefaultValue = true)]
        public bool Optional { get; set; }

        /// <summary>
        /// Default value that can be used for the parameter. 
        /// </summary>
        /// <value>Default value that can be used for the parameter. </value>
        [DataMember(Name = "defaultValue", EmitDefaultValue = false)]
        public Any DefaultValue { get; set; }

        /// <summary>
        /// Whether the parameter will not be displayed in UI. 
        /// </summary>
        /// <value>Whether the parameter will not be displayed in UI. </value>
        [DataMember(Name = "hidden", EmitDefaultValue = true)]
        public bool Hidden { get; set; }

        /// <summary>
        /// Whether the parameter is security sensitive. 
        /// </summary>
        /// <value>Whether the parameter is security sensitive. </value>
        [DataMember(Name = "securitySensitive", EmitDefaultValue = true)]
        public bool SecuritySensitive { get; set; }

        /// <summary>
        /// Indicates that the parameter value is read-only. 
        /// </summary>
        /// <value>Indicates that the parameter value is read-only. </value>
        [DataMember(Name = "readOnly", EmitDefaultValue = true)]
        public bool ReadOnly { get; set; }

        /// <summary>
        /// Relations with other profile or parameters. 
        /// </summary>
        /// <value>Relations with other profile or parameters. </value>
        [DataMember(Name = "parameterRelations", EmitDefaultValue = false)]
        public List<ProfileParameterMetadataParameterRelationMetadata> ParameterRelations { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProfileParameterMetadata {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Optional: ").Append(Optional).Append("\n");
            sb.Append("  DefaultValue: ").Append(DefaultValue).Append("\n");
            sb.Append("  Hidden: ").Append(Hidden).Append("\n");
            sb.Append("  SecuritySensitive: ").Append(SecuritySensitive).Append("\n");
            sb.Append("  ReadOnly: ").Append(ReadOnly).Append("\n");
            sb.Append("  ParameterRelations: ").Append(ParameterRelations).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
