/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// The parameters of *HostDatastoreSystem.QueryVmfsDatastoreExtendOptions*. 
    /// </summary>
    [DataContract(Name = "QueryVmfsDatastoreExtendOptionsRequestType")]
    public partial class QueryVmfsDatastoreExtendOptionsRequestType : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryVmfsDatastoreExtendOptionsRequestType" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected QueryVmfsDatastoreExtendOptionsRequestType() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryVmfsDatastoreExtendOptionsRequestType" /> class.
        /// </summary>
        /// <param name="datastore">The datastore to be extended.  Refers instance of *Datastore*.  (required).</param>
        /// <param name="devicePath">The devicePath of the disk on which datastore extension options are generated.  (required).</param>
        /// <param name="suppressExpandCandidates">Indicates whether to exclude options that can be used for extent expansion also. Free space can be used for adding an extent or expanding an existing extent. If this parameter is set to true, the list of options returned will not include free space that can be used for expansion. .</param>
        public QueryVmfsDatastoreExtendOptionsRequestType(ManagedObjectReference datastore = default, string devicePath = default, bool suppressExpandCandidates = default)
        {
            // to ensure "datastore" is required (not null)
            if (datastore == null)
            {
                throw new ArgumentNullException("datastore is a required property for QueryVmfsDatastoreExtendOptionsRequestType and cannot be null");
            }
            this.Datastore = datastore;
            // to ensure "devicePath" is required (not null)
            if (devicePath == null)
            {
                throw new ArgumentNullException("devicePath is a required property for QueryVmfsDatastoreExtendOptionsRequestType and cannot be null");
            }
            this.DevicePath = devicePath;
            this.SuppressExpandCandidates = suppressExpandCandidates;
        }

        /// <summary>
        /// The datastore to be extended.  Refers instance of *Datastore*. 
        /// </summary>
        /// <value>The datastore to be extended.  Refers instance of *Datastore*. </value>
        [DataMember(Name = "datastore", IsRequired = true, EmitDefaultValue = true)]
        public ManagedObjectReference Datastore { get; set; }

        /// <summary>
        /// The devicePath of the disk on which datastore extension options are generated. 
        /// </summary>
        /// <value>The devicePath of the disk on which datastore extension options are generated. </value>
        [DataMember(Name = "devicePath", IsRequired = true, EmitDefaultValue = true)]
        public string DevicePath { get; set; }

        /// <summary>
        /// Indicates whether to exclude options that can be used for extent expansion also. Free space can be used for adding an extent or expanding an existing extent. If this parameter is set to true, the list of options returned will not include free space that can be used for expansion. 
        /// </summary>
        /// <value>Indicates whether to exclude options that can be used for extent expansion also. Free space can be used for adding an extent or expanding an existing extent. If this parameter is set to true, the list of options returned will not include free space that can be used for expansion. </value>
        [DataMember(Name = "suppressExpandCandidates", EmitDefaultValue = true)]
        public bool SuppressExpandCandidates { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QueryVmfsDatastoreExtendOptionsRequestType {\n");
            sb.Append("  Datastore: ").Append(Datastore).Append("\n");
            sb.Append("  DevicePath: ").Append(DevicePath).Append("\n");
            sb.Append("  SuppressExpandCandidates: ").Append(SuppressExpandCandidates).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
