/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// The parameters of *HostVsanInternalSystem.QueryVsanObjectUuidsByFilter*. 
    /// </summary>
    [DataContract(Name = "QueryVsanObjectUuidsByFilterRequestType")]
    public partial class QueryVsanObjectUuidsByFilterRequestType : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryVsanObjectUuidsByFilterRequestType" /> class.
        /// </summary>
        /// <param name="uuids">Objects UUID will be checked against the filtering conditions. .</param>
        /// <param name="limit">To limit the size of the result set. .</param>
        /// <param name="varVersion">Filtering condition 1: object version. .</param>
        public QueryVsanObjectUuidsByFilterRequestType(List<string> uuids = default, int limit = default, int varVersion = default)
        {
            this.Uuids = uuids;
            this.Limit = limit;
            this.VarVersion = varVersion;
        }

        /// <summary>
        /// Objects UUID will be checked against the filtering conditions. 
        /// </summary>
        /// <value>Objects UUID will be checked against the filtering conditions. </value>
        [DataMember(Name = "uuids", EmitDefaultValue = false)]
        public List<string> Uuids { get; set; }

        /// <summary>
        /// To limit the size of the result set. 
        /// </summary>
        /// <value>To limit the size of the result set. </value>
        [DataMember(Name = "limit", EmitDefaultValue = false)]
        public int Limit { get; set; }

        /// <summary>
        /// Filtering condition 1: object version. 
        /// </summary>
        /// <value>Filtering condition 1: object version. </value>
        [DataMember(Name = "version", EmitDefaultValue = false)]
        public int VarVersion { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QueryVsanObjectUuidsByFilterRequestType {\n");
            sb.Append("  Uuids: ").Append(Uuids).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
