/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// ReadOnlyDisksWithLegacyDestination
    /// </summary>
    [DataContract(Name = "ReadOnlyDisksWithLegacyDestination")]
    public partial class ReadOnlyDisksWithLegacyDestination : MigrationFault, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReadOnlyDisksWithLegacyDestination" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ReadOnlyDisksWithLegacyDestination() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReadOnlyDisksWithLegacyDestination" /> class.
        /// </summary>
        /// <param name="roDiskCount">The number of read-only disks in use.  (required).</param>
        /// <param name="timeoutDanger">Whether this number of disks will cause a timeout failure.  (required).</param>
        /// <param name="typeName">The type discriminator. Refers to the name of a valid data object type.  (required) (default to &quot;ReadOnlyDisksWithLegacyDestination&quot;).</param>
        /// <param name="faultCause">Fault which is the cause of this fault. .</param>
        /// <param name="faultMessage">Message which has details about the error Message can also contain a key to message catalog which can be used to generate better localized messages. .</param>
        public ReadOnlyDisksWithLegacyDestination(int roDiskCount = default, bool timeoutDanger = default, string typeName = @"ReadOnlyDisksWithLegacyDestination", MethodFault faultCause = default, List<LocalizableMessage> faultMessage = default) : base()
        {
            this.RoDiskCount = roDiskCount;
            this.TimeoutDanger = timeoutDanger;
        }

        /// <summary>
        /// The number of read-only disks in use. 
        /// </summary>
        /// <value>The number of read-only disks in use. </value>
        [DataMember(Name = "roDiskCount", IsRequired = true, EmitDefaultValue = true)]
        public int RoDiskCount { get; set; }

        /// <summary>
        /// Whether this number of disks will cause a timeout failure. 
        /// </summary>
        /// <value>Whether this number of disks will cause a timeout failure. </value>
        [DataMember(Name = "timeoutDanger", IsRequired = true, EmitDefaultValue = true)]
        public bool TimeoutDanger { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReadOnlyDisksWithLegacyDestination {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  RoDiskCount: ").Append(RoDiskCount).Append("\n");
            sb.Append("  TimeoutDanger: ").Append(TimeoutDanger).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
