/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// The parameters of *AuthorizationManager.RemoveEntityPermission*. 
    /// </summary>
    [DataContract(Name = "RemoveEntityPermissionRequestType")]
    public partial class RemoveEntityPermissionRequestType : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RemoveEntityPermissionRequestType" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RemoveEntityPermissionRequestType() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RemoveEntityPermissionRequestType" /> class.
        /// </summary>
        /// <param name="entity">Entity on which a permission is removed.  ***Required privileges:*** Authorization.ModifyPermissions  Refers instance of *ManagedEntity*.  (required).</param>
        /// <param name="user">User or group for which the permission is defined.  (required).</param>
        /// <param name="isGroup">True, if user refers to a group name; false, for a user name.  (required).</param>
        public RemoveEntityPermissionRequestType(ManagedObjectReference entity = default, string user = default, bool isGroup = default)
        {
            // to ensure "entity" is required (not null)
            if (entity == null)
            {
                throw new ArgumentNullException("entity is a required property for RemoveEntityPermissionRequestType and cannot be null");
            }
            this.Entity = entity;
            // to ensure "user" is required (not null)
            if (user == null)
            {
                throw new ArgumentNullException("user is a required property for RemoveEntityPermissionRequestType and cannot be null");
            }
            this.User = user;
            this.IsGroup = isGroup;
        }

        /// <summary>
        /// Entity on which a permission is removed.  ***Required privileges:*** Authorization.ModifyPermissions  Refers instance of *ManagedEntity*. 
        /// </summary>
        /// <value>Entity on which a permission is removed.  ***Required privileges:*** Authorization.ModifyPermissions  Refers instance of *ManagedEntity*. </value>
        [DataMember(Name = "entity", IsRequired = true, EmitDefaultValue = true)]
        public ManagedObjectReference Entity { get; set; }

        /// <summary>
        /// User or group for which the permission is defined. 
        /// </summary>
        /// <value>User or group for which the permission is defined. </value>
        [DataMember(Name = "user", IsRequired = true, EmitDefaultValue = true)]
        public string User { get; set; }

        /// <summary>
        /// True, if user refers to a group name; false, for a user name. 
        /// </summary>
        /// <value>True, if user refers to a group name; false, for a user name. </value>
        [DataMember(Name = "isGroup", IsRequired = true, EmitDefaultValue = true)]
        public bool IsGroup { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RemoveEntityPermissionRequestType {\n");
            sb.Append("  Entity: ").Append(Entity).Append("\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("  IsGroup: ").Append(IsGroup).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
