/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// The parameters of *ExtensionManager.SetServiceAccount*.  ***Since:*** vSphere API Release 8.0.2.0 
    /// </summary>
    [DataContract(Name = "SetServiceAccountRequestType")]
    public partial class SetServiceAccountRequestType : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SetServiceAccountRequestType" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SetServiceAccountRequestType() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SetServiceAccountRequestType" /> class.
        /// </summary>
        /// <param name="extensionKey">Key of extension to update.  (required).</param>
        /// <param name="serviceAccount">account name qualified with SSO domain.  (required).</param>
        public SetServiceAccountRequestType(string extensionKey = default, string serviceAccount = default)
        {
            // to ensure "extensionKey" is required (not null)
            if (extensionKey == null)
            {
                throw new ArgumentNullException("extensionKey is a required property for SetServiceAccountRequestType and cannot be null");
            }
            this.ExtensionKey = extensionKey;
            // to ensure "serviceAccount" is required (not null)
            if (serviceAccount == null)
            {
                throw new ArgumentNullException("serviceAccount is a required property for SetServiceAccountRequestType and cannot be null");
            }
            this.ServiceAccount = serviceAccount;
        }

        /// <summary>
        /// Key of extension to update. 
        /// </summary>
        /// <value>Key of extension to update. </value>
        [DataMember(Name = "extensionKey", IsRequired = true, EmitDefaultValue = true)]
        public string ExtensionKey { get; set; }

        /// <summary>
        /// account name qualified with SSO domain. 
        /// </summary>
        /// <value>account name qualified with SSO domain. </value>
        [DataMember(Name = "serviceAccount", IsRequired = true, EmitDefaultValue = true)]
        public string ServiceAccount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SetServiceAccountRequestType {\n");
            sb.Append("  ExtensionKey: ").Append(ExtensionKey).Append("\n");
            sb.Append("  ServiceAccount: ").Append(ServiceAccount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
