/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// StorageResourceManagerStorageProfileStatistics
    /// </summary>
    [DataContract(Name = "StorageResourceManagerStorageProfileStatistics")]
    public partial class StorageResourceManagerStorageProfileStatistics : DataObject, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StorageResourceManagerStorageProfileStatistics" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected StorageResourceManagerStorageProfileStatistics() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="StorageResourceManagerStorageProfileStatistics" /> class.
        /// </summary>
        /// <param name="profileId">Profile identifier for the reported statistics  (required).</param>
        /// <param name="totalSpaceMB">The aggregate storage capacity available for a given storage capability profile.  The capacity is reported in Megabytes.  (required).</param>
        /// <param name="usedSpaceMB">The aggregate used storage capacity by a given storage capability profile The used space is reported in Megabytes  (required).</param>
        /// <param name="typeName">The type discriminator. Refers to the name of a valid data object type.  (required) (default to &quot;StorageResourceManagerStorageProfileStatistics&quot;).</param>
        public StorageResourceManagerStorageProfileStatistics(string profileId = default, long totalSpaceMB = default, long usedSpaceMB = default, string typeName = @"StorageResourceManagerStorageProfileStatistics") : base()
        {
            // to ensure "profileId" is required (not null)
            if (profileId == null)
            {
                throw new ArgumentNullException("profileId is a required property for StorageResourceManagerStorageProfileStatistics and cannot be null");
            }
            this.ProfileId = profileId;
            this.TotalSpaceMB = totalSpaceMB;
            this.UsedSpaceMB = usedSpaceMB;
        }

        /// <summary>
        /// Profile identifier for the reported statistics 
        /// </summary>
        /// <value>Profile identifier for the reported statistics </value>
        [DataMember(Name = "profileId", IsRequired = true, EmitDefaultValue = true)]
        public string ProfileId { get; set; }

        /// <summary>
        /// The aggregate storage capacity available for a given storage capability profile.  The capacity is reported in Megabytes. 
        /// </summary>
        /// <value>The aggregate storage capacity available for a given storage capability profile.  The capacity is reported in Megabytes. </value>
        [DataMember(Name = "totalSpaceMB", IsRequired = true, EmitDefaultValue = true)]
        public long TotalSpaceMB { get; set; }

        /// <summary>
        /// The aggregate used storage capacity by a given storage capability profile The used space is reported in Megabytes 
        /// </summary>
        /// <value>The aggregate used storage capacity by a given storage capability profile The used space is reported in Megabytes </value>
        [DataMember(Name = "usedSpaceMB", IsRequired = true, EmitDefaultValue = true)]
        public long UsedSpaceMB { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StorageResourceManagerStorageProfileStatistics {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  ProfileId: ").Append(ProfileId).Append("\n");
            sb.Append("  TotalSpaceMB: ").Append(TotalSpaceMB).Append("\n");
            sb.Append("  UsedSpaceMB: ").Append(UsedSpaceMB).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
