/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// ToolsConfigInfoToolsLastInstallInfo
    /// </summary>
    [DataContract(Name = "ToolsConfigInfoToolsLastInstallInfo")]
    public partial class ToolsConfigInfoToolsLastInstallInfo : DataObject, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsConfigInfoToolsLastInstallInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ToolsConfigInfoToolsLastInstallInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsConfigInfoToolsLastInstallInfo" /> class.
        /// </summary>
        /// <param name="counter">Number of attempts that have been made to upgrade the version of tools installed on this virtual machine.  (required).</param>
        /// <param name="fault">Error that happened, if any, during last attempt to upgrade tools. .</param>
        /// <param name="typeName">The type discriminator. Refers to the name of a valid data object type.  (required) (default to &quot;ToolsConfigInfoToolsLastInstallInfo&quot;).</param>
        public ToolsConfigInfoToolsLastInstallInfo(int counter = default, MethodFault fault = default, string typeName = @"ToolsConfigInfoToolsLastInstallInfo") : base()
        {
            this.Counter = counter;
            this.Fault = fault;
        }

        /// <summary>
        /// Number of attempts that have been made to upgrade the version of tools installed on this virtual machine. 
        /// </summary>
        /// <value>Number of attempts that have been made to upgrade the version of tools installed on this virtual machine. </value>
        [DataMember(Name = "counter", IsRequired = true, EmitDefaultValue = true)]
        public int Counter { get; set; }

        /// <summary>
        /// Error that happened, if any, during last attempt to upgrade tools. 
        /// </summary>
        /// <value>Error that happened, if any, during last attempt to upgrade tools. </value>
        [DataMember(Name = "fault", EmitDefaultValue = false)]
        public MethodFault Fault { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ToolsConfigInfoToolsLastInstallInfo {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Counter: ").Append(Counter).Append("\n");
            sb.Append("  Fault: ").Append(Fault).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
