/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// The parameters of *HostStorageSystem.UnmapVmfsVolumeEx_Task*. 
    /// </summary>
    [DataContract(Name = "UnmapVmfsVolumeExRequestType")]
    public partial class UnmapVmfsVolumeExRequestType : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UnmapVmfsVolumeExRequestType" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UnmapVmfsVolumeExRequestType() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UnmapVmfsVolumeExRequestType" /> class.
        /// </summary>
        /// <param name="vmfsUuid">each element specifies the UUID of a VMFS volume to be unmapped.  (required).</param>
        public UnmapVmfsVolumeExRequestType(List<string> vmfsUuid = default)
        {
            // to ensure "vmfsUuid" is required (not null)
            if (vmfsUuid == null)
            {
                throw new ArgumentNullException("vmfsUuid is a required property for UnmapVmfsVolumeExRequestType and cannot be null");
            }
            this.VmfsUuid = vmfsUuid;
        }

        /// <summary>
        /// each element specifies the UUID of a VMFS volume to be unmapped. 
        /// </summary>
        /// <value>each element specifies the UUID of a VMFS volume to be unmapped. </value>
        [DataMember(Name = "vmfsUuid", IsRequired = true, EmitDefaultValue = true)]
        public List<string> VmfsUuid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UnmapVmfsVolumeExRequestType {\n");
            sb.Append("  VmfsUuid: ").Append(VmfsUuid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
