/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// The lifecycle cluster types required by lifecycle manager/vLCM.  Possible values: - &#x60;single&#x60;: Single site cluster. - &#x60;stretched&#x60;: Stretched cluster. - &#x60;metadata&#x60;: Metadata mode cluster. - &#x60;LifecycleClusterType_unknown&#x60;: Unknown cluster type. 
    /// </summary>
    /// <value>The lifecycle cluster types required by lifecycle manager/vLCM.  Possible values: - &#x60;single&#x60;: Single site cluster. - &#x60;stretched&#x60;: Stretched cluster. - &#x60;metadata&#x60;: Metadata mode cluster. - &#x60;LifecycleClusterType_unknown&#x60;: Unknown cluster type. </value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VimVsanLifecycleClusterTypeEnum
    {
        /// <summary>
        /// Enum Single for value: single
        /// </summary>
        [EnumMember(Value = "single")]
        Single = 1,

        /// <summary>
        /// Enum Stretched for value: stretched
        /// </summary>
        [EnumMember(Value = "stretched")]
        Stretched = 2,

        /// <summary>
        /// Enum Metadata for value: metadata
        /// </summary>
        [EnumMember(Value = "metadata")]
        Metadata = 3,

        /// <summary>
        /// Enum LifecycleClusterTypeUnknown for value: LifecycleClusterType_unknown
        /// </summary>
        [EnumMember(Value = "LifecycleClusterType_unknown")]
        LifecycleClusterTypeUnknown = 4
    }

}
