/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// This indicates the precheck type when mounting a remote vSAN datastore and enabling remote DIT at the same time.  Possible values: - &#x60;serverClusterConsistency&#x60;: Check whether the cluster specified by remote DIT config backs up the remote datastore. - &#x60;clientRemoteDITCapability&#x60;: Check whether the client cluster has remote DIT capability. - &#x60;serverRemoteDITCapability&#x60;: Check whether the server cluster has remote DIT capability. - &#x60;rekeyIntervalValid&#x60;: Check whether the rekey interval is valid - &#x60;datastoreBelongToServerCluster&#x60;: Check whether the datastore being mounted belongs to the server cluster - &#x60;remoteDITInfoRetrieval&#x60;: Check whether remote DIT related datastore infomation can be retrieved. - &#x60;remoteDITVersionCheck&#x60;: Check whether the existing client cluster versions meet the minimum   requirement for remote DIT. 
    /// </summary>
    /// <value>This indicates the precheck type when mounting a remote vSAN datastore and enabling remote DIT at the same time.  Possible values: - &#x60;serverClusterConsistency&#x60;: Check whether the cluster specified by remote DIT config backs up the remote datastore. - &#x60;clientRemoteDITCapability&#x60;: Check whether the client cluster has remote DIT capability. - &#x60;serverRemoteDITCapability&#x60;: Check whether the server cluster has remote DIT capability. - &#x60;rekeyIntervalValid&#x60;: Check whether the rekey interval is valid - &#x60;datastoreBelongToServerCluster&#x60;: Check whether the datastore being mounted belongs to the server cluster - &#x60;remoteDITInfoRetrieval&#x60;: Check whether remote DIT related datastore infomation can be retrieved. - &#x60;remoteDITVersionCheck&#x60;: Check whether the existing client cluster versions meet the minimum   requirement for remote DIT. </value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VimVsanMountPrecheckTypeDITEnum
    {
        /// <summary>
        /// Enum ServerClusterConsistency for value: serverClusterConsistency
        /// </summary>
        [EnumMember(Value = "serverClusterConsistency")]
        ServerClusterConsistency = 1,

        /// <summary>
        /// Enum ClientRemoteDITCapability for value: clientRemoteDITCapability
        /// </summary>
        [EnumMember(Value = "clientRemoteDITCapability")]
        ClientRemoteDITCapability = 2,

        /// <summary>
        /// Enum ServerRemoteDITCapability for value: serverRemoteDITCapability
        /// </summary>
        [EnumMember(Value = "serverRemoteDITCapability")]
        ServerRemoteDITCapability = 3,

        /// <summary>
        /// Enum RekeyIntervalValid for value: rekeyIntervalValid
        /// </summary>
        [EnumMember(Value = "rekeyIntervalValid")]
        RekeyIntervalValid = 4,

        /// <summary>
        /// Enum DatastoreBelongToServerCluster for value: datastoreBelongToServerCluster
        /// </summary>
        [EnumMember(Value = "datastoreBelongToServerCluster")]
        DatastoreBelongToServerCluster = 5,

        /// <summary>
        /// Enum RemoteDITInfoRetrieval for value: remoteDITInfoRetrieval
        /// </summary>
        [EnumMember(Value = "remoteDITInfoRetrieval")]
        RemoteDITInfoRetrieval = 6,

        /// <summary>
        /// Enum RemoteDITVersionCheck for value: remoteDITVersionCheck
        /// </summary>
        [EnumMember(Value = "remoteDITVersionCheck")]
        RemoteDITVersionCheck = 7
    }

}
