/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// VirtualDiskDeltaDiskFormatsSupported
    /// </summary>
    [DataContract(Name = "VirtualDiskDeltaDiskFormatsSupported")]
    public partial class VirtualDiskDeltaDiskFormatsSupported : DataObject, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VirtualDiskDeltaDiskFormatsSupported" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VirtualDiskDeltaDiskFormatsSupported() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VirtualDiskDeltaDiskFormatsSupported" /> class.
        /// </summary>
        /// <param name="datastoreType">Datastore type name  (required).</param>
        /// <param name="deltaDiskFormat">Delta disk formats supported.  Valid values are: - *redoLogFormat* - *nativeFormat*  (required).</param>
        /// <param name="typeName">The type discriminator. Refers to the name of a valid data object type.  (required) (default to &quot;VirtualDiskDeltaDiskFormatsSupported&quot;).</param>
        public VirtualDiskDeltaDiskFormatsSupported(string datastoreType = default, ChoiceOption deltaDiskFormat = default, string typeName = @"VirtualDiskDeltaDiskFormatsSupported") : base()
        {
            // to ensure "datastoreType" is required (not null)
            if (datastoreType == null)
            {
                throw new ArgumentNullException("datastoreType is a required property for VirtualDiskDeltaDiskFormatsSupported and cannot be null");
            }
            this.DatastoreType = datastoreType;
            // to ensure "deltaDiskFormat" is required (not null)
            if (deltaDiskFormat == null)
            {
                throw new ArgumentNullException("deltaDiskFormat is a required property for VirtualDiskDeltaDiskFormatsSupported and cannot be null");
            }
            this.DeltaDiskFormat = deltaDiskFormat;
        }

        /// <summary>
        /// Datastore type name 
        /// </summary>
        /// <value>Datastore type name </value>
        [DataMember(Name = "datastoreType", IsRequired = true, EmitDefaultValue = true)]
        public string DatastoreType { get; set; }

        /// <summary>
        /// Delta disk formats supported.  Valid values are: - *redoLogFormat* - *nativeFormat* 
        /// </summary>
        /// <value>Delta disk formats supported.  Valid values are: - *redoLogFormat* - *nativeFormat* </value>
        [DataMember(Name = "deltaDiskFormat", IsRequired = true, EmitDefaultValue = true)]
        public ChoiceOption DeltaDiskFormat { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VirtualDiskDeltaDiskFormatsSupported {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  DatastoreType: ").Append(DatastoreType).Append("\n");
            sb.Append("  DeltaDiskFormat: ").Append(DeltaDiskFormat).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
