/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// VirtualDeviceConfigSpec
    /// </summary>
    [DataContract(Name = "VirtualDeviceConfigSpec")]
    [JsonConverter(typeof(JsonSubtypes), "TypeName")]
    [JsonSubtypes.KnownSubType(typeof(ArrayOfURI), "ArrayOfAnyURI")]
    [JsonSubtypes.KnownSubType(typeof(ArrayOfBinary), "ArrayOfBase64Binary")]
    [JsonSubtypes.KnownSubType(typeof(ArrayOfPropPath), "ArrayOfPropertyPath")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveMethodName), "MethodName")]
    [JsonSubtypes.KnownSubType(typeof(PrimitivePropPath), "PropertyPath")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveTypeName), "TypeName")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveURI), "anyURI")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveBinary), "base64Binary")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveBoolean), "boolean")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveByte), "byte")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveDateTime), "dateTime")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveDouble), "double")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveFloat), "float")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveInt), "int")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveLong), "long")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveShort), "short")]
    [JsonSubtypes.KnownSubType(typeof(PrimitiveString), "string")]
    [JsonSubtypes.KnownSubType(typeof(VirtualDiskConfigSpec), "VirtualDiskConfigSpec")]
    public partial class VirtualDeviceConfigSpec : DataObject, IValidatableObject
    {

        /// <summary>
        /// Type of operation being performed on the specified virtual device.  If no operation is specified, the spec. is ignored. 
        /// </summary>
        /// <value>Type of operation being performed on the specified virtual device.  If no operation is specified, the spec. is ignored. </value>
        [DataMember(Name = "operation", EmitDefaultValue = false)]
        public VirtualDeviceConfigSpecOperationEnum? Operation { get; set; }

        /// <summary>
        /// Type of operation being performed on the backing of the specified virtual device.  If no file operation is specified in the VirtualDeviceSpec, then any backing filenames in the *VirtualDevice* must refer to files that already exist. The \&quot;replace\&quot; and \&quot;delete\&quot; values for this property are only applicable to virtual disk backing files. 
        /// </summary>
        /// <value>Type of operation being performed on the backing of the specified virtual device.  If no file operation is specified in the VirtualDeviceSpec, then any backing filenames in the *VirtualDevice* must refer to files that already exist. The \&quot;replace\&quot; and \&quot;delete\&quot; values for this property are only applicable to virtual disk backing files. </value>
        [DataMember(Name = "fileOperation", EmitDefaultValue = false)]
        public VirtualDeviceConfigSpecFileOperationEnum? FileOperation { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="VirtualDeviceConfigSpec" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VirtualDeviceConfigSpec() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VirtualDeviceConfigSpec" /> class.
        /// </summary>
        /// <param name="operation">Type of operation being performed on the specified virtual device.  If no operation is specified, the spec. is ignored. .</param>
        /// <param name="fileOperation">Type of operation being performed on the backing of the specified virtual device.  If no file operation is specified in the VirtualDeviceSpec, then any backing filenames in the *VirtualDevice* must refer to files that already exist. The \&quot;replace\&quot; and \&quot;delete\&quot; values for this property are only applicable to virtual disk backing files. .</param>
        /// <param name="device">Device specification, with all necessary properties set.  (required).</param>
        /// <param name="profile">Virtual Device Profile requirement.  Profiles are solution specifics. Storage Profile Based Management(SPBM) is a vSphere server extension. The API users who want to provision VMs using Storage Profiles, need to interact with SPBM service. This is an optional parameter and if user doesn&#39;t specify profile, the default behavior will apply. .</param>
        /// <param name="backing">BackingInfo configuration options.  Each BackingSpec corresponds to a BackingInfo object. The member *VirtualDeviceConfigSpec.backing* refers to the *VirtualDeviceConfigSpec.device*.*VirtualDevice.backing*. .</param>
        /// <param name="filterSpec">List of independent filters *VirtualMachineIndependentFilterSpec* to configure on the virtual device.  ***Since:*** vSphere API Release 7.0.2.1 .</param>
        /// <param name="changeMode">The change mode of the device.  The values of the mode will be one of *VirtualDeviceConfigSpecChangeMode_enum* enumerations. On unset, default to &#39;fail&#39;.  ***Since:*** vSphere API Release 8.0.0.1 .</param>
        /// <param name="typeName">The type discriminator. Refers to the name of a valid data object type.  (required) (default to &quot;VirtualDeviceConfigSpec&quot;).</param>
        public VirtualDeviceConfigSpec(VirtualDeviceConfigSpecOperationEnum? operation = default, VirtualDeviceConfigSpecFileOperationEnum? fileOperation = default, VirtualDevice device = default, List<VirtualMachineProfileSpec> profile = default, VirtualDeviceConfigSpecBackingSpec backing = default, List<VirtualMachineBaseIndependentFilterSpec> filterSpec = default, string changeMode = default, string typeName = @"VirtualDeviceConfigSpec") : base()
        {
            // to ensure "device" is required (not null)
            if (device == null)
            {
                throw new ArgumentNullException("device is a required property for VirtualDeviceConfigSpec and cannot be null");
            }
            this.Device = device;
            this.Operation = operation;
            this.FileOperation = fileOperation;
            this.Profile = profile;
            this.Backing = backing;
            this.FilterSpec = filterSpec;
            this.ChangeMode = changeMode;
        }

        /// <summary>
        /// Device specification, with all necessary properties set. 
        /// </summary>
        /// <value>Device specification, with all necessary properties set. </value>
        [DataMember(Name = "device", IsRequired = true, EmitDefaultValue = true)]
        public VirtualDevice Device { get; set; }

        /// <summary>
        /// Virtual Device Profile requirement.  Profiles are solution specifics. Storage Profile Based Management(SPBM) is a vSphere server extension. The API users who want to provision VMs using Storage Profiles, need to interact with SPBM service. This is an optional parameter and if user doesn&#39;t specify profile, the default behavior will apply. 
        /// </summary>
        /// <value>Virtual Device Profile requirement.  Profiles are solution specifics. Storage Profile Based Management(SPBM) is a vSphere server extension. The API users who want to provision VMs using Storage Profiles, need to interact with SPBM service. This is an optional parameter and if user doesn&#39;t specify profile, the default behavior will apply. </value>
        [DataMember(Name = "profile", EmitDefaultValue = false)]
        public List<VirtualMachineProfileSpec> Profile { get; set; }

        /// <summary>
        /// BackingInfo configuration options.  Each BackingSpec corresponds to a BackingInfo object. The member *VirtualDeviceConfigSpec.backing* refers to the *VirtualDeviceConfigSpec.device*.*VirtualDevice.backing*. 
        /// </summary>
        /// <value>BackingInfo configuration options.  Each BackingSpec corresponds to a BackingInfo object. The member *VirtualDeviceConfigSpec.backing* refers to the *VirtualDeviceConfigSpec.device*.*VirtualDevice.backing*. </value>
        [DataMember(Name = "backing", EmitDefaultValue = false)]
        public VirtualDeviceConfigSpecBackingSpec Backing { get; set; }

        /// <summary>
        /// List of independent filters *VirtualMachineIndependentFilterSpec* to configure on the virtual device.  ***Since:*** vSphere API Release 7.0.2.1 
        /// </summary>
        /// <value>List of independent filters *VirtualMachineIndependentFilterSpec* to configure on the virtual device.  ***Since:*** vSphere API Release 7.0.2.1 </value>
        [DataMember(Name = "filterSpec", EmitDefaultValue = false)]
        public List<VirtualMachineBaseIndependentFilterSpec> FilterSpec { get; set; }

        /// <summary>
        /// The change mode of the device.  The values of the mode will be one of *VirtualDeviceConfigSpecChangeMode_enum* enumerations. On unset, default to &#39;fail&#39;.  ***Since:*** vSphere API Release 8.0.0.1 
        /// </summary>
        /// <value>The change mode of the device.  The values of the mode will be one of *VirtualDeviceConfigSpecChangeMode_enum* enumerations. On unset, default to &#39;fail&#39;.  ***Since:*** vSphere API Release 8.0.0.1 </value>
        [DataMember(Name = "changeMode", EmitDefaultValue = false)]
        public string ChangeMode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VirtualDeviceConfigSpec {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Operation: ").Append(Operation).Append("\n");
            sb.Append("  FileOperation: ").Append(FileOperation).Append("\n");
            sb.Append("  Device: ").Append(Device).Append("\n");
            sb.Append("  Profile: ").Append(Profile).Append("\n");
            sb.Append("  Backing: ").Append(Backing).Append("\n");
            sb.Append("  FilterSpec: ").Append(FilterSpec).Append("\n");
            sb.Append("  ChangeMode: ").Append(ChangeMode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
