/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// VirtualMachineSummary
    /// </summary>
    [DataContract(Name = "VirtualMachineSummary")]
    public partial class VirtualMachineSummary : DataObject, IValidatableObject
    {

        /// <summary>
        /// Overall alarm status on this node.  In releases after vSphere API 5.0, vSphere Servers might not generate property collector update notifications for this property. To obtain the latest value of the property, you can use PropertyCollector methods RetrievePropertiesEx or WaitForUpdatesEx. If you use the PropertyCollector.WaitForUpdatesEx method, specify an empty string for the version parameter. Since this property is on a DataObject, an update returned by WaitForUpdatesEx may contain values for this property when some other property on the DataObject changes. If this update is a result of a call to WaitForUpdatesEx with a non-empty version parameter, the value for this property may not be current. 
        /// </summary>
        /// <value>Overall alarm status on this node.  In releases after vSphere API 5.0, vSphere Servers might not generate property collector update notifications for this property. To obtain the latest value of the property, you can use PropertyCollector methods RetrievePropertiesEx or WaitForUpdatesEx. If you use the PropertyCollector.WaitForUpdatesEx method, specify an empty string for the version parameter. Since this property is on a DataObject, an update returned by WaitForUpdatesEx may contain values for this property when some other property on the DataObject changes. If this update is a result of a call to WaitForUpdatesEx with a non-empty version parameter, the value for this property may not be current. </value>
        [DataMember(Name = "overallStatus", IsRequired = true, EmitDefaultValue = true)]
        public ManagedEntityStatusEnum OverallStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="VirtualMachineSummary" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VirtualMachineSummary() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VirtualMachineSummary" /> class.
        /// </summary>
        /// <param name="vm">Reference to the virtual machine managed object.  Refers instance of *VirtualMachine*. .</param>
        /// <param name="runtime">Runtime and state information of a running virtual machine.  Most of this information is also available when a virtual machine is powered off. In that case, it contains information from the last run, if available.  (required).</param>
        /// <param name="guest">Guest operating system and VMware Tools information.  See *VirtualMachine.guest* for more information. .</param>
        /// <param name="config">Basic configuration information about the virtual machine.  This information is not available when the virtual machine is unavailable, for instance, when it is being created or deleted.  (required).</param>
        /// <param name="storage">Storage information of the virtual machine.  It can be explicitly refreshed with the *VirtualMachine.RefreshStorageInfo* operation. In releases after vSphere API 5.0, vSphere Servers might not generate property collector update notifications for this property. To obtain the latest value of the property, you can use PropertyCollector methods RetrievePropertiesEx or WaitForUpdatesEx. If you use the PropertyCollector.WaitForUpdatesEx method, specify an empty string for the version parameter. Since this property is on a DataObject, an update returned by WaitForUpdatesEx may contain values for this property when some other property on the DataObject changes. If this update is a result of a call to WaitForUpdatesEx with a non-empty version parameter, the value for this property may not be current. .</param>
        /// <param name="quickStats">A set of statistics that are typically updated with near real-time regularity.  This data object type does not support notification, for scalability reasons. Therefore, changes in QuickStats do not generate property collector updates. To monitor statistics values, use the statistics and alarms modules instead.  (required).</param>
        /// <param name="overallStatus">Overall alarm status on this node.  In releases after vSphere API 5.0, vSphere Servers might not generate property collector update notifications for this property. To obtain the latest value of the property, you can use PropertyCollector methods RetrievePropertiesEx or WaitForUpdatesEx. If you use the PropertyCollector.WaitForUpdatesEx method, specify an empty string for the version parameter. Since this property is on a DataObject, an update returned by WaitForUpdatesEx may contain values for this property when some other property on the DataObject changes. If this update is a result of a call to WaitForUpdatesEx with a non-empty version parameter, the value for this property may not be current.  (required).</param>
        /// <param name="customValue">Custom field values. .</param>
        /// <param name="typeName">The type discriminator. Refers to the name of a valid data object type.  (required) (default to &quot;VirtualMachineSummary&quot;).</param>
        public VirtualMachineSummary(ManagedObjectReference vm = default, VirtualMachineRuntimeInfo runtime = default, VirtualMachineGuestSummary guest = default, VirtualMachineConfigSummary config = default, VirtualMachineStorageSummary storage = default, VirtualMachineQuickStats quickStats = default, ManagedEntityStatusEnum overallStatus = default, List<CustomFieldValue> customValue = default, string typeName = @"VirtualMachineSummary") : base()
        {
            // to ensure "runtime" is required (not null)
            if (runtime == null)
            {
                throw new ArgumentNullException("runtime is a required property for VirtualMachineSummary and cannot be null");
            }
            this.Runtime = runtime;
            // to ensure "config" is required (not null)
            if (config == null)
            {
                throw new ArgumentNullException("config is a required property for VirtualMachineSummary and cannot be null");
            }
            this.Config = config;
            // to ensure "quickStats" is required (not null)
            if (quickStats == null)
            {
                throw new ArgumentNullException("quickStats is a required property for VirtualMachineSummary and cannot be null");
            }
            this.QuickStats = quickStats;
            this.OverallStatus = overallStatus;
            this.Vm = vm;
            this.Guest = guest;
            this.Storage = storage;
            this.CustomValue = customValue;
        }

        /// <summary>
        /// Reference to the virtual machine managed object.  Refers instance of *VirtualMachine*. 
        /// </summary>
        /// <value>Reference to the virtual machine managed object.  Refers instance of *VirtualMachine*. </value>
        [DataMember(Name = "vm", EmitDefaultValue = false)]
        public ManagedObjectReference Vm { get; set; }

        /// <summary>
        /// Runtime and state information of a running virtual machine.  Most of this information is also available when a virtual machine is powered off. In that case, it contains information from the last run, if available. 
        /// </summary>
        /// <value>Runtime and state information of a running virtual machine.  Most of this information is also available when a virtual machine is powered off. In that case, it contains information from the last run, if available. </value>
        [DataMember(Name = "runtime", IsRequired = true, EmitDefaultValue = true)]
        public VirtualMachineRuntimeInfo Runtime { get; set; }

        /// <summary>
        /// Guest operating system and VMware Tools information.  See *VirtualMachine.guest* for more information. 
        /// </summary>
        /// <value>Guest operating system and VMware Tools information.  See *VirtualMachine.guest* for more information. </value>
        [DataMember(Name = "guest", EmitDefaultValue = false)]
        public VirtualMachineGuestSummary Guest { get; set; }

        /// <summary>
        /// Basic configuration information about the virtual machine.  This information is not available when the virtual machine is unavailable, for instance, when it is being created or deleted. 
        /// </summary>
        /// <value>Basic configuration information about the virtual machine.  This information is not available when the virtual machine is unavailable, for instance, when it is being created or deleted. </value>
        [DataMember(Name = "config", IsRequired = true, EmitDefaultValue = true)]
        public VirtualMachineConfigSummary Config { get; set; }

        /// <summary>
        /// Storage information of the virtual machine.  It can be explicitly refreshed with the *VirtualMachine.RefreshStorageInfo* operation. In releases after vSphere API 5.0, vSphere Servers might not generate property collector update notifications for this property. To obtain the latest value of the property, you can use PropertyCollector methods RetrievePropertiesEx or WaitForUpdatesEx. If you use the PropertyCollector.WaitForUpdatesEx method, specify an empty string for the version parameter. Since this property is on a DataObject, an update returned by WaitForUpdatesEx may contain values for this property when some other property on the DataObject changes. If this update is a result of a call to WaitForUpdatesEx with a non-empty version parameter, the value for this property may not be current. 
        /// </summary>
        /// <value>Storage information of the virtual machine.  It can be explicitly refreshed with the *VirtualMachine.RefreshStorageInfo* operation. In releases after vSphere API 5.0, vSphere Servers might not generate property collector update notifications for this property. To obtain the latest value of the property, you can use PropertyCollector methods RetrievePropertiesEx or WaitForUpdatesEx. If you use the PropertyCollector.WaitForUpdatesEx method, specify an empty string for the version parameter. Since this property is on a DataObject, an update returned by WaitForUpdatesEx may contain values for this property when some other property on the DataObject changes. If this update is a result of a call to WaitForUpdatesEx with a non-empty version parameter, the value for this property may not be current. </value>
        [DataMember(Name = "storage", EmitDefaultValue = false)]
        public VirtualMachineStorageSummary Storage { get; set; }

        /// <summary>
        /// A set of statistics that are typically updated with near real-time regularity.  This data object type does not support notification, for scalability reasons. Therefore, changes in QuickStats do not generate property collector updates. To monitor statistics values, use the statistics and alarms modules instead. 
        /// </summary>
        /// <value>A set of statistics that are typically updated with near real-time regularity.  This data object type does not support notification, for scalability reasons. Therefore, changes in QuickStats do not generate property collector updates. To monitor statistics values, use the statistics and alarms modules instead. </value>
        [DataMember(Name = "quickStats", IsRequired = true, EmitDefaultValue = true)]
        public VirtualMachineQuickStats QuickStats { get; set; }

        /// <summary>
        /// Custom field values. 
        /// </summary>
        /// <value>Custom field values. </value>
        [DataMember(Name = "customValue", EmitDefaultValue = false)]
        public List<CustomFieldValue> CustomValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VirtualMachineSummary {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Vm: ").Append(Vm).Append("\n");
            sb.Append("  Runtime: ").Append(Runtime).Append("\n");
            sb.Append("  Guest: ").Append(Guest).Append("\n");
            sb.Append("  Config: ").Append(Config).Append("\n");
            sb.Append("  Storage: ").Append(Storage).Append("\n");
            sb.Append("  QuickStats: ").Append(QuickStats).Append("\n");
            sb.Append("  OverallStatus: ").Append(OverallStatus).Append("\n");
            sb.Append("  CustomValue: ").Append(CustomValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
