/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// The NPIV WWN source type.  Possible values: - &#x60;vc&#x60;: This set of WWNs is generated by VC server. - &#x60;host&#x60;: This set of WWNs is generated by Host Agent. - &#x60;external&#x60;: This set of WWNs is provided by the client. 
    /// </summary>
    /// <value>The NPIV WWN source type.  Possible values: - &#x60;vc&#x60;: This set of WWNs is generated by VC server. - &#x60;host&#x60;: This set of WWNs is generated by Host Agent. - &#x60;external&#x60;: This set of WWNs is provided by the client. </value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VirtualMachineConfigInfoNpivWwnTypeEnum
    {
        /// <summary>
        /// Enum Vc for value: vc
        /// </summary>
        [EnumMember(Value = "vc")]
        Vc = 1,

        /// <summary>
        /// Enum Host for value: host
        /// </summary>
        [EnumMember(Value = "host")]
        Host = 2,

        /// <summary>
        /// Enum External for value: external
        /// </summary>
        [EnumMember(Value = "external")]
        External = 3
    }

}
