/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// VirtualMachineContentLibraryItemInfo
    /// </summary>
    [DataContract(Name = "VirtualMachineContentLibraryItemInfo")]
    public partial class VirtualMachineContentLibraryItemInfo : DataObject, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VirtualMachineContentLibraryItemInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VirtualMachineContentLibraryItemInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VirtualMachineContentLibraryItemInfo" /> class.
        /// </summary>
        /// <param name="contentLibraryItemUuid">The content library item UUID  (required).</param>
        /// <param name="contentLibraryItemVersion">The content library item version is determined and managed by content library and this field stamps the version provided by CL to the VM. .</param>
        /// <param name="typeName">The type discriminator. Refers to the name of a valid data object type.  (required) (default to &quot;VirtualMachineContentLibraryItemInfo&quot;).</param>
        public VirtualMachineContentLibraryItemInfo(string contentLibraryItemUuid = default, string contentLibraryItemVersion = default, string typeName = @"VirtualMachineContentLibraryItemInfo") : base()
        {
            // to ensure "contentLibraryItemUuid" is required (not null)
            if (contentLibraryItemUuid == null)
            {
                throw new ArgumentNullException("contentLibraryItemUuid is a required property for VirtualMachineContentLibraryItemInfo and cannot be null");
            }
            this.ContentLibraryItemUuid = contentLibraryItemUuid;
            this.ContentLibraryItemVersion = contentLibraryItemVersion;
        }

        /// <summary>
        /// The content library item UUID 
        /// </summary>
        /// <value>The content library item UUID </value>
        [DataMember(Name = "contentLibraryItemUuid", IsRequired = true, EmitDefaultValue = true)]
        public string ContentLibraryItemUuid { get; set; }

        /// <summary>
        /// The content library item version is determined and managed by content library and this field stamps the version provided by CL to the VM. 
        /// </summary>
        /// <value>The content library item version is determined and managed by content library and this field stamps the version provided by CL to the VM. </value>
        [DataMember(Name = "contentLibraryItemVersion", EmitDefaultValue = false)]
        public string ContentLibraryItemVersion { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VirtualMachineContentLibraryItemInfo {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  ContentLibraryItemUuid: ").Append(ContentLibraryItemUuid).Append("\n");
            sb.Append("  ContentLibraryItemVersion: ").Append(ContentLibraryItemVersion).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
