/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// An operation on a powered-on virtual machine requests a change of networks, but the host does not have that capability. 
    /// </summary>
    [DataContract(Name = "VMotionAcrossNetworkNotSupported")]
    public partial class VMotionAcrossNetworkNotSupported : MigrationFeatureNotSupported, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VMotionAcrossNetworkNotSupported" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VMotionAcrossNetworkNotSupported() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VMotionAcrossNetworkNotSupported" /> class.
        /// </summary>
        /// <param name="typeName">The type discriminator. Refers to the name of a valid data object type.  (required) (default to &quot;VMotionAcrossNetworkNotSupported&quot;).</param>
        /// <param name="faultCause">Fault which is the cause of this fault. .</param>
        /// <param name="faultMessage">Message which has details about the error Message can also contain a key to message catalog which can be used to generate better localized messages. .</param>
        /// <param name="atSourceHost">Whether this error is for the source host.  (required).</param>
        /// <param name="failedHostName">The name of the host.  (required).</param>
        /// <param name="failedHost">The host.  Refers instance of *HostSystem*.  (required).</param>
        public VMotionAcrossNetworkNotSupported(string typeName = @"VMotionAcrossNetworkNotSupported", MethodFault faultCause = default, List<LocalizableMessage> faultMessage = default, bool atSourceHost = default, string failedHostName = default, ManagedObjectReference failedHost = default) : base(atSourceHost, failedHostName, failedHost)
        {
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VMotionAcrossNetworkNotSupported {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
