/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// VMwareDVSVspanCapability
    /// </summary>
    [DataContract(Name = "VMwareDVSVspanCapability")]
    public partial class VMwareDVSVspanCapability : DataObject, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VMwareDVSVspanCapability" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VMwareDVSVspanCapability() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VMwareDVSVspanCapability" /> class.
        /// </summary>
        /// <param name="mixedDestSupported">Flag to indicate whether mixed dest mirror session is supported on the vSphere Distributed Switch.  (required).</param>
        /// <param name="dvportSupported">Flag to indicate whether dvport mirror session is supported on the vSphere Distributed Switch.  (required).</param>
        /// <param name="remoteSourceSupported">Flag to indicate whether remote mirror source session is supported on the vSphere Distributed Switch.  (required).</param>
        /// <param name="remoteDestSupported">Flag to indicate whether remote mirror destination session is supported on the vSphere Distributed Switch.  (required).</param>
        /// <param name="encapRemoteSourceSupported">Flag to indicate whether encapsulated remote mirror source session is supported on the vSphere Distributed Switch.  (required).</param>
        /// <param name="erspanProtocolSupported">Flag to indicate whether ERSPAN protocol encapsulation is supported on the vSphere Distributed Switch. .</param>
        /// <param name="mirrorNetstackSupported">Flag to indicate whether dvport mirror can be configured to use a dedicated network stack instance. .</param>
        /// <param name="typeName">The type discriminator. Refers to the name of a valid data object type.  (required) (default to &quot;VMwareDVSVspanCapability&quot;).</param>
        public VMwareDVSVspanCapability(bool mixedDestSupported = default, bool dvportSupported = default, bool remoteSourceSupported = default, bool remoteDestSupported = default, bool encapRemoteSourceSupported = default, bool erspanProtocolSupported = default, bool mirrorNetstackSupported = default, string typeName = @"VMwareDVSVspanCapability") : base()
        {
            this.MixedDestSupported = mixedDestSupported;
            this.DvportSupported = dvportSupported;
            this.RemoteSourceSupported = remoteSourceSupported;
            this.RemoteDestSupported = remoteDestSupported;
            this.EncapRemoteSourceSupported = encapRemoteSourceSupported;
            this.ErspanProtocolSupported = erspanProtocolSupported;
            this.MirrorNetstackSupported = mirrorNetstackSupported;
        }

        /// <summary>
        /// Flag to indicate whether mixed dest mirror session is supported on the vSphere Distributed Switch. 
        /// </summary>
        /// <value>Flag to indicate whether mixed dest mirror session is supported on the vSphere Distributed Switch. </value>
        [DataMember(Name = "mixedDestSupported", IsRequired = true, EmitDefaultValue = true)]
        public bool MixedDestSupported { get; set; }

        /// <summary>
        /// Flag to indicate whether dvport mirror session is supported on the vSphere Distributed Switch. 
        /// </summary>
        /// <value>Flag to indicate whether dvport mirror session is supported on the vSphere Distributed Switch. </value>
        [DataMember(Name = "dvportSupported", IsRequired = true, EmitDefaultValue = true)]
        public bool DvportSupported { get; set; }

        /// <summary>
        /// Flag to indicate whether remote mirror source session is supported on the vSphere Distributed Switch. 
        /// </summary>
        /// <value>Flag to indicate whether remote mirror source session is supported on the vSphere Distributed Switch. </value>
        [DataMember(Name = "remoteSourceSupported", IsRequired = true, EmitDefaultValue = true)]
        public bool RemoteSourceSupported { get; set; }

        /// <summary>
        /// Flag to indicate whether remote mirror destination session is supported on the vSphere Distributed Switch. 
        /// </summary>
        /// <value>Flag to indicate whether remote mirror destination session is supported on the vSphere Distributed Switch. </value>
        [DataMember(Name = "remoteDestSupported", IsRequired = true, EmitDefaultValue = true)]
        public bool RemoteDestSupported { get; set; }

        /// <summary>
        /// Flag to indicate whether encapsulated remote mirror source session is supported on the vSphere Distributed Switch. 
        /// </summary>
        /// <value>Flag to indicate whether encapsulated remote mirror source session is supported on the vSphere Distributed Switch. </value>
        [DataMember(Name = "encapRemoteSourceSupported", IsRequired = true, EmitDefaultValue = true)]
        public bool EncapRemoteSourceSupported { get; set; }

        /// <summary>
        /// Flag to indicate whether ERSPAN protocol encapsulation is supported on the vSphere Distributed Switch. 
        /// </summary>
        /// <value>Flag to indicate whether ERSPAN protocol encapsulation is supported on the vSphere Distributed Switch. </value>
        [DataMember(Name = "erspanProtocolSupported", EmitDefaultValue = true)]
        public bool ErspanProtocolSupported { get; set; }

        /// <summary>
        /// Flag to indicate whether dvport mirror can be configured to use a dedicated network stack instance. 
        /// </summary>
        /// <value>Flag to indicate whether dvport mirror can be configured to use a dedicated network stack instance. </value>
        [DataMember(Name = "mirrorNetstackSupported", EmitDefaultValue = true)]
        public bool MirrorNetstackSupported { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VMwareDVSVspanCapability {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  MixedDestSupported: ").Append(MixedDestSupported).Append("\n");
            sb.Append("  DvportSupported: ").Append(DvportSupported).Append("\n");
            sb.Append("  RemoteSourceSupported: ").Append(RemoteSourceSupported).Append("\n");
            sb.Append("  RemoteDestSupported: ").Append(RemoteDestSupported).Append("\n");
            sb.Append("  EncapRemoteSourceSupported: ").Append(EncapRemoteSourceSupported).Append("\n");
            sb.Append("  ErspanProtocolSupported: ").Append(ErspanProtocolSupported).Append("\n");
            sb.Append("  MirrorNetstackSupported: ").Append(MirrorNetstackSupported).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
