/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// VsanClusterEncryptionHealthSummary
    /// </summary>
    [DataContract(Name = "VsanClusterEncryptionHealthSummary")]
    public partial class VsanClusterEncryptionHealthSummary : DataObject, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VsanClusterEncryptionHealthSummary" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VsanClusterEncryptionHealthSummary() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VsanClusterEncryptionHealthSummary" /> class.
        /// </summary>
        /// <param name="overallHealth">Overall health state for encryption configuration and Key Management Server connection on vCenter and across all hosts in the cluster. .</param>
        /// <param name="configHealth">Encryption configuration consistency health across all hosts in the cluster. .</param>
        /// <param name="kmsHealth">Key Management Server connection health on vCenter and across all hosts in the cluster. .</param>
        /// <param name="vcKmsResult">Key Management Servers connection health result on vCenter side. .</param>
        /// <param name="hostResults">Encryption health results on all of vSAN hosts in the cluster. .</param>
        /// <param name="aesniHealth">AES-NI configuration consistency health across all hosts in the cluster.  Valid value can be \\[&#39;green&#39; , &#39;yellow&#39;, &#39;red&#39;, &#39;unknown&#39;\\] .</param>
        /// <param name="typeName">The type discriminator. Refers to the name of a valid data object type.  (required) (default to &quot;VsanClusterEncryptionHealthSummary&quot;).</param>
        public VsanClusterEncryptionHealthSummary(string overallHealth = default, string configHealth = default, string kmsHealth = default, VsanVcKmipServersHealth vcKmsResult = default, List<VsanEncryptionHealthSummary> hostResults = default, string aesniHealth = default, string typeName = @"VsanClusterEncryptionHealthSummary") : base()
        {
            this.OverallHealth = overallHealth;
            this.ConfigHealth = configHealth;
            this.KmsHealth = kmsHealth;
            this.VcKmsResult = vcKmsResult;
            this.HostResults = hostResults;
            this.AesniHealth = aesniHealth;
        }

        /// <summary>
        /// Overall health state for encryption configuration and Key Management Server connection on vCenter and across all hosts in the cluster. 
        /// </summary>
        /// <value>Overall health state for encryption configuration and Key Management Server connection on vCenter and across all hosts in the cluster. </value>
        [DataMember(Name = "overallHealth", EmitDefaultValue = false)]
        public string OverallHealth { get; set; }

        /// <summary>
        /// Encryption configuration consistency health across all hosts in the cluster. 
        /// </summary>
        /// <value>Encryption configuration consistency health across all hosts in the cluster. </value>
        [DataMember(Name = "configHealth", EmitDefaultValue = false)]
        public string ConfigHealth { get; set; }

        /// <summary>
        /// Key Management Server connection health on vCenter and across all hosts in the cluster. 
        /// </summary>
        /// <value>Key Management Server connection health on vCenter and across all hosts in the cluster. </value>
        [DataMember(Name = "kmsHealth", EmitDefaultValue = false)]
        public string KmsHealth { get; set; }

        /// <summary>
        /// Key Management Servers connection health result on vCenter side. 
        /// </summary>
        /// <value>Key Management Servers connection health result on vCenter side. </value>
        [DataMember(Name = "vcKmsResult", EmitDefaultValue = false)]
        public VsanVcKmipServersHealth VcKmsResult { get; set; }

        /// <summary>
        /// Encryption health results on all of vSAN hosts in the cluster. 
        /// </summary>
        /// <value>Encryption health results on all of vSAN hosts in the cluster. </value>
        [DataMember(Name = "hostResults", EmitDefaultValue = false)]
        public List<VsanEncryptionHealthSummary> HostResults { get; set; }

        /// <summary>
        /// AES-NI configuration consistency health across all hosts in the cluster.  Valid value can be \\[&#39;green&#39; , &#39;yellow&#39;, &#39;red&#39;, &#39;unknown&#39;\\] 
        /// </summary>
        /// <value>AES-NI configuration consistency health across all hosts in the cluster.  Valid value can be \\[&#39;green&#39; , &#39;yellow&#39;, &#39;red&#39;, &#39;unknown&#39;\\] </value>
        [DataMember(Name = "aesniHealth", EmitDefaultValue = false)]
        public string AesniHealth { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VsanClusterEncryptionHealthSummary {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  OverallHealth: ").Append(OverallHealth).Append("\n");
            sb.Append("  ConfigHealth: ").Append(ConfigHealth).Append("\n");
            sb.Append("  KmsHealth: ").Append(KmsHealth).Append("\n");
            sb.Append("  VcKmsResult: ").Append(VcKmsResult).Append("\n");
            sb.Append("  HostResults: ").Append(HostResults).Append("\n");
            sb.Append("  AesniHealth: ").Append(AesniHealth).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
