/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// The parameters of *VsanVcsaDeployerSystem.VsanPostConfigForVcsa*. 
    /// </summary>
    [DataContract(Name = "VsanPostConfigForVcsaRequestType")]
    public partial class VsanPostConfigForVcsaRequestType : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VsanPostConfigForVcsaRequestType" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VsanPostConfigForVcsaRequestType() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VsanPostConfigForVcsaRequestType" /> class.
        /// </summary>
        /// <param name="spec">Bootstrap specification  (required).</param>
        public VsanPostConfigForVcsaRequestType(VsanVcPostDeployConfigSpec spec = default)
        {
            // to ensure "spec" is required (not null)
            if (spec == null)
            {
                throw new ArgumentNullException("spec is a required property for VsanPostConfigForVcsaRequestType and cannot be null");
            }
            this.Spec = spec;
        }

        /// <summary>
        /// Bootstrap specification 
        /// </summary>
        /// <value>Bootstrap specification </value>
        [DataMember(Name = "spec", IsRequired = true, EmitDefaultValue = true)]
        public VsanVcPostDeployConfigSpec Spec { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VsanPostConfigForVcsaRequestType {\n");
            sb.Append("  Spec: ").Append(Spec).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
