/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// Wipe disk eligible.  Possible values: - &#x60;WipeDiskEligible_Unknown&#x60;: Represent the value when the lower version client cannot recognize the enum value. - &#x60;Yes&#x60;: This disk is eligible for wipe. - &#x60;No&#x60;: This disk is ineligible for wipe. - &#x60;Unknown&#x60;: Whether the disk is eligible for wipe is unknown.      Because whether the disk support wipe or not is unknown. 
    /// </summary>
    /// <value>Wipe disk eligible.  Possible values: - &#x60;WipeDiskEligible_Unknown&#x60;: Represent the value when the lower version client cannot recognize the enum value. - &#x60;Yes&#x60;: This disk is eligible for wipe. - &#x60;No&#x60;: This disk is ineligible for wipe. - &#x60;Unknown&#x60;: Whether the disk is eligible for wipe is unknown.      Because whether the disk support wipe or not is unknown. </value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VsanHostWipeDiskEligibleEnum
    {
        /// <summary>
        /// Enum WipeDiskEligibleUnknown for value: WipeDiskEligible_Unknown
        /// </summary>
        [EnumMember(Value = "WipeDiskEligible_Unknown")]
        WipeDiskEligibleUnknown = 1,

        /// <summary>
        /// Enum Yes for value: Yes
        /// </summary>
        [EnumMember(Value = "Yes")]
        Yes = 2,

        /// <summary>
        /// Enum No for value: No
        /// </summary>
        [EnumMember(Value = "No")]
        No = 3,

        /// <summary>
        /// Enum Unknown for value: Unknown
        /// </summary>
        [EnumMember(Value = "Unknown")]
        Unknown = 4
    }

}
