/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// The parameters of *VsanSystemEx.VsanQueryHostStatusEx*.  This structure may be used only with operations rendered under &#x60;/vsan&#x60;. 
    /// </summary>
    [DataContract(Name = "VsanQueryHostStatusExRequestType")]
    public partial class VsanQueryHostStatusExRequestType : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VsanQueryHostStatusExRequestType" /> class.
        /// </summary>
        /// <param name="clusterUuids">A list of vSAN cluster uuids. If this parameter is provided, we will only return the runtime status of recognized clusters; And if it is omitted, we will return that of all clusters associated to this host. .</param>
        public VsanQueryHostStatusExRequestType(List<string> clusterUuids = default)
        {
            this.ClusterUuids = clusterUuids;
        }

        /// <summary>
        /// A list of vSAN cluster uuids. If this parameter is provided, we will only return the runtime status of recognized clusters; And if it is omitted, we will return that of all clusters associated to this host. 
        /// </summary>
        /// <value>A list of vSAN cluster uuids. If this parameter is provided, we will only return the runtime status of recognized clusters; And if it is omitted, we will return that of all clusters associated to this host. </value>
        [DataMember(Name = "clusterUuids", EmitDefaultValue = false)]
        public List<string> ClusterUuids { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VsanQueryHostStatusExRequestType {\n");
            sb.Append("  ClusterUuids: ").Append(ClusterUuids).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
