/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// Defines the possible operators to use for comparison of the resource model properties.  Possible values: - &#x60;EQUALS&#x60;: Check for equality of values - &#x60;GREATER&#x60;: Filters values if greater than specified constraint value. - &#x60;SMALLER&#x60;: Filters values if smaller than specified constraint value. - &#x60;POP&#x60; - &#x60;CONTAINS&#x60;: Matches value to check if it contains the specified constraint value. - &#x60;TEXTUALLY_MATCHES&#x60;: Uses Python regex re.match() function. - &#x60;VsanPropertyConstraintComparatorEnum_Unknown&#x60; 
    /// </summary>
    /// <value>Defines the possible operators to use for comparison of the resource model properties.  Possible values: - &#x60;EQUALS&#x60;: Check for equality of values - &#x60;GREATER&#x60;: Filters values if greater than specified constraint value. - &#x60;SMALLER&#x60;: Filters values if smaller than specified constraint value. - &#x60;POP&#x60; - &#x60;CONTAINS&#x60;: Matches value to check if it contains the specified constraint value. - &#x60;TEXTUALLY_MATCHES&#x60;: Uses Python regex re.match() function. - &#x60;VsanPropertyConstraintComparatorEnum_Unknown&#x60; </value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VsanPropertyConstraintComparatorEnumEnum
    {
        /// <summary>
        /// Enum EQUALS for value: EQUALS
        /// </summary>
        [EnumMember(Value = "EQUALS")]
        EQUALS = 1,

        /// <summary>
        /// Enum GREATER for value: GREATER
        /// </summary>
        [EnumMember(Value = "GREATER")]
        GREATER = 2,

        /// <summary>
        /// Enum SMALLER for value: SMALLER
        /// </summary>
        [EnumMember(Value = "SMALLER")]
        SMALLER = 3,

        /// <summary>
        /// Enum POP for value: POP
        /// </summary>
        [EnumMember(Value = "POP")]
        POP = 4,

        /// <summary>
        /// Enum CONTAINS for value: CONTAINS
        /// </summary>
        [EnumMember(Value = "CONTAINS")]
        CONTAINS = 5,

        /// <summary>
        /// Enum TEXTUALLYMATCHES for value: TEXTUALLY_MATCHES
        /// </summary>
        [EnumMember(Value = "TEXTUALLY_MATCHES")]
        TEXTUALLYMATCHES = 6,

        /// <summary>
        /// Enum VsanPropertyConstraintComparatorEnumUnknown for value: VsanPropertyConstraintComparatorEnum_Unknown
        /// </summary>
        [EnumMember(Value = "VsanPropertyConstraintComparatorEnum_Unknown")]
        VsanPropertyConstraintComparatorEnumUnknown = 7
    }

}
