/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// VsanCloudHealthStatus
    /// </summary>
    [DataContract(Name = "VsanCloudHealthStatus")]
    public partial class VsanCloudHealthStatus : DataObject, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VsanCloudHealthStatus" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VsanCloudHealthStatus() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VsanCloudHealthStatus" /> class.
        /// </summary>
        /// <param name="collectorRunning">Running status of the collector. .</param>
        /// <param name="lastSentTimestamp">A string timestamp of last data sent.  When data was not sent, &#39;None&#39; is returned. .</param>
        /// <param name="internetConnectivity">Status for the internet connectivity currently test connection to https://vcsa.vmware.com/ .</param>
        /// <param name="typeName">The type discriminator. Refers to the name of a valid data object type.  (required) (default to &quot;VsanCloudHealthStatus&quot;).</param>
        public VsanCloudHealthStatus(bool collectorRunning = default, string lastSentTimestamp = default, bool internetConnectivity = default, string typeName = @"VsanCloudHealthStatus") : base()
        {
            this.CollectorRunning = collectorRunning;
            this.LastSentTimestamp = lastSentTimestamp;
            this.InternetConnectivity = internetConnectivity;
        }

        /// <summary>
        /// Running status of the collector. 
        /// </summary>
        /// <value>Running status of the collector. </value>
        [DataMember(Name = "collectorRunning", EmitDefaultValue = true)]
        public bool CollectorRunning { get; set; }

        /// <summary>
        /// A string timestamp of last data sent.  When data was not sent, &#39;None&#39; is returned. 
        /// </summary>
        /// <value>A string timestamp of last data sent.  When data was not sent, &#39;None&#39; is returned. </value>
        [DataMember(Name = "lastSentTimestamp", EmitDefaultValue = false)]
        public string LastSentTimestamp { get; set; }

        /// <summary>
        /// Status for the internet connectivity currently test connection to https://vcsa.vmware.com/ 
        /// </summary>
        /// <value>Status for the internet connectivity currently test connection to https://vcsa.vmware.com/ </value>
        [DataMember(Name = "internetConnectivity", EmitDefaultValue = true)]
        public bool InternetConnectivity { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VsanCloudHealthStatus {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  CollectorRunning: ").Append(CollectorRunning).Append("\n");
            sb.Append("  LastSentTimestamp: ").Append(LastSentTimestamp).Append("\n");
            sb.Append("  InternetConnectivity: ").Append(InternetConnectivity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }

}
