/*
 * Virtual Infrastructure JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 9.1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vcenter.ViJson.OpenApi.Client.OpenAPIDateConverter;

namespace Vcenter.ViJson.OpenApi.Model
{
    /// <summary>
    /// Possible values: - &#x60;svmotion&#x60;: storage vmotion resolution - &#x60;relocate&#x60;: relocate resolution 
    /// </summary>
    /// <value>Possible values: - &#x60;svmotion&#x60;: storage vmotion resolution - &#x60;relocate&#x60;: relocate resolution </value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum WillLoseHAProtectionResolutionEnum
    {
        /// <summary>
        /// Enum Svmotion for value: svmotion
        /// </summary>
        [EnumMember(Value = "svmotion")]
        Svmotion = 1,

        /// <summary>
        /// Enum Relocate for value: relocate
        /// </summary>
        [EnumMember(Value = "relocate")]
        Relocate = 2
    }

}
